// Code generated by ent, DO NOT EDIT.

package referral

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/jordanlanch/industrydb/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Referral {
	return predicate.Referral(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Referral {
	return predicate.Referral(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Referral {
	return predicate.Referral(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Referral {
	return predicate.Referral(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Referral {
	return predicate.Referral(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Referral {
	return predicate.Referral(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Referral {
	return predicate.Referral(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Referral {
	return predicate.Referral(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Referral {
	return predicate.Referral(sql.FieldLTE(FieldID, id))
}

// ReferrerUserID applies equality check predicate on the "referrer_user_id" field. It's identical to ReferrerUserIDEQ.
func ReferrerUserID(v int) predicate.Referral {
	return predicate.Referral(sql.FieldEQ(FieldReferrerUserID, v))
}

// ReferredUserID applies equality check predicate on the "referred_user_id" field. It's identical to ReferredUserIDEQ.
func ReferredUserID(v int) predicate.Referral {
	return predicate.Referral(sql.FieldEQ(FieldReferredUserID, v))
}

// ReferralCode applies equality check predicate on the "referral_code" field. It's identical to ReferralCodeEQ.
func ReferralCode(v string) predicate.Referral {
	return predicate.Referral(sql.FieldEQ(FieldReferralCode, v))
}

// RewardAmount applies equality check predicate on the "reward_amount" field. It's identical to RewardAmountEQ.
func RewardAmount(v float64) predicate.Referral {
	return predicate.Referral(sql.FieldEQ(FieldRewardAmount, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldEQ(FieldCreatedAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldEQ(FieldCompletedAt, v))
}

// RewardedAt applies equality check predicate on the "rewarded_at" field. It's identical to RewardedAtEQ.
func RewardedAt(v time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldEQ(FieldRewardedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldEQ(FieldExpiresAt, v))
}

// ReferrerUserIDEQ applies the EQ predicate on the "referrer_user_id" field.
func ReferrerUserIDEQ(v int) predicate.Referral {
	return predicate.Referral(sql.FieldEQ(FieldReferrerUserID, v))
}

// ReferrerUserIDNEQ applies the NEQ predicate on the "referrer_user_id" field.
func ReferrerUserIDNEQ(v int) predicate.Referral {
	return predicate.Referral(sql.FieldNEQ(FieldReferrerUserID, v))
}

// ReferrerUserIDIn applies the In predicate on the "referrer_user_id" field.
func ReferrerUserIDIn(vs ...int) predicate.Referral {
	return predicate.Referral(sql.FieldIn(FieldReferrerUserID, vs...))
}

// ReferrerUserIDNotIn applies the NotIn predicate on the "referrer_user_id" field.
func ReferrerUserIDNotIn(vs ...int) predicate.Referral {
	return predicate.Referral(sql.FieldNotIn(FieldReferrerUserID, vs...))
}

// ReferredUserIDEQ applies the EQ predicate on the "referred_user_id" field.
func ReferredUserIDEQ(v int) predicate.Referral {
	return predicate.Referral(sql.FieldEQ(FieldReferredUserID, v))
}

// ReferredUserIDNEQ applies the NEQ predicate on the "referred_user_id" field.
func ReferredUserIDNEQ(v int) predicate.Referral {
	return predicate.Referral(sql.FieldNEQ(FieldReferredUserID, v))
}

// ReferredUserIDIn applies the In predicate on the "referred_user_id" field.
func ReferredUserIDIn(vs ...int) predicate.Referral {
	return predicate.Referral(sql.FieldIn(FieldReferredUserID, vs...))
}

// ReferredUserIDNotIn applies the NotIn predicate on the "referred_user_id" field.
func ReferredUserIDNotIn(vs ...int) predicate.Referral {
	return predicate.Referral(sql.FieldNotIn(FieldReferredUserID, vs...))
}

// ReferredUserIDIsNil applies the IsNil predicate on the "referred_user_id" field.
func ReferredUserIDIsNil() predicate.Referral {
	return predicate.Referral(sql.FieldIsNull(FieldReferredUserID))
}

// ReferredUserIDNotNil applies the NotNil predicate on the "referred_user_id" field.
func ReferredUserIDNotNil() predicate.Referral {
	return predicate.Referral(sql.FieldNotNull(FieldReferredUserID))
}

// ReferralCodeEQ applies the EQ predicate on the "referral_code" field.
func ReferralCodeEQ(v string) predicate.Referral {
	return predicate.Referral(sql.FieldEQ(FieldReferralCode, v))
}

// ReferralCodeNEQ applies the NEQ predicate on the "referral_code" field.
func ReferralCodeNEQ(v string) predicate.Referral {
	return predicate.Referral(sql.FieldNEQ(FieldReferralCode, v))
}

// ReferralCodeIn applies the In predicate on the "referral_code" field.
func ReferralCodeIn(vs ...string) predicate.Referral {
	return predicate.Referral(sql.FieldIn(FieldReferralCode, vs...))
}

// ReferralCodeNotIn applies the NotIn predicate on the "referral_code" field.
func ReferralCodeNotIn(vs ...string) predicate.Referral {
	return predicate.Referral(sql.FieldNotIn(FieldReferralCode, vs...))
}

// ReferralCodeGT applies the GT predicate on the "referral_code" field.
func ReferralCodeGT(v string) predicate.Referral {
	return predicate.Referral(sql.FieldGT(FieldReferralCode, v))
}

// ReferralCodeGTE applies the GTE predicate on the "referral_code" field.
func ReferralCodeGTE(v string) predicate.Referral {
	return predicate.Referral(sql.FieldGTE(FieldReferralCode, v))
}

// ReferralCodeLT applies the LT predicate on the "referral_code" field.
func ReferralCodeLT(v string) predicate.Referral {
	return predicate.Referral(sql.FieldLT(FieldReferralCode, v))
}

// ReferralCodeLTE applies the LTE predicate on the "referral_code" field.
func ReferralCodeLTE(v string) predicate.Referral {
	return predicate.Referral(sql.FieldLTE(FieldReferralCode, v))
}

// ReferralCodeContains applies the Contains predicate on the "referral_code" field.
func ReferralCodeContains(v string) predicate.Referral {
	return predicate.Referral(sql.FieldContains(FieldReferralCode, v))
}

// ReferralCodeHasPrefix applies the HasPrefix predicate on the "referral_code" field.
func ReferralCodeHasPrefix(v string) predicate.Referral {
	return predicate.Referral(sql.FieldHasPrefix(FieldReferralCode, v))
}

// ReferralCodeHasSuffix applies the HasSuffix predicate on the "referral_code" field.
func ReferralCodeHasSuffix(v string) predicate.Referral {
	return predicate.Referral(sql.FieldHasSuffix(FieldReferralCode, v))
}

// ReferralCodeEqualFold applies the EqualFold predicate on the "referral_code" field.
func ReferralCodeEqualFold(v string) predicate.Referral {
	return predicate.Referral(sql.FieldEqualFold(FieldReferralCode, v))
}

// ReferralCodeContainsFold applies the ContainsFold predicate on the "referral_code" field.
func ReferralCodeContainsFold(v string) predicate.Referral {
	return predicate.Referral(sql.FieldContainsFold(FieldReferralCode, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Referral {
	return predicate.Referral(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Referral {
	return predicate.Referral(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Referral {
	return predicate.Referral(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Referral {
	return predicate.Referral(sql.FieldNotIn(FieldStatus, vs...))
}

// RewardTypeEQ applies the EQ predicate on the "reward_type" field.
func RewardTypeEQ(v RewardType) predicate.Referral {
	return predicate.Referral(sql.FieldEQ(FieldRewardType, v))
}

// RewardTypeNEQ applies the NEQ predicate on the "reward_type" field.
func RewardTypeNEQ(v RewardType) predicate.Referral {
	return predicate.Referral(sql.FieldNEQ(FieldRewardType, v))
}

// RewardTypeIn applies the In predicate on the "reward_type" field.
func RewardTypeIn(vs ...RewardType) predicate.Referral {
	return predicate.Referral(sql.FieldIn(FieldRewardType, vs...))
}

// RewardTypeNotIn applies the NotIn predicate on the "reward_type" field.
func RewardTypeNotIn(vs ...RewardType) predicate.Referral {
	return predicate.Referral(sql.FieldNotIn(FieldRewardType, vs...))
}

// RewardAmountEQ applies the EQ predicate on the "reward_amount" field.
func RewardAmountEQ(v float64) predicate.Referral {
	return predicate.Referral(sql.FieldEQ(FieldRewardAmount, v))
}

// RewardAmountNEQ applies the NEQ predicate on the "reward_amount" field.
func RewardAmountNEQ(v float64) predicate.Referral {
	return predicate.Referral(sql.FieldNEQ(FieldRewardAmount, v))
}

// RewardAmountIn applies the In predicate on the "reward_amount" field.
func RewardAmountIn(vs ...float64) predicate.Referral {
	return predicate.Referral(sql.FieldIn(FieldRewardAmount, vs...))
}

// RewardAmountNotIn applies the NotIn predicate on the "reward_amount" field.
func RewardAmountNotIn(vs ...float64) predicate.Referral {
	return predicate.Referral(sql.FieldNotIn(FieldRewardAmount, vs...))
}

// RewardAmountGT applies the GT predicate on the "reward_amount" field.
func RewardAmountGT(v float64) predicate.Referral {
	return predicate.Referral(sql.FieldGT(FieldRewardAmount, v))
}

// RewardAmountGTE applies the GTE predicate on the "reward_amount" field.
func RewardAmountGTE(v float64) predicate.Referral {
	return predicate.Referral(sql.FieldGTE(FieldRewardAmount, v))
}

// RewardAmountLT applies the LT predicate on the "reward_amount" field.
func RewardAmountLT(v float64) predicate.Referral {
	return predicate.Referral(sql.FieldLT(FieldRewardAmount, v))
}

// RewardAmountLTE applies the LTE predicate on the "reward_amount" field.
func RewardAmountLTE(v float64) predicate.Referral {
	return predicate.Referral(sql.FieldLTE(FieldRewardAmount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldLTE(FieldCreatedAt, v))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.Referral {
	return predicate.Referral(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.Referral {
	return predicate.Referral(sql.FieldNotNull(FieldCompletedAt))
}

// RewardedAtEQ applies the EQ predicate on the "rewarded_at" field.
func RewardedAtEQ(v time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldEQ(FieldRewardedAt, v))
}

// RewardedAtNEQ applies the NEQ predicate on the "rewarded_at" field.
func RewardedAtNEQ(v time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldNEQ(FieldRewardedAt, v))
}

// RewardedAtIn applies the In predicate on the "rewarded_at" field.
func RewardedAtIn(vs ...time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldIn(FieldRewardedAt, vs...))
}

// RewardedAtNotIn applies the NotIn predicate on the "rewarded_at" field.
func RewardedAtNotIn(vs ...time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldNotIn(FieldRewardedAt, vs...))
}

// RewardedAtGT applies the GT predicate on the "rewarded_at" field.
func RewardedAtGT(v time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldGT(FieldRewardedAt, v))
}

// RewardedAtGTE applies the GTE predicate on the "rewarded_at" field.
func RewardedAtGTE(v time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldGTE(FieldRewardedAt, v))
}

// RewardedAtLT applies the LT predicate on the "rewarded_at" field.
func RewardedAtLT(v time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldLT(FieldRewardedAt, v))
}

// RewardedAtLTE applies the LTE predicate on the "rewarded_at" field.
func RewardedAtLTE(v time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldLTE(FieldRewardedAt, v))
}

// RewardedAtIsNil applies the IsNil predicate on the "rewarded_at" field.
func RewardedAtIsNil() predicate.Referral {
	return predicate.Referral(sql.FieldIsNull(FieldRewardedAt))
}

// RewardedAtNotNil applies the NotNil predicate on the "rewarded_at" field.
func RewardedAtNotNil() predicate.Referral {
	return predicate.Referral(sql.FieldNotNull(FieldRewardedAt))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.Referral {
	return predicate.Referral(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.Referral {
	return predicate.Referral(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.Referral {
	return predicate.Referral(sql.FieldNotNull(FieldExpiresAt))
}

// HasReferrer applies the HasEdge predicate on the "referrer" edge.
func HasReferrer() predicate.Referral {
	return predicate.Referral(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ReferrerTable, ReferrerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReferrerWith applies the HasEdge predicate on the "referrer" edge with a given conditions (other predicates).
func HasReferrerWith(preds ...predicate.User) predicate.Referral {
	return predicate.Referral(func(s *sql.Selector) {
		step := newReferrerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasReferred applies the HasEdge predicate on the "referred" edge.
func HasReferred() predicate.Referral {
	return predicate.Referral(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ReferredTable, ReferredColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReferredWith applies the HasEdge predicate on the "referred" edge with a given conditions (other predicates).
func HasReferredWith(preds ...predicate.User) predicate.Referral {
	return predicate.Referral(func(s *sql.Selector) {
		step := newReferredStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Referral) predicate.Referral {
	return predicate.Referral(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Referral) predicate.Referral {
	return predicate.Referral(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Referral) predicate.Referral {
	return predicate.Referral(sql.NotPredicates(p))
}
