package industries

// GymSubNiches returns all gym/fitness sub-niches
func GymSubNiches() []SubNicheConfig {
	return []SubNicheConfig{
		{
			ID:          "fitness",
			Name:        "Traditional Gym",
			Icon:        "💪",
			OSMTag:      "sport",
			OSMValues:   []string{"fitness", "gym", "multi", "fitness_centre"},
			Description: "Traditional gyms with weights and cardio equipment",
			SortOrder:   1,
			Popular:     true,
		},
		{
			ID:          "crossfit",
			Name:        "CrossFit",
			Icon:        "🏋️",
			OSMTag:      "sport",
			OSMValues:   []string{"crossfit"},
			Description: "CrossFit boxes and functional fitness",
			SortOrder:   2,
			Popular:     true,
		},
		{
			ID:          "yoga",
			Name:        "Yoga Studio",
			Icon:        "🧘",
			OSMTag:      "sport",
			OSMValues:   []string{"yoga"},
			Description: "Yoga studios and classes",
			SortOrder:   3,
			Popular:     true,
		},
		{
			ID:          "pilates",
			Name:        "Pilates",
			Icon:        "🤸",
			OSMTag:      "sport",
			OSMValues:   []string{"pilates"},
			Description: "Pilates studios and reformer classes",
			SortOrder:   4,
			Popular:     false,
		},
		{
			ID:          "boxing",
			Name:        "Boxing/MMA",
			Icon:        "🥊",
			OSMTag:      "sport",
			OSMValues:   []string{"boxing", "martial_arts", "mma", "kickboxing"},
			Description: "Boxing gyms, MMA, and martial arts studios",
			SortOrder:   5,
			Popular:     false,
		},
		{
			ID:          "cycling",
			Name:        "Cycling Studio",
			Icon:        "🚴",
			OSMTag:      "sport",
			OSMValues:   []string{"cycling", "spinning"},
			Description: "Indoor cycling and spin studios",
			SortOrder:   6,
			Popular:     false,
		},
		{
			ID:          "climbing",
			Name:        "Rock Climbing",
			Icon:        "🧗",
			OSMTag:      "sport",
			OSMValues:   []string{"climbing"},
			Description: "Rock climbing gyms and bouldering",
			SortOrder:   7,
			Popular:     false,
		},
		{
			ID:          "swimming",
			Name:        "Swimming Pool",
			Icon:        "🏊",
			OSMTag:      "sport",
			OSMValues:   []string{"swimming"},
			Description: "Swimming pools and aquatic centers",
			SortOrder:   8,
			Popular:     false,
		},
		{
			ID:          "dance",
			Name:        "Dance Studio",
			Icon:        "💃",
			OSMTag:      "sport",
			OSMValues:   []string{"dance"},
			Description: "Dance studios and classes",
			SortOrder:   9,
			Popular:     false,
		},
		{
			ID:          "other",
			Name:        "Other Fitness",
			Icon:        "🏃",
			OSMTag:      "sport",
			OSMValues:   []string{},
			Description: "Other fitness and sports facilities",
			SortOrder:   10,
			Popular:     false,
		},
	}
}
