package industries

// TattooSubNiches returns all tattoo style sub-niches
func TattooSubNiches() []SubNicheConfig {
	return []SubNicheConfig{
		{
			ID:          "traditional",
			Name:        "Traditional American",
			Icon:        "⚓",
			OSMTag:      "",
			OSMValues:   []string{"traditional", "old_school"},
			Description: "Traditional American/old school tattoos",
			SortOrder:   1,
			Popular:     true,
		},
		{
			ID:          "japanese",
			Name:        "Japanese/Irezumi",
			Icon:        "🐉",
			OSMTag:      "",
			OSMValues:   []string{"japanese", "irezumi"},
			Description: "Japanese style tattoos and irezumi",
			SortOrder:   2,
			Popular:     true,
		},
		{
			ID:          "realism",
			Name:        "Realism",
			Icon:        "📷",
			OSMTag:      "",
			OSMValues:   []string{"realism", "realistic"},
			Description: "Realistic and photorealistic tattoos",
			SortOrder:   3,
			Popular:     true,
		},
		{
			ID:          "watercolor",
			Name:        "Watercolor",
			Icon:        "🎨",
			OSMTag:      "",
			OSMValues:   []string{"watercolor", "watercolour"},
			Description: "Watercolor style tattoos",
			SortOrder:   4,
			Popular:     false,
		},
		{
			ID:          "neo_traditional",
			Name:        "Neo-Traditional",
			Icon:        "🌹",
			OSMTag:      "",
			OSMValues:   []string{"neo_traditional", "new_school"},
			Description: "Neo-traditional and new school tattoos",
			SortOrder:   5,
			Popular:     false,
		},
		{
			ID:          "tribal",
			Name:        "Tribal",
			Icon:        "🗿",
			OSMTag:      "",
			OSMValues:   []string{"tribal", "polynesian", "maori"},
			Description: "Tribal, Polynesian, and Maori tattoos",
			SortOrder:   6,
			Popular:     false,
		},
		{
			ID:          "blackwork",
			Name:        "Blackwork",
			Icon:        "⬛",
			OSMTag:      "",
			OSMValues:   []string{"blackwork", "dotwork"},
			Description: "Blackwork and dotwork tattoos",
			SortOrder:   7,
			Popular:     false,
		},
		{
			ID:          "geometric",
			Name:        "Geometric",
			Icon:        "🔷",
			OSMTag:      "",
			OSMValues:   []string{"geometric", "mandala"},
			Description: "Geometric patterns and mandalas",
			SortOrder:   8,
			Popular:     false,
		},
		{
			ID:          "portrait",
			Name:        "Portrait",
			Icon:        "👤",
			OSMTag:      "",
			OSMValues:   []string{"portrait"},
			Description: "Portrait tattoos and faces",
			SortOrder:   9,
			Popular:     false,
		},
		{
			ID:          "minimalist",
			Name:        "Minimalist",
			Icon:        "✨",
			OSMTag:      "",
			OSMValues:   []string{"minimalist", "fine_line"},
			Description: "Minimalist and fine line tattoos",
			SortOrder:   10,
			Popular:     false,
		},
		{
			ID:          "lettering",
			Name:        "Lettering/Script",
			Icon:        "✍️",
			OSMTag:      "",
			OSMValues:   []string{"lettering", "script", "calligraphy"},
			Description: "Lettering, script, and calligraphy tattoos",
			SortOrder:   11,
			Popular:     false,
		},
		{
			ID:          "other",
			Name:        "Mixed/Other Styles",
			Icon:        "🎨",
			OSMTag:      "",
			OSMValues:   []string{},
			Description: "Other or mixed tattoo styles",
			SortOrder:   12,
			Popular:     false,
		},
	}
}
