// Code generated by ent, DO NOT EDIT.

package emailcampaign

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/jordanlanch/industrydb/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEQ(FieldName, v))
}

// Subject applies equality check predicate on the "subject" field. It's identical to SubjectEQ.
func Subject(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEQ(FieldSubject, v))
}

// ContentHTML applies equality check predicate on the "content_html" field. It's identical to ContentHTMLEQ.
func ContentHTML(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEQ(FieldContentHTML, v))
}

// ContentText applies equality check predicate on the "content_text" field. It's identical to ContentTextEQ.
func ContentText(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEQ(FieldContentText, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEQ(FieldUserID, v))
}

// FromEmail applies equality check predicate on the "from_email" field. It's identical to FromEmailEQ.
func FromEmail(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEQ(FieldFromEmail, v))
}

// FromName applies equality check predicate on the "from_name" field. It's identical to FromNameEQ.
func FromName(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEQ(FieldFromName, v))
}

// ReplyTo applies equality check predicate on the "reply_to" field. It's identical to ReplyToEQ.
func ReplyTo(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEQ(FieldReplyTo, v))
}

// ScheduledAt applies equality check predicate on the "scheduled_at" field. It's identical to ScheduledAtEQ.
func ScheduledAt(v time.Time) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEQ(FieldScheduledAt, v))
}

// SentAt applies equality check predicate on the "sent_at" field. It's identical to SentAtEQ.
func SentAt(v time.Time) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEQ(FieldSentAt, v))
}

// RecipientsCount applies equality check predicate on the "recipients_count" field. It's identical to RecipientsCountEQ.
func RecipientsCount(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEQ(FieldRecipientsCount, v))
}

// SentCount applies equality check predicate on the "sent_count" field. It's identical to SentCountEQ.
func SentCount(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEQ(FieldSentCount, v))
}

// FailedCount applies equality check predicate on the "failed_count" field. It's identical to FailedCountEQ.
func FailedCount(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEQ(FieldFailedCount, v))
}

// OpenedCount applies equality check predicate on the "opened_count" field. It's identical to OpenedCountEQ.
func OpenedCount(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEQ(FieldOpenedCount, v))
}

// ClickedCount applies equality check predicate on the "clicked_count" field. It's identical to ClickedCountEQ.
func ClickedCount(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEQ(FieldClickedCount, v))
}

// UnsubscribedCount applies equality check predicate on the "unsubscribed_count" field. It's identical to UnsubscribedCountEQ.
func UnsubscribedCount(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEQ(FieldUnsubscribedCount, v))
}

// SendgridBatchID applies equality check predicate on the "sendgrid_batch_id" field. It's identical to SendgridBatchIDEQ.
func SendgridBatchID(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEQ(FieldSendgridBatchID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldContainsFold(FieldName, v))
}

// SubjectEQ applies the EQ predicate on the "subject" field.
func SubjectEQ(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEQ(FieldSubject, v))
}

// SubjectNEQ applies the NEQ predicate on the "subject" field.
func SubjectNEQ(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNEQ(FieldSubject, v))
}

// SubjectIn applies the In predicate on the "subject" field.
func SubjectIn(vs ...string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldIn(FieldSubject, vs...))
}

// SubjectNotIn applies the NotIn predicate on the "subject" field.
func SubjectNotIn(vs ...string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNotIn(FieldSubject, vs...))
}

// SubjectGT applies the GT predicate on the "subject" field.
func SubjectGT(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldGT(FieldSubject, v))
}

// SubjectGTE applies the GTE predicate on the "subject" field.
func SubjectGTE(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldGTE(FieldSubject, v))
}

// SubjectLT applies the LT predicate on the "subject" field.
func SubjectLT(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldLT(FieldSubject, v))
}

// SubjectLTE applies the LTE predicate on the "subject" field.
func SubjectLTE(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldLTE(FieldSubject, v))
}

// SubjectContains applies the Contains predicate on the "subject" field.
func SubjectContains(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldContains(FieldSubject, v))
}

// SubjectHasPrefix applies the HasPrefix predicate on the "subject" field.
func SubjectHasPrefix(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldHasPrefix(FieldSubject, v))
}

// SubjectHasSuffix applies the HasSuffix predicate on the "subject" field.
func SubjectHasSuffix(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldHasSuffix(FieldSubject, v))
}

// SubjectEqualFold applies the EqualFold predicate on the "subject" field.
func SubjectEqualFold(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEqualFold(FieldSubject, v))
}

// SubjectContainsFold applies the ContainsFold predicate on the "subject" field.
func SubjectContainsFold(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldContainsFold(FieldSubject, v))
}

// ContentHTMLEQ applies the EQ predicate on the "content_html" field.
func ContentHTMLEQ(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEQ(FieldContentHTML, v))
}

// ContentHTMLNEQ applies the NEQ predicate on the "content_html" field.
func ContentHTMLNEQ(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNEQ(FieldContentHTML, v))
}

// ContentHTMLIn applies the In predicate on the "content_html" field.
func ContentHTMLIn(vs ...string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldIn(FieldContentHTML, vs...))
}

// ContentHTMLNotIn applies the NotIn predicate on the "content_html" field.
func ContentHTMLNotIn(vs ...string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNotIn(FieldContentHTML, vs...))
}

// ContentHTMLGT applies the GT predicate on the "content_html" field.
func ContentHTMLGT(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldGT(FieldContentHTML, v))
}

// ContentHTMLGTE applies the GTE predicate on the "content_html" field.
func ContentHTMLGTE(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldGTE(FieldContentHTML, v))
}

// ContentHTMLLT applies the LT predicate on the "content_html" field.
func ContentHTMLLT(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldLT(FieldContentHTML, v))
}

// ContentHTMLLTE applies the LTE predicate on the "content_html" field.
func ContentHTMLLTE(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldLTE(FieldContentHTML, v))
}

// ContentHTMLContains applies the Contains predicate on the "content_html" field.
func ContentHTMLContains(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldContains(FieldContentHTML, v))
}

// ContentHTMLHasPrefix applies the HasPrefix predicate on the "content_html" field.
func ContentHTMLHasPrefix(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldHasPrefix(FieldContentHTML, v))
}

// ContentHTMLHasSuffix applies the HasSuffix predicate on the "content_html" field.
func ContentHTMLHasSuffix(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldHasSuffix(FieldContentHTML, v))
}

// ContentHTMLEqualFold applies the EqualFold predicate on the "content_html" field.
func ContentHTMLEqualFold(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEqualFold(FieldContentHTML, v))
}

// ContentHTMLContainsFold applies the ContainsFold predicate on the "content_html" field.
func ContentHTMLContainsFold(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldContainsFold(FieldContentHTML, v))
}

// ContentTextEQ applies the EQ predicate on the "content_text" field.
func ContentTextEQ(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEQ(FieldContentText, v))
}

// ContentTextNEQ applies the NEQ predicate on the "content_text" field.
func ContentTextNEQ(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNEQ(FieldContentText, v))
}

// ContentTextIn applies the In predicate on the "content_text" field.
func ContentTextIn(vs ...string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldIn(FieldContentText, vs...))
}

// ContentTextNotIn applies the NotIn predicate on the "content_text" field.
func ContentTextNotIn(vs ...string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNotIn(FieldContentText, vs...))
}

// ContentTextGT applies the GT predicate on the "content_text" field.
func ContentTextGT(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldGT(FieldContentText, v))
}

// ContentTextGTE applies the GTE predicate on the "content_text" field.
func ContentTextGTE(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldGTE(FieldContentText, v))
}

// ContentTextLT applies the LT predicate on the "content_text" field.
func ContentTextLT(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldLT(FieldContentText, v))
}

// ContentTextLTE applies the LTE predicate on the "content_text" field.
func ContentTextLTE(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldLTE(FieldContentText, v))
}

// ContentTextContains applies the Contains predicate on the "content_text" field.
func ContentTextContains(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldContains(FieldContentText, v))
}

// ContentTextHasPrefix applies the HasPrefix predicate on the "content_text" field.
func ContentTextHasPrefix(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldHasPrefix(FieldContentText, v))
}

// ContentTextHasSuffix applies the HasSuffix predicate on the "content_text" field.
func ContentTextHasSuffix(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldHasSuffix(FieldContentText, v))
}

// ContentTextIsNil applies the IsNil predicate on the "content_text" field.
func ContentTextIsNil() predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldIsNull(FieldContentText))
}

// ContentTextNotNil applies the NotNil predicate on the "content_text" field.
func ContentTextNotNil() predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNotNull(FieldContentText))
}

// ContentTextEqualFold applies the EqualFold predicate on the "content_text" field.
func ContentTextEqualFold(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEqualFold(FieldContentText, v))
}

// ContentTextContainsFold applies the ContainsFold predicate on the "content_text" field.
func ContentTextContainsFold(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldContainsFold(FieldContentText, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNotIn(FieldStatus, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNotIn(FieldUserID, vs...))
}

// FromEmailEQ applies the EQ predicate on the "from_email" field.
func FromEmailEQ(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEQ(FieldFromEmail, v))
}

// FromEmailNEQ applies the NEQ predicate on the "from_email" field.
func FromEmailNEQ(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNEQ(FieldFromEmail, v))
}

// FromEmailIn applies the In predicate on the "from_email" field.
func FromEmailIn(vs ...string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldIn(FieldFromEmail, vs...))
}

// FromEmailNotIn applies the NotIn predicate on the "from_email" field.
func FromEmailNotIn(vs ...string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNotIn(FieldFromEmail, vs...))
}

// FromEmailGT applies the GT predicate on the "from_email" field.
func FromEmailGT(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldGT(FieldFromEmail, v))
}

// FromEmailGTE applies the GTE predicate on the "from_email" field.
func FromEmailGTE(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldGTE(FieldFromEmail, v))
}

// FromEmailLT applies the LT predicate on the "from_email" field.
func FromEmailLT(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldLT(FieldFromEmail, v))
}

// FromEmailLTE applies the LTE predicate on the "from_email" field.
func FromEmailLTE(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldLTE(FieldFromEmail, v))
}

// FromEmailContains applies the Contains predicate on the "from_email" field.
func FromEmailContains(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldContains(FieldFromEmail, v))
}

// FromEmailHasPrefix applies the HasPrefix predicate on the "from_email" field.
func FromEmailHasPrefix(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldHasPrefix(FieldFromEmail, v))
}

// FromEmailHasSuffix applies the HasSuffix predicate on the "from_email" field.
func FromEmailHasSuffix(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldHasSuffix(FieldFromEmail, v))
}

// FromEmailEqualFold applies the EqualFold predicate on the "from_email" field.
func FromEmailEqualFold(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEqualFold(FieldFromEmail, v))
}

// FromEmailContainsFold applies the ContainsFold predicate on the "from_email" field.
func FromEmailContainsFold(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldContainsFold(FieldFromEmail, v))
}

// FromNameEQ applies the EQ predicate on the "from_name" field.
func FromNameEQ(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEQ(FieldFromName, v))
}

// FromNameNEQ applies the NEQ predicate on the "from_name" field.
func FromNameNEQ(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNEQ(FieldFromName, v))
}

// FromNameIn applies the In predicate on the "from_name" field.
func FromNameIn(vs ...string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldIn(FieldFromName, vs...))
}

// FromNameNotIn applies the NotIn predicate on the "from_name" field.
func FromNameNotIn(vs ...string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNotIn(FieldFromName, vs...))
}

// FromNameGT applies the GT predicate on the "from_name" field.
func FromNameGT(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldGT(FieldFromName, v))
}

// FromNameGTE applies the GTE predicate on the "from_name" field.
func FromNameGTE(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldGTE(FieldFromName, v))
}

// FromNameLT applies the LT predicate on the "from_name" field.
func FromNameLT(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldLT(FieldFromName, v))
}

// FromNameLTE applies the LTE predicate on the "from_name" field.
func FromNameLTE(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldLTE(FieldFromName, v))
}

// FromNameContains applies the Contains predicate on the "from_name" field.
func FromNameContains(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldContains(FieldFromName, v))
}

// FromNameHasPrefix applies the HasPrefix predicate on the "from_name" field.
func FromNameHasPrefix(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldHasPrefix(FieldFromName, v))
}

// FromNameHasSuffix applies the HasSuffix predicate on the "from_name" field.
func FromNameHasSuffix(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldHasSuffix(FieldFromName, v))
}

// FromNameEqualFold applies the EqualFold predicate on the "from_name" field.
func FromNameEqualFold(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEqualFold(FieldFromName, v))
}

// FromNameContainsFold applies the ContainsFold predicate on the "from_name" field.
func FromNameContainsFold(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldContainsFold(FieldFromName, v))
}

// ReplyToEQ applies the EQ predicate on the "reply_to" field.
func ReplyToEQ(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEQ(FieldReplyTo, v))
}

// ReplyToNEQ applies the NEQ predicate on the "reply_to" field.
func ReplyToNEQ(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNEQ(FieldReplyTo, v))
}

// ReplyToIn applies the In predicate on the "reply_to" field.
func ReplyToIn(vs ...string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldIn(FieldReplyTo, vs...))
}

// ReplyToNotIn applies the NotIn predicate on the "reply_to" field.
func ReplyToNotIn(vs ...string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNotIn(FieldReplyTo, vs...))
}

// ReplyToGT applies the GT predicate on the "reply_to" field.
func ReplyToGT(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldGT(FieldReplyTo, v))
}

// ReplyToGTE applies the GTE predicate on the "reply_to" field.
func ReplyToGTE(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldGTE(FieldReplyTo, v))
}

// ReplyToLT applies the LT predicate on the "reply_to" field.
func ReplyToLT(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldLT(FieldReplyTo, v))
}

// ReplyToLTE applies the LTE predicate on the "reply_to" field.
func ReplyToLTE(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldLTE(FieldReplyTo, v))
}

// ReplyToContains applies the Contains predicate on the "reply_to" field.
func ReplyToContains(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldContains(FieldReplyTo, v))
}

// ReplyToHasPrefix applies the HasPrefix predicate on the "reply_to" field.
func ReplyToHasPrefix(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldHasPrefix(FieldReplyTo, v))
}

// ReplyToHasSuffix applies the HasSuffix predicate on the "reply_to" field.
func ReplyToHasSuffix(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldHasSuffix(FieldReplyTo, v))
}

// ReplyToIsNil applies the IsNil predicate on the "reply_to" field.
func ReplyToIsNil() predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldIsNull(FieldReplyTo))
}

// ReplyToNotNil applies the NotNil predicate on the "reply_to" field.
func ReplyToNotNil() predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNotNull(FieldReplyTo))
}

// ReplyToEqualFold applies the EqualFold predicate on the "reply_to" field.
func ReplyToEqualFold(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEqualFold(FieldReplyTo, v))
}

// ReplyToContainsFold applies the ContainsFold predicate on the "reply_to" field.
func ReplyToContainsFold(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldContainsFold(FieldReplyTo, v))
}

// ScheduledAtEQ applies the EQ predicate on the "scheduled_at" field.
func ScheduledAtEQ(v time.Time) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEQ(FieldScheduledAt, v))
}

// ScheduledAtNEQ applies the NEQ predicate on the "scheduled_at" field.
func ScheduledAtNEQ(v time.Time) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNEQ(FieldScheduledAt, v))
}

// ScheduledAtIn applies the In predicate on the "scheduled_at" field.
func ScheduledAtIn(vs ...time.Time) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldIn(FieldScheduledAt, vs...))
}

// ScheduledAtNotIn applies the NotIn predicate on the "scheduled_at" field.
func ScheduledAtNotIn(vs ...time.Time) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNotIn(FieldScheduledAt, vs...))
}

// ScheduledAtGT applies the GT predicate on the "scheduled_at" field.
func ScheduledAtGT(v time.Time) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldGT(FieldScheduledAt, v))
}

// ScheduledAtGTE applies the GTE predicate on the "scheduled_at" field.
func ScheduledAtGTE(v time.Time) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldGTE(FieldScheduledAt, v))
}

// ScheduledAtLT applies the LT predicate on the "scheduled_at" field.
func ScheduledAtLT(v time.Time) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldLT(FieldScheduledAt, v))
}

// ScheduledAtLTE applies the LTE predicate on the "scheduled_at" field.
func ScheduledAtLTE(v time.Time) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldLTE(FieldScheduledAt, v))
}

// ScheduledAtIsNil applies the IsNil predicate on the "scheduled_at" field.
func ScheduledAtIsNil() predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldIsNull(FieldScheduledAt))
}

// ScheduledAtNotNil applies the NotNil predicate on the "scheduled_at" field.
func ScheduledAtNotNil() predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNotNull(FieldScheduledAt))
}

// SentAtEQ applies the EQ predicate on the "sent_at" field.
func SentAtEQ(v time.Time) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEQ(FieldSentAt, v))
}

// SentAtNEQ applies the NEQ predicate on the "sent_at" field.
func SentAtNEQ(v time.Time) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNEQ(FieldSentAt, v))
}

// SentAtIn applies the In predicate on the "sent_at" field.
func SentAtIn(vs ...time.Time) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldIn(FieldSentAt, vs...))
}

// SentAtNotIn applies the NotIn predicate on the "sent_at" field.
func SentAtNotIn(vs ...time.Time) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNotIn(FieldSentAt, vs...))
}

// SentAtGT applies the GT predicate on the "sent_at" field.
func SentAtGT(v time.Time) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldGT(FieldSentAt, v))
}

// SentAtGTE applies the GTE predicate on the "sent_at" field.
func SentAtGTE(v time.Time) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldGTE(FieldSentAt, v))
}

// SentAtLT applies the LT predicate on the "sent_at" field.
func SentAtLT(v time.Time) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldLT(FieldSentAt, v))
}

// SentAtLTE applies the LTE predicate on the "sent_at" field.
func SentAtLTE(v time.Time) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldLTE(FieldSentAt, v))
}

// SentAtIsNil applies the IsNil predicate on the "sent_at" field.
func SentAtIsNil() predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldIsNull(FieldSentAt))
}

// SentAtNotNil applies the NotNil predicate on the "sent_at" field.
func SentAtNotNil() predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNotNull(FieldSentAt))
}

// RecipientsCountEQ applies the EQ predicate on the "recipients_count" field.
func RecipientsCountEQ(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEQ(FieldRecipientsCount, v))
}

// RecipientsCountNEQ applies the NEQ predicate on the "recipients_count" field.
func RecipientsCountNEQ(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNEQ(FieldRecipientsCount, v))
}

// RecipientsCountIn applies the In predicate on the "recipients_count" field.
func RecipientsCountIn(vs ...int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldIn(FieldRecipientsCount, vs...))
}

// RecipientsCountNotIn applies the NotIn predicate on the "recipients_count" field.
func RecipientsCountNotIn(vs ...int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNotIn(FieldRecipientsCount, vs...))
}

// RecipientsCountGT applies the GT predicate on the "recipients_count" field.
func RecipientsCountGT(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldGT(FieldRecipientsCount, v))
}

// RecipientsCountGTE applies the GTE predicate on the "recipients_count" field.
func RecipientsCountGTE(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldGTE(FieldRecipientsCount, v))
}

// RecipientsCountLT applies the LT predicate on the "recipients_count" field.
func RecipientsCountLT(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldLT(FieldRecipientsCount, v))
}

// RecipientsCountLTE applies the LTE predicate on the "recipients_count" field.
func RecipientsCountLTE(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldLTE(FieldRecipientsCount, v))
}

// SentCountEQ applies the EQ predicate on the "sent_count" field.
func SentCountEQ(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEQ(FieldSentCount, v))
}

// SentCountNEQ applies the NEQ predicate on the "sent_count" field.
func SentCountNEQ(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNEQ(FieldSentCount, v))
}

// SentCountIn applies the In predicate on the "sent_count" field.
func SentCountIn(vs ...int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldIn(FieldSentCount, vs...))
}

// SentCountNotIn applies the NotIn predicate on the "sent_count" field.
func SentCountNotIn(vs ...int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNotIn(FieldSentCount, vs...))
}

// SentCountGT applies the GT predicate on the "sent_count" field.
func SentCountGT(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldGT(FieldSentCount, v))
}

// SentCountGTE applies the GTE predicate on the "sent_count" field.
func SentCountGTE(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldGTE(FieldSentCount, v))
}

// SentCountLT applies the LT predicate on the "sent_count" field.
func SentCountLT(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldLT(FieldSentCount, v))
}

// SentCountLTE applies the LTE predicate on the "sent_count" field.
func SentCountLTE(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldLTE(FieldSentCount, v))
}

// FailedCountEQ applies the EQ predicate on the "failed_count" field.
func FailedCountEQ(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEQ(FieldFailedCount, v))
}

// FailedCountNEQ applies the NEQ predicate on the "failed_count" field.
func FailedCountNEQ(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNEQ(FieldFailedCount, v))
}

// FailedCountIn applies the In predicate on the "failed_count" field.
func FailedCountIn(vs ...int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldIn(FieldFailedCount, vs...))
}

// FailedCountNotIn applies the NotIn predicate on the "failed_count" field.
func FailedCountNotIn(vs ...int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNotIn(FieldFailedCount, vs...))
}

// FailedCountGT applies the GT predicate on the "failed_count" field.
func FailedCountGT(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldGT(FieldFailedCount, v))
}

// FailedCountGTE applies the GTE predicate on the "failed_count" field.
func FailedCountGTE(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldGTE(FieldFailedCount, v))
}

// FailedCountLT applies the LT predicate on the "failed_count" field.
func FailedCountLT(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldLT(FieldFailedCount, v))
}

// FailedCountLTE applies the LTE predicate on the "failed_count" field.
func FailedCountLTE(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldLTE(FieldFailedCount, v))
}

// OpenedCountEQ applies the EQ predicate on the "opened_count" field.
func OpenedCountEQ(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEQ(FieldOpenedCount, v))
}

// OpenedCountNEQ applies the NEQ predicate on the "opened_count" field.
func OpenedCountNEQ(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNEQ(FieldOpenedCount, v))
}

// OpenedCountIn applies the In predicate on the "opened_count" field.
func OpenedCountIn(vs ...int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldIn(FieldOpenedCount, vs...))
}

// OpenedCountNotIn applies the NotIn predicate on the "opened_count" field.
func OpenedCountNotIn(vs ...int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNotIn(FieldOpenedCount, vs...))
}

// OpenedCountGT applies the GT predicate on the "opened_count" field.
func OpenedCountGT(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldGT(FieldOpenedCount, v))
}

// OpenedCountGTE applies the GTE predicate on the "opened_count" field.
func OpenedCountGTE(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldGTE(FieldOpenedCount, v))
}

// OpenedCountLT applies the LT predicate on the "opened_count" field.
func OpenedCountLT(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldLT(FieldOpenedCount, v))
}

// OpenedCountLTE applies the LTE predicate on the "opened_count" field.
func OpenedCountLTE(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldLTE(FieldOpenedCount, v))
}

// ClickedCountEQ applies the EQ predicate on the "clicked_count" field.
func ClickedCountEQ(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEQ(FieldClickedCount, v))
}

// ClickedCountNEQ applies the NEQ predicate on the "clicked_count" field.
func ClickedCountNEQ(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNEQ(FieldClickedCount, v))
}

// ClickedCountIn applies the In predicate on the "clicked_count" field.
func ClickedCountIn(vs ...int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldIn(FieldClickedCount, vs...))
}

// ClickedCountNotIn applies the NotIn predicate on the "clicked_count" field.
func ClickedCountNotIn(vs ...int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNotIn(FieldClickedCount, vs...))
}

// ClickedCountGT applies the GT predicate on the "clicked_count" field.
func ClickedCountGT(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldGT(FieldClickedCount, v))
}

// ClickedCountGTE applies the GTE predicate on the "clicked_count" field.
func ClickedCountGTE(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldGTE(FieldClickedCount, v))
}

// ClickedCountLT applies the LT predicate on the "clicked_count" field.
func ClickedCountLT(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldLT(FieldClickedCount, v))
}

// ClickedCountLTE applies the LTE predicate on the "clicked_count" field.
func ClickedCountLTE(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldLTE(FieldClickedCount, v))
}

// UnsubscribedCountEQ applies the EQ predicate on the "unsubscribed_count" field.
func UnsubscribedCountEQ(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEQ(FieldUnsubscribedCount, v))
}

// UnsubscribedCountNEQ applies the NEQ predicate on the "unsubscribed_count" field.
func UnsubscribedCountNEQ(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNEQ(FieldUnsubscribedCount, v))
}

// UnsubscribedCountIn applies the In predicate on the "unsubscribed_count" field.
func UnsubscribedCountIn(vs ...int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldIn(FieldUnsubscribedCount, vs...))
}

// UnsubscribedCountNotIn applies the NotIn predicate on the "unsubscribed_count" field.
func UnsubscribedCountNotIn(vs ...int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNotIn(FieldUnsubscribedCount, vs...))
}

// UnsubscribedCountGT applies the GT predicate on the "unsubscribed_count" field.
func UnsubscribedCountGT(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldGT(FieldUnsubscribedCount, v))
}

// UnsubscribedCountGTE applies the GTE predicate on the "unsubscribed_count" field.
func UnsubscribedCountGTE(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldGTE(FieldUnsubscribedCount, v))
}

// UnsubscribedCountLT applies the LT predicate on the "unsubscribed_count" field.
func UnsubscribedCountLT(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldLT(FieldUnsubscribedCount, v))
}

// UnsubscribedCountLTE applies the LTE predicate on the "unsubscribed_count" field.
func UnsubscribedCountLTE(v int) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldLTE(FieldUnsubscribedCount, v))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNotNull(FieldTags))
}

// SendgridBatchIDEQ applies the EQ predicate on the "sendgrid_batch_id" field.
func SendgridBatchIDEQ(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEQ(FieldSendgridBatchID, v))
}

// SendgridBatchIDNEQ applies the NEQ predicate on the "sendgrid_batch_id" field.
func SendgridBatchIDNEQ(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNEQ(FieldSendgridBatchID, v))
}

// SendgridBatchIDIn applies the In predicate on the "sendgrid_batch_id" field.
func SendgridBatchIDIn(vs ...string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldIn(FieldSendgridBatchID, vs...))
}

// SendgridBatchIDNotIn applies the NotIn predicate on the "sendgrid_batch_id" field.
func SendgridBatchIDNotIn(vs ...string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNotIn(FieldSendgridBatchID, vs...))
}

// SendgridBatchIDGT applies the GT predicate on the "sendgrid_batch_id" field.
func SendgridBatchIDGT(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldGT(FieldSendgridBatchID, v))
}

// SendgridBatchIDGTE applies the GTE predicate on the "sendgrid_batch_id" field.
func SendgridBatchIDGTE(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldGTE(FieldSendgridBatchID, v))
}

// SendgridBatchIDLT applies the LT predicate on the "sendgrid_batch_id" field.
func SendgridBatchIDLT(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldLT(FieldSendgridBatchID, v))
}

// SendgridBatchIDLTE applies the LTE predicate on the "sendgrid_batch_id" field.
func SendgridBatchIDLTE(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldLTE(FieldSendgridBatchID, v))
}

// SendgridBatchIDContains applies the Contains predicate on the "sendgrid_batch_id" field.
func SendgridBatchIDContains(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldContains(FieldSendgridBatchID, v))
}

// SendgridBatchIDHasPrefix applies the HasPrefix predicate on the "sendgrid_batch_id" field.
func SendgridBatchIDHasPrefix(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldHasPrefix(FieldSendgridBatchID, v))
}

// SendgridBatchIDHasSuffix applies the HasSuffix predicate on the "sendgrid_batch_id" field.
func SendgridBatchIDHasSuffix(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldHasSuffix(FieldSendgridBatchID, v))
}

// SendgridBatchIDIsNil applies the IsNil predicate on the "sendgrid_batch_id" field.
func SendgridBatchIDIsNil() predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldIsNull(FieldSendgridBatchID))
}

// SendgridBatchIDNotNil applies the NotNil predicate on the "sendgrid_batch_id" field.
func SendgridBatchIDNotNil() predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNotNull(FieldSendgridBatchID))
}

// SendgridBatchIDEqualFold applies the EqualFold predicate on the "sendgrid_batch_id" field.
func SendgridBatchIDEqualFold(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEqualFold(FieldSendgridBatchID, v))
}

// SendgridBatchIDContainsFold applies the ContainsFold predicate on the "sendgrid_batch_id" field.
func SendgridBatchIDContainsFold(v string) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldContainsFold(FieldSendgridBatchID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.EmailCampaign {
	return predicate.EmailCampaign(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.EmailCampaign {
	return predicate.EmailCampaign(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRecipients applies the HasEdge predicate on the "recipients" edge.
func HasRecipients() predicate.EmailCampaign {
	return predicate.EmailCampaign(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RecipientsTable, RecipientsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRecipientsWith applies the HasEdge predicate on the "recipients" edge with a given conditions (other predicates).
func HasRecipientsWith(preds ...predicate.EmailCampaignRecipient) predicate.EmailCampaign {
	return predicate.EmailCampaign(func(s *sql.Selector) {
		step := newRecipientsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EmailCampaign) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EmailCampaign) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EmailCampaign) predicate.EmailCampaign {
	return predicate.EmailCampaign(sql.NotPredicates(p))
}
