// Code generated by ent, DO NOT EDIT.

package leadassignment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/jordanlanch/industrydb/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldLTE(FieldID, id))
}

// LeadID applies equality check predicate on the "lead_id" field. It's identical to LeadIDEQ.
func LeadID(v int) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldEQ(FieldLeadID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldEQ(FieldUserID, v))
}

// AssignedByUserID applies equality check predicate on the "assigned_by_user_id" field. It's identical to AssignedByUserIDEQ.
func AssignedByUserID(v int) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldEQ(FieldAssignedByUserID, v))
}

// AssignmentReason applies equality check predicate on the "assignment_reason" field. It's identical to AssignmentReasonEQ.
func AssignmentReason(v string) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldEQ(FieldAssignmentReason, v))
}

// AssignedAt applies equality check predicate on the "assigned_at" field. It's identical to AssignedAtEQ.
func AssignedAt(v time.Time) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldEQ(FieldAssignedAt, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldEQ(FieldIsActive, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldEQ(FieldCreatedAt, v))
}

// LeadIDEQ applies the EQ predicate on the "lead_id" field.
func LeadIDEQ(v int) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldEQ(FieldLeadID, v))
}

// LeadIDNEQ applies the NEQ predicate on the "lead_id" field.
func LeadIDNEQ(v int) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldNEQ(FieldLeadID, v))
}

// LeadIDIn applies the In predicate on the "lead_id" field.
func LeadIDIn(vs ...int) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldIn(FieldLeadID, vs...))
}

// LeadIDNotIn applies the NotIn predicate on the "lead_id" field.
func LeadIDNotIn(vs ...int) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldNotIn(FieldLeadID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldNotIn(FieldUserID, vs...))
}

// AssignedByUserIDEQ applies the EQ predicate on the "assigned_by_user_id" field.
func AssignedByUserIDEQ(v int) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldEQ(FieldAssignedByUserID, v))
}

// AssignedByUserIDNEQ applies the NEQ predicate on the "assigned_by_user_id" field.
func AssignedByUserIDNEQ(v int) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldNEQ(FieldAssignedByUserID, v))
}

// AssignedByUserIDIn applies the In predicate on the "assigned_by_user_id" field.
func AssignedByUserIDIn(vs ...int) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldIn(FieldAssignedByUserID, vs...))
}

// AssignedByUserIDNotIn applies the NotIn predicate on the "assigned_by_user_id" field.
func AssignedByUserIDNotIn(vs ...int) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldNotIn(FieldAssignedByUserID, vs...))
}

// AssignedByUserIDIsNil applies the IsNil predicate on the "assigned_by_user_id" field.
func AssignedByUserIDIsNil() predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldIsNull(FieldAssignedByUserID))
}

// AssignedByUserIDNotNil applies the NotNil predicate on the "assigned_by_user_id" field.
func AssignedByUserIDNotNil() predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldNotNull(FieldAssignedByUserID))
}

// AssignmentTypeEQ applies the EQ predicate on the "assignment_type" field.
func AssignmentTypeEQ(v AssignmentType) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldEQ(FieldAssignmentType, v))
}

// AssignmentTypeNEQ applies the NEQ predicate on the "assignment_type" field.
func AssignmentTypeNEQ(v AssignmentType) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldNEQ(FieldAssignmentType, v))
}

// AssignmentTypeIn applies the In predicate on the "assignment_type" field.
func AssignmentTypeIn(vs ...AssignmentType) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldIn(FieldAssignmentType, vs...))
}

// AssignmentTypeNotIn applies the NotIn predicate on the "assignment_type" field.
func AssignmentTypeNotIn(vs ...AssignmentType) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldNotIn(FieldAssignmentType, vs...))
}

// AssignmentReasonEQ applies the EQ predicate on the "assignment_reason" field.
func AssignmentReasonEQ(v string) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldEQ(FieldAssignmentReason, v))
}

// AssignmentReasonNEQ applies the NEQ predicate on the "assignment_reason" field.
func AssignmentReasonNEQ(v string) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldNEQ(FieldAssignmentReason, v))
}

// AssignmentReasonIn applies the In predicate on the "assignment_reason" field.
func AssignmentReasonIn(vs ...string) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldIn(FieldAssignmentReason, vs...))
}

// AssignmentReasonNotIn applies the NotIn predicate on the "assignment_reason" field.
func AssignmentReasonNotIn(vs ...string) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldNotIn(FieldAssignmentReason, vs...))
}

// AssignmentReasonGT applies the GT predicate on the "assignment_reason" field.
func AssignmentReasonGT(v string) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldGT(FieldAssignmentReason, v))
}

// AssignmentReasonGTE applies the GTE predicate on the "assignment_reason" field.
func AssignmentReasonGTE(v string) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldGTE(FieldAssignmentReason, v))
}

// AssignmentReasonLT applies the LT predicate on the "assignment_reason" field.
func AssignmentReasonLT(v string) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldLT(FieldAssignmentReason, v))
}

// AssignmentReasonLTE applies the LTE predicate on the "assignment_reason" field.
func AssignmentReasonLTE(v string) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldLTE(FieldAssignmentReason, v))
}

// AssignmentReasonContains applies the Contains predicate on the "assignment_reason" field.
func AssignmentReasonContains(v string) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldContains(FieldAssignmentReason, v))
}

// AssignmentReasonHasPrefix applies the HasPrefix predicate on the "assignment_reason" field.
func AssignmentReasonHasPrefix(v string) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldHasPrefix(FieldAssignmentReason, v))
}

// AssignmentReasonHasSuffix applies the HasSuffix predicate on the "assignment_reason" field.
func AssignmentReasonHasSuffix(v string) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldHasSuffix(FieldAssignmentReason, v))
}

// AssignmentReasonIsNil applies the IsNil predicate on the "assignment_reason" field.
func AssignmentReasonIsNil() predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldIsNull(FieldAssignmentReason))
}

// AssignmentReasonNotNil applies the NotNil predicate on the "assignment_reason" field.
func AssignmentReasonNotNil() predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldNotNull(FieldAssignmentReason))
}

// AssignmentReasonEqualFold applies the EqualFold predicate on the "assignment_reason" field.
func AssignmentReasonEqualFold(v string) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldEqualFold(FieldAssignmentReason, v))
}

// AssignmentReasonContainsFold applies the ContainsFold predicate on the "assignment_reason" field.
func AssignmentReasonContainsFold(v string) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldContainsFold(FieldAssignmentReason, v))
}

// AssignedAtEQ applies the EQ predicate on the "assigned_at" field.
func AssignedAtEQ(v time.Time) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldEQ(FieldAssignedAt, v))
}

// AssignedAtNEQ applies the NEQ predicate on the "assigned_at" field.
func AssignedAtNEQ(v time.Time) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldNEQ(FieldAssignedAt, v))
}

// AssignedAtIn applies the In predicate on the "assigned_at" field.
func AssignedAtIn(vs ...time.Time) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldIn(FieldAssignedAt, vs...))
}

// AssignedAtNotIn applies the NotIn predicate on the "assigned_at" field.
func AssignedAtNotIn(vs ...time.Time) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldNotIn(FieldAssignedAt, vs...))
}

// AssignedAtGT applies the GT predicate on the "assigned_at" field.
func AssignedAtGT(v time.Time) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldGT(FieldAssignedAt, v))
}

// AssignedAtGTE applies the GTE predicate on the "assigned_at" field.
func AssignedAtGTE(v time.Time) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldGTE(FieldAssignedAt, v))
}

// AssignedAtLT applies the LT predicate on the "assigned_at" field.
func AssignedAtLT(v time.Time) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldLT(FieldAssignedAt, v))
}

// AssignedAtLTE applies the LTE predicate on the "assigned_at" field.
func AssignedAtLTE(v time.Time) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldLTE(FieldAssignedAt, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldNEQ(FieldIsActive, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.FieldLTE(FieldCreatedAt, v))
}

// HasLead applies the HasEdge predicate on the "lead" edge.
func HasLead() predicate.LeadAssignment {
	return predicate.LeadAssignment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, LeadTable, LeadColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLeadWith applies the HasEdge predicate on the "lead" edge with a given conditions (other predicates).
func HasLeadWith(preds ...predicate.Lead) predicate.LeadAssignment {
	return predicate.LeadAssignment(func(s *sql.Selector) {
		step := newLeadStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.LeadAssignment {
	return predicate.LeadAssignment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.LeadAssignment {
	return predicate.LeadAssignment(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAssignedBy applies the HasEdge predicate on the "assigned_by" edge.
func HasAssignedBy() predicate.LeadAssignment {
	return predicate.LeadAssignment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AssignedByTable, AssignedByColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAssignedByWith applies the HasEdge predicate on the "assigned_by" edge with a given conditions (other predicates).
func HasAssignedByWith(preds ...predicate.User) predicate.LeadAssignment {
	return predicate.LeadAssignment(func(s *sql.Selector) {
		step := newAssignedByStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LeadAssignment) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LeadAssignment) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LeadAssignment) predicate.LeadAssignment {
	return predicate.LeadAssignment(sql.NotPredicates(p))
}
