// Code generated by ent, DO NOT EDIT.

package emailcampaignrecipient

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/jordanlanch/industrydb/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldLTE(FieldID, id))
}

// CampaignID applies equality check predicate on the "campaign_id" field. It's identical to CampaignIDEQ.
func CampaignID(v int) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldEQ(FieldCampaignID, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldEQ(FieldEmail, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldEQ(FieldName, v))
}

// SentAt applies equality check predicate on the "sent_at" field. It's identical to SentAtEQ.
func SentAt(v time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldEQ(FieldSentAt, v))
}

// OpenedAt applies equality check predicate on the "opened_at" field. It's identical to OpenedAtEQ.
func OpenedAt(v time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldEQ(FieldOpenedAt, v))
}

// ClickedAt applies equality check predicate on the "clicked_at" field. It's identical to ClickedAtEQ.
func ClickedAt(v time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldEQ(FieldClickedAt, v))
}

// UnsubscribedAt applies equality check predicate on the "unsubscribed_at" field. It's identical to UnsubscribedAtEQ.
func UnsubscribedAt(v time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldEQ(FieldUnsubscribedAt, v))
}

// FailureReason applies equality check predicate on the "failure_reason" field. It's identical to FailureReasonEQ.
func FailureReason(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldEQ(FieldFailureReason, v))
}

// SendgridMessageID applies equality check predicate on the "sendgrid_message_id" field. It's identical to SendgridMessageIDEQ.
func SendgridMessageID(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldEQ(FieldSendgridMessageID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldEQ(FieldUpdatedAt, v))
}

// CampaignIDEQ applies the EQ predicate on the "campaign_id" field.
func CampaignIDEQ(v int) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldEQ(FieldCampaignID, v))
}

// CampaignIDNEQ applies the NEQ predicate on the "campaign_id" field.
func CampaignIDNEQ(v int) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldNEQ(FieldCampaignID, v))
}

// CampaignIDIn applies the In predicate on the "campaign_id" field.
func CampaignIDIn(vs ...int) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldIn(FieldCampaignID, vs...))
}

// CampaignIDNotIn applies the NotIn predicate on the "campaign_id" field.
func CampaignIDNotIn(vs ...int) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldNotIn(FieldCampaignID, vs...))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldContainsFold(FieldEmail, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldHasSuffix(FieldName, v))
}

// NameIsNil applies the IsNil predicate on the "name" field.
func NameIsNil() predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldIsNull(FieldName))
}

// NameNotNil applies the NotNil predicate on the "name" field.
func NameNotNil() predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldNotNull(FieldName))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldContainsFold(FieldName, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldNotIn(FieldStatus, vs...))
}

// SentAtEQ applies the EQ predicate on the "sent_at" field.
func SentAtEQ(v time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldEQ(FieldSentAt, v))
}

// SentAtNEQ applies the NEQ predicate on the "sent_at" field.
func SentAtNEQ(v time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldNEQ(FieldSentAt, v))
}

// SentAtIn applies the In predicate on the "sent_at" field.
func SentAtIn(vs ...time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldIn(FieldSentAt, vs...))
}

// SentAtNotIn applies the NotIn predicate on the "sent_at" field.
func SentAtNotIn(vs ...time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldNotIn(FieldSentAt, vs...))
}

// SentAtGT applies the GT predicate on the "sent_at" field.
func SentAtGT(v time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldGT(FieldSentAt, v))
}

// SentAtGTE applies the GTE predicate on the "sent_at" field.
func SentAtGTE(v time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldGTE(FieldSentAt, v))
}

// SentAtLT applies the LT predicate on the "sent_at" field.
func SentAtLT(v time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldLT(FieldSentAt, v))
}

// SentAtLTE applies the LTE predicate on the "sent_at" field.
func SentAtLTE(v time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldLTE(FieldSentAt, v))
}

// SentAtIsNil applies the IsNil predicate on the "sent_at" field.
func SentAtIsNil() predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldIsNull(FieldSentAt))
}

// SentAtNotNil applies the NotNil predicate on the "sent_at" field.
func SentAtNotNil() predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldNotNull(FieldSentAt))
}

// OpenedAtEQ applies the EQ predicate on the "opened_at" field.
func OpenedAtEQ(v time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldEQ(FieldOpenedAt, v))
}

// OpenedAtNEQ applies the NEQ predicate on the "opened_at" field.
func OpenedAtNEQ(v time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldNEQ(FieldOpenedAt, v))
}

// OpenedAtIn applies the In predicate on the "opened_at" field.
func OpenedAtIn(vs ...time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldIn(FieldOpenedAt, vs...))
}

// OpenedAtNotIn applies the NotIn predicate on the "opened_at" field.
func OpenedAtNotIn(vs ...time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldNotIn(FieldOpenedAt, vs...))
}

// OpenedAtGT applies the GT predicate on the "opened_at" field.
func OpenedAtGT(v time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldGT(FieldOpenedAt, v))
}

// OpenedAtGTE applies the GTE predicate on the "opened_at" field.
func OpenedAtGTE(v time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldGTE(FieldOpenedAt, v))
}

// OpenedAtLT applies the LT predicate on the "opened_at" field.
func OpenedAtLT(v time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldLT(FieldOpenedAt, v))
}

// OpenedAtLTE applies the LTE predicate on the "opened_at" field.
func OpenedAtLTE(v time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldLTE(FieldOpenedAt, v))
}

// OpenedAtIsNil applies the IsNil predicate on the "opened_at" field.
func OpenedAtIsNil() predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldIsNull(FieldOpenedAt))
}

// OpenedAtNotNil applies the NotNil predicate on the "opened_at" field.
func OpenedAtNotNil() predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldNotNull(FieldOpenedAt))
}

// ClickedAtEQ applies the EQ predicate on the "clicked_at" field.
func ClickedAtEQ(v time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldEQ(FieldClickedAt, v))
}

// ClickedAtNEQ applies the NEQ predicate on the "clicked_at" field.
func ClickedAtNEQ(v time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldNEQ(FieldClickedAt, v))
}

// ClickedAtIn applies the In predicate on the "clicked_at" field.
func ClickedAtIn(vs ...time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldIn(FieldClickedAt, vs...))
}

// ClickedAtNotIn applies the NotIn predicate on the "clicked_at" field.
func ClickedAtNotIn(vs ...time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldNotIn(FieldClickedAt, vs...))
}

// ClickedAtGT applies the GT predicate on the "clicked_at" field.
func ClickedAtGT(v time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldGT(FieldClickedAt, v))
}

// ClickedAtGTE applies the GTE predicate on the "clicked_at" field.
func ClickedAtGTE(v time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldGTE(FieldClickedAt, v))
}

// ClickedAtLT applies the LT predicate on the "clicked_at" field.
func ClickedAtLT(v time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldLT(FieldClickedAt, v))
}

// ClickedAtLTE applies the LTE predicate on the "clicked_at" field.
func ClickedAtLTE(v time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldLTE(FieldClickedAt, v))
}

// ClickedAtIsNil applies the IsNil predicate on the "clicked_at" field.
func ClickedAtIsNil() predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldIsNull(FieldClickedAt))
}

// ClickedAtNotNil applies the NotNil predicate on the "clicked_at" field.
func ClickedAtNotNil() predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldNotNull(FieldClickedAt))
}

// UnsubscribedAtEQ applies the EQ predicate on the "unsubscribed_at" field.
func UnsubscribedAtEQ(v time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldEQ(FieldUnsubscribedAt, v))
}

// UnsubscribedAtNEQ applies the NEQ predicate on the "unsubscribed_at" field.
func UnsubscribedAtNEQ(v time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldNEQ(FieldUnsubscribedAt, v))
}

// UnsubscribedAtIn applies the In predicate on the "unsubscribed_at" field.
func UnsubscribedAtIn(vs ...time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldIn(FieldUnsubscribedAt, vs...))
}

// UnsubscribedAtNotIn applies the NotIn predicate on the "unsubscribed_at" field.
func UnsubscribedAtNotIn(vs ...time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldNotIn(FieldUnsubscribedAt, vs...))
}

// UnsubscribedAtGT applies the GT predicate on the "unsubscribed_at" field.
func UnsubscribedAtGT(v time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldGT(FieldUnsubscribedAt, v))
}

// UnsubscribedAtGTE applies the GTE predicate on the "unsubscribed_at" field.
func UnsubscribedAtGTE(v time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldGTE(FieldUnsubscribedAt, v))
}

// UnsubscribedAtLT applies the LT predicate on the "unsubscribed_at" field.
func UnsubscribedAtLT(v time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldLT(FieldUnsubscribedAt, v))
}

// UnsubscribedAtLTE applies the LTE predicate on the "unsubscribed_at" field.
func UnsubscribedAtLTE(v time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldLTE(FieldUnsubscribedAt, v))
}

// UnsubscribedAtIsNil applies the IsNil predicate on the "unsubscribed_at" field.
func UnsubscribedAtIsNil() predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldIsNull(FieldUnsubscribedAt))
}

// UnsubscribedAtNotNil applies the NotNil predicate on the "unsubscribed_at" field.
func UnsubscribedAtNotNil() predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldNotNull(FieldUnsubscribedAt))
}

// FailureReasonEQ applies the EQ predicate on the "failure_reason" field.
func FailureReasonEQ(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldEQ(FieldFailureReason, v))
}

// FailureReasonNEQ applies the NEQ predicate on the "failure_reason" field.
func FailureReasonNEQ(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldNEQ(FieldFailureReason, v))
}

// FailureReasonIn applies the In predicate on the "failure_reason" field.
func FailureReasonIn(vs ...string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldIn(FieldFailureReason, vs...))
}

// FailureReasonNotIn applies the NotIn predicate on the "failure_reason" field.
func FailureReasonNotIn(vs ...string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldNotIn(FieldFailureReason, vs...))
}

// FailureReasonGT applies the GT predicate on the "failure_reason" field.
func FailureReasonGT(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldGT(FieldFailureReason, v))
}

// FailureReasonGTE applies the GTE predicate on the "failure_reason" field.
func FailureReasonGTE(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldGTE(FieldFailureReason, v))
}

// FailureReasonLT applies the LT predicate on the "failure_reason" field.
func FailureReasonLT(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldLT(FieldFailureReason, v))
}

// FailureReasonLTE applies the LTE predicate on the "failure_reason" field.
func FailureReasonLTE(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldLTE(FieldFailureReason, v))
}

// FailureReasonContains applies the Contains predicate on the "failure_reason" field.
func FailureReasonContains(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldContains(FieldFailureReason, v))
}

// FailureReasonHasPrefix applies the HasPrefix predicate on the "failure_reason" field.
func FailureReasonHasPrefix(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldHasPrefix(FieldFailureReason, v))
}

// FailureReasonHasSuffix applies the HasSuffix predicate on the "failure_reason" field.
func FailureReasonHasSuffix(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldHasSuffix(FieldFailureReason, v))
}

// FailureReasonIsNil applies the IsNil predicate on the "failure_reason" field.
func FailureReasonIsNil() predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldIsNull(FieldFailureReason))
}

// FailureReasonNotNil applies the NotNil predicate on the "failure_reason" field.
func FailureReasonNotNil() predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldNotNull(FieldFailureReason))
}

// FailureReasonEqualFold applies the EqualFold predicate on the "failure_reason" field.
func FailureReasonEqualFold(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldEqualFold(FieldFailureReason, v))
}

// FailureReasonContainsFold applies the ContainsFold predicate on the "failure_reason" field.
func FailureReasonContainsFold(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldContainsFold(FieldFailureReason, v))
}

// SendgridMessageIDEQ applies the EQ predicate on the "sendgrid_message_id" field.
func SendgridMessageIDEQ(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldEQ(FieldSendgridMessageID, v))
}

// SendgridMessageIDNEQ applies the NEQ predicate on the "sendgrid_message_id" field.
func SendgridMessageIDNEQ(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldNEQ(FieldSendgridMessageID, v))
}

// SendgridMessageIDIn applies the In predicate on the "sendgrid_message_id" field.
func SendgridMessageIDIn(vs ...string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldIn(FieldSendgridMessageID, vs...))
}

// SendgridMessageIDNotIn applies the NotIn predicate on the "sendgrid_message_id" field.
func SendgridMessageIDNotIn(vs ...string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldNotIn(FieldSendgridMessageID, vs...))
}

// SendgridMessageIDGT applies the GT predicate on the "sendgrid_message_id" field.
func SendgridMessageIDGT(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldGT(FieldSendgridMessageID, v))
}

// SendgridMessageIDGTE applies the GTE predicate on the "sendgrid_message_id" field.
func SendgridMessageIDGTE(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldGTE(FieldSendgridMessageID, v))
}

// SendgridMessageIDLT applies the LT predicate on the "sendgrid_message_id" field.
func SendgridMessageIDLT(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldLT(FieldSendgridMessageID, v))
}

// SendgridMessageIDLTE applies the LTE predicate on the "sendgrid_message_id" field.
func SendgridMessageIDLTE(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldLTE(FieldSendgridMessageID, v))
}

// SendgridMessageIDContains applies the Contains predicate on the "sendgrid_message_id" field.
func SendgridMessageIDContains(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldContains(FieldSendgridMessageID, v))
}

// SendgridMessageIDHasPrefix applies the HasPrefix predicate on the "sendgrid_message_id" field.
func SendgridMessageIDHasPrefix(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldHasPrefix(FieldSendgridMessageID, v))
}

// SendgridMessageIDHasSuffix applies the HasSuffix predicate on the "sendgrid_message_id" field.
func SendgridMessageIDHasSuffix(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldHasSuffix(FieldSendgridMessageID, v))
}

// SendgridMessageIDIsNil applies the IsNil predicate on the "sendgrid_message_id" field.
func SendgridMessageIDIsNil() predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldIsNull(FieldSendgridMessageID))
}

// SendgridMessageIDNotNil applies the NotNil predicate on the "sendgrid_message_id" field.
func SendgridMessageIDNotNil() predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldNotNull(FieldSendgridMessageID))
}

// SendgridMessageIDEqualFold applies the EqualFold predicate on the "sendgrid_message_id" field.
func SendgridMessageIDEqualFold(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldEqualFold(FieldSendgridMessageID, v))
}

// SendgridMessageIDContainsFold applies the ContainsFold predicate on the "sendgrid_message_id" field.
func SendgridMessageIDContainsFold(v string) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldContainsFold(FieldSendgridMessageID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasCampaign applies the HasEdge predicate on the "campaign" edge.
func HasCampaign() predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CampaignTable, CampaignColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCampaignWith applies the HasEdge predicate on the "campaign" edge with a given conditions (other predicates).
func HasCampaignWith(preds ...predicate.EmailCampaign) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(func(s *sql.Selector) {
		step := newCampaignStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EmailCampaignRecipient) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EmailCampaignRecipient) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EmailCampaignRecipient) predicate.EmailCampaignRecipient {
	return predicate.EmailCampaignRecipient(sql.NotPredicates(p))
}
