// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jordanlanch/industrydb/ent/affiliate"
	"github.com/jordanlanch/industrydb/ent/affiliateclick"
	"github.com/jordanlanch/industrydb/ent/affiliateconversion"
	"github.com/jordanlanch/industrydb/ent/predicate"
	"github.com/jordanlanch/industrydb/ent/user"
)

// AffiliateQuery is the builder for querying Affiliate entities.
type AffiliateQuery struct {
	config
	ctx             *QueryContext
	order           []affiliate.OrderOption
	inters          []Interceptor
	predicates      []predicate.Affiliate
	withUser        *UserQuery
	withClicks      *AffiliateClickQuery
	withConversions *AffiliateConversionQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AffiliateQuery builder.
func (_q *AffiliateQuery) Where(ps ...predicate.Affiliate) *AffiliateQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *AffiliateQuery) Limit(limit int) *AffiliateQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *AffiliateQuery) Offset(offset int) *AffiliateQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *AffiliateQuery) Unique(unique bool) *AffiliateQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *AffiliateQuery) Order(o ...affiliate.OrderOption) *AffiliateQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryUser chains the current query on the "user" edge.
func (_q *AffiliateQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(affiliate.Table, affiliate.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, affiliate.UserTable, affiliate.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryClicks chains the current query on the "clicks" edge.
func (_q *AffiliateQuery) QueryClicks() *AffiliateClickQuery {
	query := (&AffiliateClickClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(affiliate.Table, affiliate.FieldID, selector),
			sqlgraph.To(affiliateclick.Table, affiliateclick.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, affiliate.ClicksTable, affiliate.ClicksColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryConversions chains the current query on the "conversions" edge.
func (_q *AffiliateQuery) QueryConversions() *AffiliateConversionQuery {
	query := (&AffiliateConversionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(affiliate.Table, affiliate.FieldID, selector),
			sqlgraph.To(affiliateconversion.Table, affiliateconversion.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, affiliate.ConversionsTable, affiliate.ConversionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Affiliate entity from the query.
// Returns a *NotFoundError when no Affiliate was found.
func (_q *AffiliateQuery) First(ctx context.Context) (*Affiliate, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{affiliate.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *AffiliateQuery) FirstX(ctx context.Context) *Affiliate {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Affiliate ID from the query.
// Returns a *NotFoundError when no Affiliate ID was found.
func (_q *AffiliateQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{affiliate.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *AffiliateQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Affiliate entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Affiliate entity is found.
// Returns a *NotFoundError when no Affiliate entities are found.
func (_q *AffiliateQuery) Only(ctx context.Context) (*Affiliate, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{affiliate.Label}
	default:
		return nil, &NotSingularError{affiliate.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *AffiliateQuery) OnlyX(ctx context.Context) *Affiliate {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Affiliate ID in the query.
// Returns a *NotSingularError when more than one Affiliate ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *AffiliateQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{affiliate.Label}
	default:
		err = &NotSingularError{affiliate.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *AffiliateQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Affiliates.
func (_q *AffiliateQuery) All(ctx context.Context) ([]*Affiliate, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Affiliate, *AffiliateQuery]()
	return withInterceptors[[]*Affiliate](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *AffiliateQuery) AllX(ctx context.Context) []*Affiliate {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Affiliate IDs.
func (_q *AffiliateQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(affiliate.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *AffiliateQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *AffiliateQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*AffiliateQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *AffiliateQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *AffiliateQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *AffiliateQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AffiliateQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *AffiliateQuery) Clone() *AffiliateQuery {
	if _q == nil {
		return nil
	}
	return &AffiliateQuery{
		config:          _q.config,
		ctx:             _q.ctx.Clone(),
		order:           append([]affiliate.OrderOption{}, _q.order...),
		inters:          append([]Interceptor{}, _q.inters...),
		predicates:      append([]predicate.Affiliate{}, _q.predicates...),
		withUser:        _q.withUser.Clone(),
		withClicks:      _q.withClicks.Clone(),
		withConversions: _q.withConversions.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AffiliateQuery) WithUser(opts ...func(*UserQuery)) *AffiliateQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// WithClicks tells the query-builder to eager-load the nodes that are connected to
// the "clicks" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AffiliateQuery) WithClicks(opts ...func(*AffiliateClickQuery)) *AffiliateQuery {
	query := (&AffiliateClickClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withClicks = query
	return _q
}

// WithConversions tells the query-builder to eager-load the nodes that are connected to
// the "conversions" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AffiliateQuery) WithConversions(opts ...func(*AffiliateConversionQuery)) *AffiliateQuery {
	query := (&AffiliateConversionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withConversions = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID int `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Affiliate.Query().
//		GroupBy(affiliate.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *AffiliateQuery) GroupBy(field string, fields ...string) *AffiliateGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AffiliateGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = affiliate.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID int `json:"user_id,omitempty"`
//	}
//
//	client.Affiliate.Query().
//		Select(affiliate.FieldUserID).
//		Scan(ctx, &v)
func (_q *AffiliateQuery) Select(fields ...string) *AffiliateSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &AffiliateSelect{AffiliateQuery: _q}
	sbuild.label = affiliate.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AffiliateSelect configured with the given aggregations.
func (_q *AffiliateQuery) Aggregate(fns ...AggregateFunc) *AffiliateSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *AffiliateQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !affiliate.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *AffiliateQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Affiliate, error) {
	var (
		nodes       = []*Affiliate{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withUser != nil,
			_q.withClicks != nil,
			_q.withConversions != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Affiliate).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Affiliate{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *Affiliate, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withClicks; query != nil {
		if err := _q.loadClicks(ctx, query, nodes,
			func(n *Affiliate) { n.Edges.Clicks = []*AffiliateClick{} },
			func(n *Affiliate, e *AffiliateClick) { n.Edges.Clicks = append(n.Edges.Clicks, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withConversions; query != nil {
		if err := _q.loadConversions(ctx, query, nodes,
			func(n *Affiliate) { n.Edges.Conversions = []*AffiliateConversion{} },
			func(n *Affiliate, e *AffiliateConversion) { n.Edges.Conversions = append(n.Edges.Conversions, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *AffiliateQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*Affiliate, init func(*Affiliate), assign func(*Affiliate, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Affiliate)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *AffiliateQuery) loadClicks(ctx context.Context, query *AffiliateClickQuery, nodes []*Affiliate, init func(*Affiliate), assign func(*Affiliate, *AffiliateClick)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Affiliate)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(affiliateclick.FieldAffiliateID)
	}
	query.Where(predicate.AffiliateClick(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(affiliate.ClicksColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.AffiliateID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "affiliate_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *AffiliateQuery) loadConversions(ctx context.Context, query *AffiliateConversionQuery, nodes []*Affiliate, init func(*Affiliate), assign func(*Affiliate, *AffiliateConversion)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Affiliate)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(affiliateconversion.FieldAffiliateID)
	}
	query.Where(predicate.AffiliateConversion(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(affiliate.ConversionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.AffiliateID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "affiliate_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *AffiliateQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *AffiliateQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(affiliate.Table, affiliate.Columns, sqlgraph.NewFieldSpec(affiliate.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, affiliate.FieldID)
		for i := range fields {
			if fields[i] != affiliate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withUser != nil {
			_spec.Node.AddColumnOnce(affiliate.FieldUserID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *AffiliateQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(affiliate.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = affiliate.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AffiliateGroupBy is the group-by builder for Affiliate entities.
type AffiliateGroupBy struct {
	selector
	build *AffiliateQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *AffiliateGroupBy) Aggregate(fns ...AggregateFunc) *AffiliateGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *AffiliateGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AffiliateQuery, *AffiliateGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *AffiliateGroupBy) sqlScan(ctx context.Context, root *AffiliateQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AffiliateSelect is the builder for selecting fields of Affiliate entities.
type AffiliateSelect struct {
	*AffiliateQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *AffiliateSelect) Aggregate(fns ...AggregateFunc) *AffiliateSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *AffiliateSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AffiliateQuery, *AffiliateSelect](ctx, _s.AffiliateQuery, _s, _s.inters, v)
}

func (_s *AffiliateSelect) sqlScan(ctx context.Context, root *AffiliateQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
