// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/jordanlanch/industrydb/ent/lead"
	"github.com/jordanlanch/industrydb/ent/leadstatushistory"
	"github.com/jordanlanch/industrydb/ent/user"
)

// LeadStatusHistory is the model entity for the LeadStatusHistory schema.
type LeadStatusHistory struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ID of the lead whose status changed
	LeadID int `json:"lead_id,omitempty"`
	// ID of the user who changed the status
	UserID int `json:"user_id,omitempty"`
	// Previous status (null for initial status)
	OldStatus *leadstatushistory.OldStatus `json:"old_status,omitempty"`
	// New status after the change
	NewStatus leadstatushistory.NewStatus `json:"new_status,omitempty"`
	// Optional reason for status change (e.g., 'Client not interested')
	Reason string `json:"reason,omitempty"`
	// When the status change occurred
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LeadStatusHistoryQuery when eager-loading is set.
	Edges        LeadStatusHistoryEdges `json:"edges"`
	selectValues sql.SelectValues
}

// LeadStatusHistoryEdges holds the relations/edges for other nodes in the graph.
type LeadStatusHistoryEdges struct {
	// Lead holds the value of the lead edge.
	Lead *Lead `json:"lead,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// LeadOrErr returns the Lead value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LeadStatusHistoryEdges) LeadOrErr() (*Lead, error) {
	if e.Lead != nil {
		return e.Lead, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: lead.Label}
	}
	return nil, &NotLoadedError{edge: "lead"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LeadStatusHistoryEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LeadStatusHistory) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case leadstatushistory.FieldID, leadstatushistory.FieldLeadID, leadstatushistory.FieldUserID:
			values[i] = new(sql.NullInt64)
		case leadstatushistory.FieldOldStatus, leadstatushistory.FieldNewStatus, leadstatushistory.FieldReason:
			values[i] = new(sql.NullString)
		case leadstatushistory.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LeadStatusHistory fields.
func (_m *LeadStatusHistory) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case leadstatushistory.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case leadstatushistory.FieldLeadID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field lead_id", values[i])
			} else if value.Valid {
				_m.LeadID = int(value.Int64)
			}
		case leadstatushistory.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case leadstatushistory.FieldOldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field old_status", values[i])
			} else if value.Valid {
				_m.OldStatus = new(leadstatushistory.OldStatus)
				*_m.OldStatus = leadstatushistory.OldStatus(value.String)
			}
		case leadstatushistory.FieldNewStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field new_status", values[i])
			} else if value.Valid {
				_m.NewStatus = leadstatushistory.NewStatus(value.String)
			}
		case leadstatushistory.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = value.String
			}
		case leadstatushistory.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LeadStatusHistory.
// This includes values selected through modifiers, order, etc.
func (_m *LeadStatusHistory) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryLead queries the "lead" edge of the LeadStatusHistory entity.
func (_m *LeadStatusHistory) QueryLead() *LeadQuery {
	return NewLeadStatusHistoryClient(_m.config).QueryLead(_m)
}

// QueryUser queries the "user" edge of the LeadStatusHistory entity.
func (_m *LeadStatusHistory) QueryUser() *UserQuery {
	return NewLeadStatusHistoryClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this LeadStatusHistory.
// Note that you need to call LeadStatusHistory.Unwrap() before calling this method if this LeadStatusHistory
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LeadStatusHistory) Update() *LeadStatusHistoryUpdateOne {
	return NewLeadStatusHistoryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LeadStatusHistory entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LeadStatusHistory) Unwrap() *LeadStatusHistory {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: LeadStatusHistory is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LeadStatusHistory) String() string {
	var builder strings.Builder
	builder.WriteString("LeadStatusHistory(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("lead_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.LeadID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	if v := _m.OldStatus; v != nil {
		builder.WriteString("old_status=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("new_status=")
	builder.WriteString(fmt.Sprintf("%v", _m.NewStatus))
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(_m.Reason)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// LeadStatusHistories is a parsable slice of LeadStatusHistory.
type LeadStatusHistories []*LeadStatusHistory
