// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jordanlanch/industrydb/ent/marketreport"
	"github.com/jordanlanch/industrydb/ent/predicate"
	"github.com/jordanlanch/industrydb/ent/user"
)

// MarketReportUpdate is the builder for updating MarketReport entities.
type MarketReportUpdate struct {
	config
	hooks    []Hook
	mutation *MarketReportMutation
}

// Where appends a list predicates to the MarketReportUpdate builder.
func (_u *MarketReportUpdate) Where(ps ...predicate.MarketReport) *MarketReportUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *MarketReportUpdate) SetUserID(v int) *MarketReportUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *MarketReportUpdate) SetNillableUserID(v *int) *MarketReportUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *MarketReportUpdate) SetTitle(v string) *MarketReportUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *MarketReportUpdate) SetNillableTitle(v *string) *MarketReportUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetIndustry sets the "industry" field.
func (_u *MarketReportUpdate) SetIndustry(v string) *MarketReportUpdate {
	_u.mutation.SetIndustry(v)
	return _u
}

// SetNillableIndustry sets the "industry" field if the given value is not nil.
func (_u *MarketReportUpdate) SetNillableIndustry(v *string) *MarketReportUpdate {
	if v != nil {
		_u.SetIndustry(*v)
	}
	return _u
}

// SetCountry sets the "country" field.
func (_u *MarketReportUpdate) SetCountry(v string) *MarketReportUpdate {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *MarketReportUpdate) SetNillableCountry(v *string) *MarketReportUpdate {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// ClearCountry clears the value of the "country" field.
func (_u *MarketReportUpdate) ClearCountry() *MarketReportUpdate {
	_u.mutation.ClearCountry()
	return _u
}

// SetReportType sets the "report_type" field.
func (_u *MarketReportUpdate) SetReportType(v marketreport.ReportType) *MarketReportUpdate {
	_u.mutation.SetReportType(v)
	return _u
}

// SetNillableReportType sets the "report_type" field if the given value is not nil.
func (_u *MarketReportUpdate) SetNillableReportType(v *marketreport.ReportType) *MarketReportUpdate {
	if v != nil {
		_u.SetReportType(*v)
	}
	return _u
}

// SetData sets the "data" field.
func (_u *MarketReportUpdate) SetData(v map[string]interface{}) *MarketReportUpdate {
	_u.mutation.SetData(v)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *MarketReportUpdate) SetMetadata(v map[string]interface{}) *MarketReportUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *MarketReportUpdate) ClearMetadata() *MarketReportUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetPeriodStart sets the "period_start" field.
func (_u *MarketReportUpdate) SetPeriodStart(v time.Time) *MarketReportUpdate {
	_u.mutation.SetPeriodStart(v)
	return _u
}

// SetNillablePeriodStart sets the "period_start" field if the given value is not nil.
func (_u *MarketReportUpdate) SetNillablePeriodStart(v *time.Time) *MarketReportUpdate {
	if v != nil {
		_u.SetPeriodStart(*v)
	}
	return _u
}

// SetPeriodEnd sets the "period_end" field.
func (_u *MarketReportUpdate) SetPeriodEnd(v time.Time) *MarketReportUpdate {
	_u.mutation.SetPeriodEnd(v)
	return _u
}

// SetNillablePeriodEnd sets the "period_end" field if the given value is not nil.
func (_u *MarketReportUpdate) SetNillablePeriodEnd(v *time.Time) *MarketReportUpdate {
	if v != nil {
		_u.SetPeriodEnd(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *MarketReportUpdate) SetExpiresAt(v time.Time) *MarketReportUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *MarketReportUpdate) SetNillableExpiresAt(v *time.Time) *MarketReportUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *MarketReportUpdate) ClearExpiresAt() *MarketReportUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *MarketReportUpdate) SetUser(v *User) *MarketReportUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the MarketReportMutation object of the builder.
func (_u *MarketReportUpdate) Mutation() *MarketReportMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *MarketReportUpdate) ClearUser() *MarketReportUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MarketReportUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MarketReportUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MarketReportUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MarketReportUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MarketReportUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := marketreport.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "MarketReport.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Industry(); ok {
		if err := marketreport.IndustryValidator(v); err != nil {
			return &ValidationError{Name: "industry", err: fmt.Errorf(`ent: validator failed for field "MarketReport.industry": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Country(); ok {
		if err := marketreport.CountryValidator(v); err != nil {
			return &ValidationError{Name: "country", err: fmt.Errorf(`ent: validator failed for field "MarketReport.country": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReportType(); ok {
		if err := marketreport.ReportTypeValidator(v); err != nil {
			return &ValidationError{Name: "report_type", err: fmt.Errorf(`ent: validator failed for field "MarketReport.report_type": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MarketReport.user"`)
	}
	return nil
}

func (_u *MarketReportUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(marketreport.Table, marketreport.Columns, sqlgraph.NewFieldSpec(marketreport.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(marketreport.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Industry(); ok {
		_spec.SetField(marketreport.FieldIndustry, field.TypeString, value)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(marketreport.FieldCountry, field.TypeString, value)
	}
	if _u.mutation.CountryCleared() {
		_spec.ClearField(marketreport.FieldCountry, field.TypeString)
	}
	if value, ok := _u.mutation.ReportType(); ok {
		_spec.SetField(marketreport.FieldReportType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Data(); ok {
		_spec.SetField(marketreport.FieldData, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(marketreport.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(marketreport.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.PeriodStart(); ok {
		_spec.SetField(marketreport.FieldPeriodStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PeriodEnd(); ok {
		_spec.SetField(marketreport.FieldPeriodEnd, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(marketreport.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(marketreport.FieldExpiresAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   marketreport.UserTable,
			Columns: []string{marketreport.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   marketreport.UserTable,
			Columns: []string{marketreport.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{marketreport.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MarketReportUpdateOne is the builder for updating a single MarketReport entity.
type MarketReportUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MarketReportMutation
}

// SetUserID sets the "user_id" field.
func (_u *MarketReportUpdateOne) SetUserID(v int) *MarketReportUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *MarketReportUpdateOne) SetNillableUserID(v *int) *MarketReportUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *MarketReportUpdateOne) SetTitle(v string) *MarketReportUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *MarketReportUpdateOne) SetNillableTitle(v *string) *MarketReportUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetIndustry sets the "industry" field.
func (_u *MarketReportUpdateOne) SetIndustry(v string) *MarketReportUpdateOne {
	_u.mutation.SetIndustry(v)
	return _u
}

// SetNillableIndustry sets the "industry" field if the given value is not nil.
func (_u *MarketReportUpdateOne) SetNillableIndustry(v *string) *MarketReportUpdateOne {
	if v != nil {
		_u.SetIndustry(*v)
	}
	return _u
}

// SetCountry sets the "country" field.
func (_u *MarketReportUpdateOne) SetCountry(v string) *MarketReportUpdateOne {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *MarketReportUpdateOne) SetNillableCountry(v *string) *MarketReportUpdateOne {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// ClearCountry clears the value of the "country" field.
func (_u *MarketReportUpdateOne) ClearCountry() *MarketReportUpdateOne {
	_u.mutation.ClearCountry()
	return _u
}

// SetReportType sets the "report_type" field.
func (_u *MarketReportUpdateOne) SetReportType(v marketreport.ReportType) *MarketReportUpdateOne {
	_u.mutation.SetReportType(v)
	return _u
}

// SetNillableReportType sets the "report_type" field if the given value is not nil.
func (_u *MarketReportUpdateOne) SetNillableReportType(v *marketreport.ReportType) *MarketReportUpdateOne {
	if v != nil {
		_u.SetReportType(*v)
	}
	return _u
}

// SetData sets the "data" field.
func (_u *MarketReportUpdateOne) SetData(v map[string]interface{}) *MarketReportUpdateOne {
	_u.mutation.SetData(v)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *MarketReportUpdateOne) SetMetadata(v map[string]interface{}) *MarketReportUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *MarketReportUpdateOne) ClearMetadata() *MarketReportUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetPeriodStart sets the "period_start" field.
func (_u *MarketReportUpdateOne) SetPeriodStart(v time.Time) *MarketReportUpdateOne {
	_u.mutation.SetPeriodStart(v)
	return _u
}

// SetNillablePeriodStart sets the "period_start" field if the given value is not nil.
func (_u *MarketReportUpdateOne) SetNillablePeriodStart(v *time.Time) *MarketReportUpdateOne {
	if v != nil {
		_u.SetPeriodStart(*v)
	}
	return _u
}

// SetPeriodEnd sets the "period_end" field.
func (_u *MarketReportUpdateOne) SetPeriodEnd(v time.Time) *MarketReportUpdateOne {
	_u.mutation.SetPeriodEnd(v)
	return _u
}

// SetNillablePeriodEnd sets the "period_end" field if the given value is not nil.
func (_u *MarketReportUpdateOne) SetNillablePeriodEnd(v *time.Time) *MarketReportUpdateOne {
	if v != nil {
		_u.SetPeriodEnd(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *MarketReportUpdateOne) SetExpiresAt(v time.Time) *MarketReportUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *MarketReportUpdateOne) SetNillableExpiresAt(v *time.Time) *MarketReportUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *MarketReportUpdateOne) ClearExpiresAt() *MarketReportUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *MarketReportUpdateOne) SetUser(v *User) *MarketReportUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the MarketReportMutation object of the builder.
func (_u *MarketReportUpdateOne) Mutation() *MarketReportMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *MarketReportUpdateOne) ClearUser() *MarketReportUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the MarketReportUpdate builder.
func (_u *MarketReportUpdateOne) Where(ps ...predicate.MarketReport) *MarketReportUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MarketReportUpdateOne) Select(field string, fields ...string) *MarketReportUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MarketReport entity.
func (_u *MarketReportUpdateOne) Save(ctx context.Context) (*MarketReport, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MarketReportUpdateOne) SaveX(ctx context.Context) *MarketReport {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MarketReportUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MarketReportUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MarketReportUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := marketreport.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "MarketReport.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Industry(); ok {
		if err := marketreport.IndustryValidator(v); err != nil {
			return &ValidationError{Name: "industry", err: fmt.Errorf(`ent: validator failed for field "MarketReport.industry": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Country(); ok {
		if err := marketreport.CountryValidator(v); err != nil {
			return &ValidationError{Name: "country", err: fmt.Errorf(`ent: validator failed for field "MarketReport.country": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReportType(); ok {
		if err := marketreport.ReportTypeValidator(v); err != nil {
			return &ValidationError{Name: "report_type", err: fmt.Errorf(`ent: validator failed for field "MarketReport.report_type": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MarketReport.user"`)
	}
	return nil
}

func (_u *MarketReportUpdateOne) sqlSave(ctx context.Context) (_node *MarketReport, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(marketreport.Table, marketreport.Columns, sqlgraph.NewFieldSpec(marketreport.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MarketReport.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, marketreport.FieldID)
		for _, f := range fields {
			if !marketreport.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != marketreport.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(marketreport.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Industry(); ok {
		_spec.SetField(marketreport.FieldIndustry, field.TypeString, value)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(marketreport.FieldCountry, field.TypeString, value)
	}
	if _u.mutation.CountryCleared() {
		_spec.ClearField(marketreport.FieldCountry, field.TypeString)
	}
	if value, ok := _u.mutation.ReportType(); ok {
		_spec.SetField(marketreport.FieldReportType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Data(); ok {
		_spec.SetField(marketreport.FieldData, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(marketreport.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(marketreport.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.PeriodStart(); ok {
		_spec.SetField(marketreport.FieldPeriodStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PeriodEnd(); ok {
		_spec.SetField(marketreport.FieldPeriodEnd, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(marketreport.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(marketreport.FieldExpiresAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   marketreport.UserTable,
			Columns: []string{marketreport.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   marketreport.UserTable,
			Columns: []string{marketreport.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &MarketReport{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{marketreport.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
