// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jordanlanch/industrydb/ent/export"
	"github.com/jordanlanch/industrydb/ent/organization"
	"github.com/jordanlanch/industrydb/ent/organizationmember"
	"github.com/jordanlanch/industrydb/ent/user"
)

// OrganizationCreate is the builder for creating a Organization entity.
type OrganizationCreate struct {
	config
	mutation *OrganizationMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *OrganizationCreate) SetName(v string) *OrganizationCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetSlug sets the "slug" field.
func (_c *OrganizationCreate) SetSlug(v string) *OrganizationCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetOwnerID sets the "owner_id" field.
func (_c *OrganizationCreate) SetOwnerID(v int) *OrganizationCreate {
	_c.mutation.SetOwnerID(v)
	return _c
}

// SetSubscriptionTier sets the "subscription_tier" field.
func (_c *OrganizationCreate) SetSubscriptionTier(v organization.SubscriptionTier) *OrganizationCreate {
	_c.mutation.SetSubscriptionTier(v)
	return _c
}

// SetNillableSubscriptionTier sets the "subscription_tier" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableSubscriptionTier(v *organization.SubscriptionTier) *OrganizationCreate {
	if v != nil {
		_c.SetSubscriptionTier(*v)
	}
	return _c
}

// SetUsageLimit sets the "usage_limit" field.
func (_c *OrganizationCreate) SetUsageLimit(v int) *OrganizationCreate {
	_c.mutation.SetUsageLimit(v)
	return _c
}

// SetNillableUsageLimit sets the "usage_limit" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableUsageLimit(v *int) *OrganizationCreate {
	if v != nil {
		_c.SetUsageLimit(*v)
	}
	return _c
}

// SetUsageCount sets the "usage_count" field.
func (_c *OrganizationCreate) SetUsageCount(v int) *OrganizationCreate {
	_c.mutation.SetUsageCount(v)
	return _c
}

// SetNillableUsageCount sets the "usage_count" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableUsageCount(v *int) *OrganizationCreate {
	if v != nil {
		_c.SetUsageCount(*v)
	}
	return _c
}

// SetLastResetAt sets the "last_reset_at" field.
func (_c *OrganizationCreate) SetLastResetAt(v time.Time) *OrganizationCreate {
	_c.mutation.SetLastResetAt(v)
	return _c
}

// SetNillableLastResetAt sets the "last_reset_at" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableLastResetAt(v *time.Time) *OrganizationCreate {
	if v != nil {
		_c.SetLastResetAt(*v)
	}
	return _c
}

// SetStripeCustomerID sets the "stripe_customer_id" field.
func (_c *OrganizationCreate) SetStripeCustomerID(v string) *OrganizationCreate {
	_c.mutation.SetStripeCustomerID(v)
	return _c
}

// SetNillableStripeCustomerID sets the "stripe_customer_id" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableStripeCustomerID(v *string) *OrganizationCreate {
	if v != nil {
		_c.SetStripeCustomerID(*v)
	}
	return _c
}

// SetBillingEmail sets the "billing_email" field.
func (_c *OrganizationCreate) SetBillingEmail(v string) *OrganizationCreate {
	_c.mutation.SetBillingEmail(v)
	return _c
}

// SetNillableBillingEmail sets the "billing_email" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableBillingEmail(v *string) *OrganizationCreate {
	if v != nil {
		_c.SetBillingEmail(*v)
	}
	return _c
}

// SetActive sets the "active" field.
func (_c *OrganizationCreate) SetActive(v bool) *OrganizationCreate {
	_c.mutation.SetActive(v)
	return _c
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableActive(v *bool) *OrganizationCreate {
	if v != nil {
		_c.SetActive(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OrganizationCreate) SetCreatedAt(v time.Time) *OrganizationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableCreatedAt(v *time.Time) *OrganizationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OrganizationCreate) SetUpdatedAt(v time.Time) *OrganizationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableUpdatedAt(v *time.Time) *OrganizationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetSamlEnabled sets the "saml_enabled" field.
func (_c *OrganizationCreate) SetSamlEnabled(v bool) *OrganizationCreate {
	_c.mutation.SetSamlEnabled(v)
	return _c
}

// SetNillableSamlEnabled sets the "saml_enabled" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableSamlEnabled(v *bool) *OrganizationCreate {
	if v != nil {
		_c.SetSamlEnabled(*v)
	}
	return _c
}

// SetSamlIdpMetadataURL sets the "saml_idp_metadata_url" field.
func (_c *OrganizationCreate) SetSamlIdpMetadataURL(v string) *OrganizationCreate {
	_c.mutation.SetSamlIdpMetadataURL(v)
	return _c
}

// SetNillableSamlIdpMetadataURL sets the "saml_idp_metadata_url" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableSamlIdpMetadataURL(v *string) *OrganizationCreate {
	if v != nil {
		_c.SetSamlIdpMetadataURL(*v)
	}
	return _c
}

// SetSamlIdpEntityID sets the "saml_idp_entity_id" field.
func (_c *OrganizationCreate) SetSamlIdpEntityID(v string) *OrganizationCreate {
	_c.mutation.SetSamlIdpEntityID(v)
	return _c
}

// SetNillableSamlIdpEntityID sets the "saml_idp_entity_id" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableSamlIdpEntityID(v *string) *OrganizationCreate {
	if v != nil {
		_c.SetSamlIdpEntityID(*v)
	}
	return _c
}

// SetSamlCertificate sets the "saml_certificate" field.
func (_c *OrganizationCreate) SetSamlCertificate(v string) *OrganizationCreate {
	_c.mutation.SetSamlCertificate(v)
	return _c
}

// SetNillableSamlCertificate sets the "saml_certificate" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableSamlCertificate(v *string) *OrganizationCreate {
	if v != nil {
		_c.SetSamlCertificate(*v)
	}
	return _c
}

// SetSamlPrivateKey sets the "saml_private_key" field.
func (_c *OrganizationCreate) SetSamlPrivateKey(v string) *OrganizationCreate {
	_c.mutation.SetSamlPrivateKey(v)
	return _c
}

// SetNillableSamlPrivateKey sets the "saml_private_key" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableSamlPrivateKey(v *string) *OrganizationCreate {
	if v != nil {
		_c.SetSamlPrivateKey(*v)
	}
	return _c
}

// SetOwner sets the "owner" edge to the User entity.
func (_c *OrganizationCreate) SetOwner(v *User) *OrganizationCreate {
	return _c.SetOwnerID(v.ID)
}

// AddMemberIDs adds the "members" edge to the OrganizationMember entity by IDs.
func (_c *OrganizationCreate) AddMemberIDs(ids ...int) *OrganizationCreate {
	_c.mutation.AddMemberIDs(ids...)
	return _c
}

// AddMembers adds the "members" edges to the OrganizationMember entity.
func (_c *OrganizationCreate) AddMembers(v ...*OrganizationMember) *OrganizationCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMemberIDs(ids...)
}

// AddExportIDs adds the "exports" edge to the Export entity by IDs.
func (_c *OrganizationCreate) AddExportIDs(ids ...int) *OrganizationCreate {
	_c.mutation.AddExportIDs(ids...)
	return _c
}

// AddExports adds the "exports" edges to the Export entity.
func (_c *OrganizationCreate) AddExports(v ...*Export) *OrganizationCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddExportIDs(ids...)
}

// Mutation returns the OrganizationMutation object of the builder.
func (_c *OrganizationCreate) Mutation() *OrganizationMutation {
	return _c.mutation
}

// Save creates the Organization in the database.
func (_c *OrganizationCreate) Save(ctx context.Context) (*Organization, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OrganizationCreate) SaveX(ctx context.Context) *Organization {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrganizationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrganizationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OrganizationCreate) defaults() {
	if _, ok := _c.mutation.SubscriptionTier(); !ok {
		v := organization.DefaultSubscriptionTier
		_c.mutation.SetSubscriptionTier(v)
	}
	if _, ok := _c.mutation.UsageLimit(); !ok {
		v := organization.DefaultUsageLimit
		_c.mutation.SetUsageLimit(v)
	}
	if _, ok := _c.mutation.UsageCount(); !ok {
		v := organization.DefaultUsageCount
		_c.mutation.SetUsageCount(v)
	}
	if _, ok := _c.mutation.LastResetAt(); !ok {
		v := organization.DefaultLastResetAt()
		_c.mutation.SetLastResetAt(v)
	}
	if _, ok := _c.mutation.Active(); !ok {
		v := organization.DefaultActive
		_c.mutation.SetActive(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := organization.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := organization.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.SamlEnabled(); !ok {
		v := organization.DefaultSamlEnabled
		_c.mutation.SetSamlEnabled(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OrganizationCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Organization.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := organization.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Organization.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "Organization.slug"`)}
	}
	if v, ok := _c.mutation.Slug(); ok {
		if err := organization.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Organization.slug": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OwnerID(); !ok {
		return &ValidationError{Name: "owner_id", err: errors.New(`ent: missing required field "Organization.owner_id"`)}
	}
	if _, ok := _c.mutation.SubscriptionTier(); !ok {
		return &ValidationError{Name: "subscription_tier", err: errors.New(`ent: missing required field "Organization.subscription_tier"`)}
	}
	if v, ok := _c.mutation.SubscriptionTier(); ok {
		if err := organization.SubscriptionTierValidator(v); err != nil {
			return &ValidationError{Name: "subscription_tier", err: fmt.Errorf(`ent: validator failed for field "Organization.subscription_tier": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UsageLimit(); !ok {
		return &ValidationError{Name: "usage_limit", err: errors.New(`ent: missing required field "Organization.usage_limit"`)}
	}
	if v, ok := _c.mutation.UsageLimit(); ok {
		if err := organization.UsageLimitValidator(v); err != nil {
			return &ValidationError{Name: "usage_limit", err: fmt.Errorf(`ent: validator failed for field "Organization.usage_limit": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UsageCount(); !ok {
		return &ValidationError{Name: "usage_count", err: errors.New(`ent: missing required field "Organization.usage_count"`)}
	}
	if v, ok := _c.mutation.UsageCount(); ok {
		if err := organization.UsageCountValidator(v); err != nil {
			return &ValidationError{Name: "usage_count", err: fmt.Errorf(`ent: validator failed for field "Organization.usage_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastResetAt(); !ok {
		return &ValidationError{Name: "last_reset_at", err: errors.New(`ent: missing required field "Organization.last_reset_at"`)}
	}
	if _, ok := _c.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "Organization.active"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Organization.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Organization.updated_at"`)}
	}
	if _, ok := _c.mutation.SamlEnabled(); !ok {
		return &ValidationError{Name: "saml_enabled", err: errors.New(`ent: missing required field "Organization.saml_enabled"`)}
	}
	if len(_c.mutation.OwnerIDs()) == 0 {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required edge "Organization.owner"`)}
	}
	return nil
}

func (_c *OrganizationCreate) sqlSave(ctx context.Context) (*Organization, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OrganizationCreate) createSpec() (*Organization, *sqlgraph.CreateSpec) {
	var (
		_node = &Organization{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(organization.Table, sqlgraph.NewFieldSpec(organization.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(organization.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(organization.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.SubscriptionTier(); ok {
		_spec.SetField(organization.FieldSubscriptionTier, field.TypeEnum, value)
		_node.SubscriptionTier = value
	}
	if value, ok := _c.mutation.UsageLimit(); ok {
		_spec.SetField(organization.FieldUsageLimit, field.TypeInt, value)
		_node.UsageLimit = value
	}
	if value, ok := _c.mutation.UsageCount(); ok {
		_spec.SetField(organization.FieldUsageCount, field.TypeInt, value)
		_node.UsageCount = value
	}
	if value, ok := _c.mutation.LastResetAt(); ok {
		_spec.SetField(organization.FieldLastResetAt, field.TypeTime, value)
		_node.LastResetAt = value
	}
	if value, ok := _c.mutation.StripeCustomerID(); ok {
		_spec.SetField(organization.FieldStripeCustomerID, field.TypeString, value)
		_node.StripeCustomerID = &value
	}
	if value, ok := _c.mutation.BillingEmail(); ok {
		_spec.SetField(organization.FieldBillingEmail, field.TypeString, value)
		_node.BillingEmail = &value
	}
	if value, ok := _c.mutation.Active(); ok {
		_spec.SetField(organization.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(organization.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(organization.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.SamlEnabled(); ok {
		_spec.SetField(organization.FieldSamlEnabled, field.TypeBool, value)
		_node.SamlEnabled = value
	}
	if value, ok := _c.mutation.SamlIdpMetadataURL(); ok {
		_spec.SetField(organization.FieldSamlIdpMetadataURL, field.TypeString, value)
		_node.SamlIdpMetadataURL = &value
	}
	if value, ok := _c.mutation.SamlIdpEntityID(); ok {
		_spec.SetField(organization.FieldSamlIdpEntityID, field.TypeString, value)
		_node.SamlIdpEntityID = &value
	}
	if value, ok := _c.mutation.SamlCertificate(); ok {
		_spec.SetField(organization.FieldSamlCertificate, field.TypeString, value)
		_node.SamlCertificate = &value
	}
	if value, ok := _c.mutation.SamlPrivateKey(); ok {
		_spec.SetField(organization.FieldSamlPrivateKey, field.TypeString, value)
		_node.SamlPrivateKey = &value
	}
	if nodes := _c.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   organization.OwnerTable,
			Columns: []string{organization.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OwnerID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organization.MembersTable,
			Columns: []string{organization.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organizationmember.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ExportsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organization.ExportsTable,
			Columns: []string{organization.ExportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(export.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OrganizationCreateBulk is the builder for creating many Organization entities in bulk.
type OrganizationCreateBulk struct {
	config
	err      error
	builders []*OrganizationCreate
}

// Save creates the Organization entities in the database.
func (_c *OrganizationCreateBulk) Save(ctx context.Context) ([]*Organization, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Organization, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrganizationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OrganizationCreateBulk) SaveX(ctx context.Context) []*Organization {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrganizationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrganizationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
