// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/jordanlanch/industrydb/ent/apikey"
	"github.com/jordanlanch/industrydb/ent/auditlog"
	"github.com/jordanlanch/industrydb/ent/export"
	"github.com/jordanlanch/industrydb/ent/industry"
	"github.com/jordanlanch/industrydb/ent/lead"
	"github.com/jordanlanch/industrydb/ent/leadnote"
	"github.com/jordanlanch/industrydb/ent/leadstatushistory"
	"github.com/jordanlanch/industrydb/ent/organization"
	"github.com/jordanlanch/industrydb/ent/organizationmember"
	"github.com/jordanlanch/industrydb/ent/savedsearch"
	"github.com/jordanlanch/industrydb/ent/schema"
	"github.com/jordanlanch/industrydb/ent/subscription"
	"github.com/jordanlanch/industrydb/ent/usagelog"
	"github.com/jordanlanch/industrydb/ent/user"
	"github.com/jordanlanch/industrydb/ent/webhook"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	apikeyFields := schema.APIKey{}.Fields()
	_ = apikeyFields
	// apikeyDescUserID is the schema descriptor for user_id field.
	apikeyDescUserID := apikeyFields[0].Descriptor()
	// apikey.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	apikey.UserIDValidator = apikeyDescUserID.Validators[0].(func(int) error)
	// apikeyDescKeyHash is the schema descriptor for key_hash field.
	apikeyDescKeyHash := apikeyFields[1].Descriptor()
	// apikey.KeyHashValidator is a validator for the "key_hash" field. It is called by the builders before save.
	apikey.KeyHashValidator = apikeyDescKeyHash.Validators[0].(func(string) error)
	// apikeyDescName is the schema descriptor for name field.
	apikeyDescName := apikeyFields[2].Descriptor()
	// apikey.NameValidator is a validator for the "name" field. It is called by the builders before save.
	apikey.NameValidator = apikeyDescName.Validators[0].(func(string) error)
	// apikeyDescPrefix is the schema descriptor for prefix field.
	apikeyDescPrefix := apikeyFields[3].Descriptor()
	// apikey.PrefixValidator is a validator for the "prefix" field. It is called by the builders before save.
	apikey.PrefixValidator = apikeyDescPrefix.Validators[0].(func(string) error)
	// apikeyDescUsageCount is the schema descriptor for usage_count field.
	apikeyDescUsageCount := apikeyFields[5].Descriptor()
	// apikey.DefaultUsageCount holds the default value on creation for the usage_count field.
	apikey.DefaultUsageCount = apikeyDescUsageCount.Default.(int)
	// apikey.UsageCountValidator is a validator for the "usage_count" field. It is called by the builders before save.
	apikey.UsageCountValidator = apikeyDescUsageCount.Validators[0].(func(int) error)
	// apikeyDescRevoked is the schema descriptor for revoked field.
	apikeyDescRevoked := apikeyFields[6].Descriptor()
	// apikey.DefaultRevoked holds the default value on creation for the revoked field.
	apikey.DefaultRevoked = apikeyDescRevoked.Default.(bool)
	// apikeyDescCreatedAt is the schema descriptor for created_at field.
	apikeyDescCreatedAt := apikeyFields[9].Descriptor()
	// apikey.DefaultCreatedAt holds the default value on creation for the created_at field.
	apikey.DefaultCreatedAt = apikeyDescCreatedAt.Default.(func() time.Time)
	// apikeyDescUpdatedAt is the schema descriptor for updated_at field.
	apikeyDescUpdatedAt := apikeyFields[10].Descriptor()
	// apikey.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	apikey.DefaultUpdatedAt = apikeyDescUpdatedAt.Default.(func() time.Time)
	// apikey.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	apikey.UpdateDefaultUpdatedAt = apikeyDescUpdatedAt.UpdateDefault.(func() time.Time)
	auditlogFields := schema.AuditLog{}.Fields()
	_ = auditlogFields
	// auditlogDescCreatedAt is the schema descriptor for created_at field.
	auditlogDescCreatedAt := auditlogFields[9].Descriptor()
	// auditlog.DefaultCreatedAt holds the default value on creation for the created_at field.
	auditlog.DefaultCreatedAt = auditlogDescCreatedAt.Default.(func() time.Time)
	exportFields := schema.Export{}.Fields()
	_ = exportFields
	// exportDescUserID is the schema descriptor for user_id field.
	exportDescUserID := exportFields[0].Descriptor()
	// export.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	export.UserIDValidator = exportDescUserID.Validators[0].(func(int) error)
	// exportDescLeadCount is the schema descriptor for lead_count field.
	exportDescLeadCount := exportFields[4].Descriptor()
	// export.LeadCountValidator is a validator for the "lead_count" field. It is called by the builders before save.
	export.LeadCountValidator = exportDescLeadCount.Validators[0].(func(int) error)
	// exportDescCreatedAt is the schema descriptor for created_at field.
	exportDescCreatedAt := exportFields[10].Descriptor()
	// export.DefaultCreatedAt holds the default value on creation for the created_at field.
	export.DefaultCreatedAt = exportDescCreatedAt.Default.(func() time.Time)
	// exportDescUpdatedAt is the schema descriptor for updated_at field.
	exportDescUpdatedAt := exportFields[11].Descriptor()
	// export.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	export.DefaultUpdatedAt = exportDescUpdatedAt.Default.(func() time.Time)
	// export.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	export.UpdateDefaultUpdatedAt = exportDescUpdatedAt.UpdateDefault.(func() time.Time)
	industryFields := schema.Industry{}.Fields()
	_ = industryFields
	// industryDescName is the schema descriptor for name field.
	industryDescName := industryFields[1].Descriptor()
	// industry.NameValidator is a validator for the "name" field. It is called by the builders before save.
	industry.NameValidator = industryDescName.Validators[0].(func(string) error)
	// industryDescCategory is the schema descriptor for category field.
	industryDescCategory := industryFields[2].Descriptor()
	// industry.CategoryValidator is a validator for the "category" field. It is called by the builders before save.
	industry.CategoryValidator = industryDescCategory.Validators[0].(func(string) error)
	// industryDescOsmPrimaryTag is the schema descriptor for osm_primary_tag field.
	industryDescOsmPrimaryTag := industryFields[4].Descriptor()
	// industry.OsmPrimaryTagValidator is a validator for the "osm_primary_tag" field. It is called by the builders before save.
	industry.OsmPrimaryTagValidator = industryDescOsmPrimaryTag.Validators[0].(func(string) error)
	// industryDescActive is the schema descriptor for active field.
	industryDescActive := industryFields[7].Descriptor()
	// industry.DefaultActive holds the default value on creation for the active field.
	industry.DefaultActive = industryDescActive.Default.(bool)
	// industryDescSortOrder is the schema descriptor for sort_order field.
	industryDescSortOrder := industryFields[8].Descriptor()
	// industry.DefaultSortOrder holds the default value on creation for the sort_order field.
	industry.DefaultSortOrder = industryDescSortOrder.Default.(int)
	// industryDescCreatedAt is the schema descriptor for created_at field.
	industryDescCreatedAt := industryFields[9].Descriptor()
	// industry.DefaultCreatedAt holds the default value on creation for the created_at field.
	industry.DefaultCreatedAt = industryDescCreatedAt.Default.(func() time.Time)
	// industryDescUpdatedAt is the schema descriptor for updated_at field.
	industryDescUpdatedAt := industryFields[10].Descriptor()
	// industry.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	industry.DefaultUpdatedAt = industryDescUpdatedAt.Default.(func() time.Time)
	// industry.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	industry.UpdateDefaultUpdatedAt = industryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// industryDescID is the schema descriptor for id field.
	industryDescID := industryFields[0].Descriptor()
	// industry.IDValidator is a validator for the "id" field. It is called by the builders before save.
	industry.IDValidator = industryDescID.Validators[0].(func(string) error)
	leadFields := schema.Lead{}.Fields()
	_ = leadFields
	// leadDescName is the schema descriptor for name field.
	leadDescName := leadFields[0].Descriptor()
	// lead.NameValidator is a validator for the "name" field. It is called by the builders before save.
	lead.NameValidator = leadDescName.Validators[0].(func(string) error)
	// leadDescCountry is the schema descriptor for country field.
	leadDescCountry := leadFields[2].Descriptor()
	// lead.CountryValidator is a validator for the "country" field. It is called by the builders before save.
	lead.CountryValidator = func() func(string) error {
		validators := leadDescCountry.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(country string) error {
			for _, fn := range fns {
				if err := fn(country); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// leadDescCity is the schema descriptor for city field.
	leadDescCity := leadFields[3].Descriptor()
	// lead.CityValidator is a validator for the "city" field. It is called by the builders before save.
	lead.CityValidator = leadDescCity.Validators[0].(func(string) error)
	// leadDescVerified is the schema descriptor for verified field.
	leadDescVerified := leadFields[12].Descriptor()
	// lead.DefaultVerified holds the default value on creation for the verified field.
	lead.DefaultVerified = leadDescVerified.Default.(bool)
	// leadDescQualityScore is the schema descriptor for quality_score field.
	leadDescQualityScore := leadFields[13].Descriptor()
	// lead.DefaultQualityScore holds the default value on creation for the quality_score field.
	lead.DefaultQualityScore = leadDescQualityScore.Default.(int)
	// lead.QualityScoreValidator is a validator for the "quality_score" field. It is called by the builders before save.
	lead.QualityScoreValidator = func() func(int) error {
		validators := leadDescQualityScore.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(quality_score int) error {
			for _, fn := range fns {
				if err := fn(quality_score); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// leadDescStatusChangedAt is the schema descriptor for status_changed_at field.
	leadDescStatusChangedAt := leadFields[15].Descriptor()
	// lead.DefaultStatusChangedAt holds the default value on creation for the status_changed_at field.
	lead.DefaultStatusChangedAt = leadDescStatusChangedAt.Default.(func() time.Time)
	// leadDescCreatedAt is the schema descriptor for created_at field.
	leadDescCreatedAt := leadFields[24].Descriptor()
	// lead.DefaultCreatedAt holds the default value on creation for the created_at field.
	lead.DefaultCreatedAt = leadDescCreatedAt.Default.(func() time.Time)
	// leadDescUpdatedAt is the schema descriptor for updated_at field.
	leadDescUpdatedAt := leadFields[25].Descriptor()
	// lead.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	lead.DefaultUpdatedAt = leadDescUpdatedAt.Default.(func() time.Time)
	// lead.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	lead.UpdateDefaultUpdatedAt = leadDescUpdatedAt.UpdateDefault.(func() time.Time)
	leadnoteFields := schema.LeadNote{}.Fields()
	_ = leadnoteFields
	// leadnoteDescLeadID is the schema descriptor for lead_id field.
	leadnoteDescLeadID := leadnoteFields[0].Descriptor()
	// leadnote.LeadIDValidator is a validator for the "lead_id" field. It is called by the builders before save.
	leadnote.LeadIDValidator = leadnoteDescLeadID.Validators[0].(func(int) error)
	// leadnoteDescUserID is the schema descriptor for user_id field.
	leadnoteDescUserID := leadnoteFields[1].Descriptor()
	// leadnote.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	leadnote.UserIDValidator = leadnoteDescUserID.Validators[0].(func(int) error)
	// leadnoteDescContent is the schema descriptor for content field.
	leadnoteDescContent := leadnoteFields[2].Descriptor()
	// leadnote.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	leadnote.ContentValidator = func() func(string) error {
		validators := leadnoteDescContent.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(content string) error {
			for _, fn := range fns {
				if err := fn(content); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// leadnoteDescIsPinned is the schema descriptor for is_pinned field.
	leadnoteDescIsPinned := leadnoteFields[3].Descriptor()
	// leadnote.DefaultIsPinned holds the default value on creation for the is_pinned field.
	leadnote.DefaultIsPinned = leadnoteDescIsPinned.Default.(bool)
	// leadnoteDescCreatedAt is the schema descriptor for created_at field.
	leadnoteDescCreatedAt := leadnoteFields[4].Descriptor()
	// leadnote.DefaultCreatedAt holds the default value on creation for the created_at field.
	leadnote.DefaultCreatedAt = leadnoteDescCreatedAt.Default.(func() time.Time)
	// leadnoteDescUpdatedAt is the schema descriptor for updated_at field.
	leadnoteDescUpdatedAt := leadnoteFields[5].Descriptor()
	// leadnote.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	leadnote.DefaultUpdatedAt = leadnoteDescUpdatedAt.Default.(func() time.Time)
	// leadnote.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	leadnote.UpdateDefaultUpdatedAt = leadnoteDescUpdatedAt.UpdateDefault.(func() time.Time)
	leadstatushistoryFields := schema.LeadStatusHistory{}.Fields()
	_ = leadstatushistoryFields
	// leadstatushistoryDescLeadID is the schema descriptor for lead_id field.
	leadstatushistoryDescLeadID := leadstatushistoryFields[0].Descriptor()
	// leadstatushistory.LeadIDValidator is a validator for the "lead_id" field. It is called by the builders before save.
	leadstatushistory.LeadIDValidator = leadstatushistoryDescLeadID.Validators[0].(func(int) error)
	// leadstatushistoryDescUserID is the schema descriptor for user_id field.
	leadstatushistoryDescUserID := leadstatushistoryFields[1].Descriptor()
	// leadstatushistory.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	leadstatushistory.UserIDValidator = leadstatushistoryDescUserID.Validators[0].(func(int) error)
	// leadstatushistoryDescReason is the schema descriptor for reason field.
	leadstatushistoryDescReason := leadstatushistoryFields[4].Descriptor()
	// leadstatushistory.ReasonValidator is a validator for the "reason" field. It is called by the builders before save.
	leadstatushistory.ReasonValidator = leadstatushistoryDescReason.Validators[0].(func(string) error)
	// leadstatushistoryDescCreatedAt is the schema descriptor for created_at field.
	leadstatushistoryDescCreatedAt := leadstatushistoryFields[5].Descriptor()
	// leadstatushistory.DefaultCreatedAt holds the default value on creation for the created_at field.
	leadstatushistory.DefaultCreatedAt = leadstatushistoryDescCreatedAt.Default.(func() time.Time)
	organizationFields := schema.Organization{}.Fields()
	_ = organizationFields
	// organizationDescName is the schema descriptor for name field.
	organizationDescName := organizationFields[0].Descriptor()
	// organization.NameValidator is a validator for the "name" field. It is called by the builders before save.
	organization.NameValidator = organizationDescName.Validators[0].(func(string) error)
	// organizationDescSlug is the schema descriptor for slug field.
	organizationDescSlug := organizationFields[1].Descriptor()
	// organization.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	organization.SlugValidator = organizationDescSlug.Validators[0].(func(string) error)
	// organizationDescUsageLimit is the schema descriptor for usage_limit field.
	organizationDescUsageLimit := organizationFields[4].Descriptor()
	// organization.DefaultUsageLimit holds the default value on creation for the usage_limit field.
	organization.DefaultUsageLimit = organizationDescUsageLimit.Default.(int)
	// organization.UsageLimitValidator is a validator for the "usage_limit" field. It is called by the builders before save.
	organization.UsageLimitValidator = organizationDescUsageLimit.Validators[0].(func(int) error)
	// organizationDescUsageCount is the schema descriptor for usage_count field.
	organizationDescUsageCount := organizationFields[5].Descriptor()
	// organization.DefaultUsageCount holds the default value on creation for the usage_count field.
	organization.DefaultUsageCount = organizationDescUsageCount.Default.(int)
	// organization.UsageCountValidator is a validator for the "usage_count" field. It is called by the builders before save.
	organization.UsageCountValidator = organizationDescUsageCount.Validators[0].(func(int) error)
	// organizationDescLastResetAt is the schema descriptor for last_reset_at field.
	organizationDescLastResetAt := organizationFields[6].Descriptor()
	// organization.DefaultLastResetAt holds the default value on creation for the last_reset_at field.
	organization.DefaultLastResetAt = organizationDescLastResetAt.Default.(func() time.Time)
	// organizationDescActive is the schema descriptor for active field.
	organizationDescActive := organizationFields[9].Descriptor()
	// organization.DefaultActive holds the default value on creation for the active field.
	organization.DefaultActive = organizationDescActive.Default.(bool)
	// organizationDescCreatedAt is the schema descriptor for created_at field.
	organizationDescCreatedAt := organizationFields[10].Descriptor()
	// organization.DefaultCreatedAt holds the default value on creation for the created_at field.
	organization.DefaultCreatedAt = organizationDescCreatedAt.Default.(func() time.Time)
	// organizationDescUpdatedAt is the schema descriptor for updated_at field.
	organizationDescUpdatedAt := organizationFields[11].Descriptor()
	// organization.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	organization.DefaultUpdatedAt = organizationDescUpdatedAt.Default.(func() time.Time)
	// organization.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	organization.UpdateDefaultUpdatedAt = organizationDescUpdatedAt.UpdateDefault.(func() time.Time)
	organizationmemberFields := schema.OrganizationMember{}.Fields()
	_ = organizationmemberFields
	// organizationmemberDescJoinedAt is the schema descriptor for joined_at field.
	organizationmemberDescJoinedAt := organizationmemberFields[6].Descriptor()
	// organizationmember.DefaultJoinedAt holds the default value on creation for the joined_at field.
	organizationmember.DefaultJoinedAt = organizationmemberDescJoinedAt.Default.(func() time.Time)
	// organizationmemberDescCreatedAt is the schema descriptor for created_at field.
	organizationmemberDescCreatedAt := organizationmemberFields[7].Descriptor()
	// organizationmember.DefaultCreatedAt holds the default value on creation for the created_at field.
	organizationmember.DefaultCreatedAt = organizationmemberDescCreatedAt.Default.(func() time.Time)
	// organizationmemberDescUpdatedAt is the schema descriptor for updated_at field.
	organizationmemberDescUpdatedAt := organizationmemberFields[8].Descriptor()
	// organizationmember.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	organizationmember.DefaultUpdatedAt = organizationmemberDescUpdatedAt.Default.(func() time.Time)
	// organizationmember.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	organizationmember.UpdateDefaultUpdatedAt = organizationmemberDescUpdatedAt.UpdateDefault.(func() time.Time)
	savedsearchFields := schema.SavedSearch{}.Fields()
	_ = savedsearchFields
	// savedsearchDescName is the schema descriptor for name field.
	savedsearchDescName := savedsearchFields[1].Descriptor()
	// savedsearch.NameValidator is a validator for the "name" field. It is called by the builders before save.
	savedsearch.NameValidator = func() func(string) error {
		validators := savedsearchDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// savedsearchDescCreatedAt is the schema descriptor for created_at field.
	savedsearchDescCreatedAt := savedsearchFields[3].Descriptor()
	// savedsearch.DefaultCreatedAt holds the default value on creation for the created_at field.
	savedsearch.DefaultCreatedAt = savedsearchDescCreatedAt.Default.(func() time.Time)
	// savedsearchDescUpdatedAt is the schema descriptor for updated_at field.
	savedsearchDescUpdatedAt := savedsearchFields[4].Descriptor()
	// savedsearch.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	savedsearch.DefaultUpdatedAt = savedsearchDescUpdatedAt.Default.(func() time.Time)
	// savedsearch.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	savedsearch.UpdateDefaultUpdatedAt = savedsearchDescUpdatedAt.UpdateDefault.(func() time.Time)
	subscriptionFields := schema.Subscription{}.Fields()
	_ = subscriptionFields
	// subscriptionDescUserID is the schema descriptor for user_id field.
	subscriptionDescUserID := subscriptionFields[0].Descriptor()
	// subscription.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	subscription.UserIDValidator = subscriptionDescUserID.Validators[0].(func(int) error)
	// subscriptionDescCancelAtPeriodEnd is the schema descriptor for cancel_at_period_end field.
	subscriptionDescCancelAtPeriodEnd := subscriptionFields[7].Descriptor()
	// subscription.DefaultCancelAtPeriodEnd holds the default value on creation for the cancel_at_period_end field.
	subscription.DefaultCancelAtPeriodEnd = subscriptionDescCancelAtPeriodEnd.Default.(bool)
	// subscriptionDescCreatedAt is the schema descriptor for created_at field.
	subscriptionDescCreatedAt := subscriptionFields[9].Descriptor()
	// subscription.DefaultCreatedAt holds the default value on creation for the created_at field.
	subscription.DefaultCreatedAt = subscriptionDescCreatedAt.Default.(func() time.Time)
	// subscriptionDescUpdatedAt is the schema descriptor for updated_at field.
	subscriptionDescUpdatedAt := subscriptionFields[10].Descriptor()
	// subscription.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	subscription.DefaultUpdatedAt = subscriptionDescUpdatedAt.Default.(func() time.Time)
	// subscription.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	subscription.UpdateDefaultUpdatedAt = subscriptionDescUpdatedAt.UpdateDefault.(func() time.Time)
	usagelogFields := schema.UsageLog{}.Fields()
	_ = usagelogFields
	// usagelogDescCount is the schema descriptor for count field.
	usagelogDescCount := usagelogFields[2].Descriptor()
	// usagelog.DefaultCount holds the default value on creation for the count field.
	usagelog.DefaultCount = usagelogDescCount.Default.(int)
	// usagelogDescCreatedAt is the schema descriptor for created_at field.
	usagelogDescCreatedAt := usagelogFields[4].Descriptor()
	// usagelog.DefaultCreatedAt holds the default value on creation for the created_at field.
	usagelog.DefaultCreatedAt = usagelogDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[0].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[1].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[2].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescUsageCount is the schema descriptor for usage_count field.
	userDescUsageCount := userFields[5].Descriptor()
	// user.DefaultUsageCount holds the default value on creation for the usage_count field.
	user.DefaultUsageCount = userDescUsageCount.Default.(int)
	// user.UsageCountValidator is a validator for the "usage_count" field. It is called by the builders before save.
	user.UsageCountValidator = userDescUsageCount.Validators[0].(func(int) error)
	// userDescUsageLimit is the schema descriptor for usage_limit field.
	userDescUsageLimit := userFields[6].Descriptor()
	// user.DefaultUsageLimit holds the default value on creation for the usage_limit field.
	user.DefaultUsageLimit = userDescUsageLimit.Default.(int)
	// user.UsageLimitValidator is a validator for the "usage_limit" field. It is called by the builders before save.
	user.UsageLimitValidator = userDescUsageLimit.Validators[0].(func(int) error)
	// userDescLastResetAt is the schema descriptor for last_reset_at field.
	userDescLastResetAt := userFields[7].Descriptor()
	// user.DefaultLastResetAt holds the default value on creation for the last_reset_at field.
	user.DefaultLastResetAt = userDescLastResetAt.Default.(func() time.Time)
	// userDescEmailVerified is the schema descriptor for email_verified field.
	userDescEmailVerified := userFields[9].Descriptor()
	// user.DefaultEmailVerified holds the default value on creation for the email_verified field.
	user.DefaultEmailVerified = userDescEmailVerified.Default.(bool)
	// userDescOnboardingCompleted is the schema descriptor for onboarding_completed field.
	userDescOnboardingCompleted := userFields[14].Descriptor()
	// user.DefaultOnboardingCompleted holds the default value on creation for the onboarding_completed field.
	user.DefaultOnboardingCompleted = userDescOnboardingCompleted.Default.(bool)
	// userDescTotpEnabled is the schema descriptor for totp_enabled field.
	userDescTotpEnabled := userFields[15].Descriptor()
	// user.DefaultTotpEnabled holds the default value on creation for the totp_enabled field.
	user.DefaultTotpEnabled = userDescTotpEnabled.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[20].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[21].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescOnboardingStep is the schema descriptor for onboarding_step field.
	userDescOnboardingStep := userFields[23].Descriptor()
	// user.DefaultOnboardingStep holds the default value on creation for the onboarding_step field.
	user.DefaultOnboardingStep = userDescOnboardingStep.Default.(int)
	// user.OnboardingStepValidator is a validator for the "onboarding_step" field. It is called by the builders before save.
	user.OnboardingStepValidator = userDescOnboardingStep.Validators[0].(func(int) error)
	webhookFields := schema.Webhook{}.Fields()
	_ = webhookFields
	// webhookDescURL is the schema descriptor for url field.
	webhookDescURL := webhookFields[0].Descriptor()
	// webhook.URLValidator is a validator for the "url" field. It is called by the builders before save.
	webhook.URLValidator = webhookDescURL.Validators[0].(func(string) error)
	// webhookDescActive is the schema descriptor for active field.
	webhookDescActive := webhookFields[3].Descriptor()
	// webhook.DefaultActive holds the default value on creation for the active field.
	webhook.DefaultActive = webhookDescActive.Default.(bool)
	// webhookDescRetryCount is the schema descriptor for retry_count field.
	webhookDescRetryCount := webhookFields[5].Descriptor()
	// webhook.DefaultRetryCount holds the default value on creation for the retry_count field.
	webhook.DefaultRetryCount = webhookDescRetryCount.Default.(int)
	// webhookDescSuccessCount is the schema descriptor for success_count field.
	webhookDescSuccessCount := webhookFields[7].Descriptor()
	// webhook.DefaultSuccessCount holds the default value on creation for the success_count field.
	webhook.DefaultSuccessCount = webhookDescSuccessCount.Default.(int)
	// webhookDescFailureCount is the schema descriptor for failure_count field.
	webhookDescFailureCount := webhookFields[8].Descriptor()
	// webhook.DefaultFailureCount holds the default value on creation for the failure_count field.
	webhook.DefaultFailureCount = webhookDescFailureCount.Default.(int)
	// webhookDescCreatedAt is the schema descriptor for created_at field.
	webhookDescCreatedAt := webhookFields[9].Descriptor()
	// webhook.DefaultCreatedAt holds the default value on creation for the created_at field.
	webhook.DefaultCreatedAt = webhookDescCreatedAt.Default.(func() time.Time)
	// webhookDescUpdatedAt is the schema descriptor for updated_at field.
	webhookDescUpdatedAt := webhookFields[10].Descriptor()
	// webhook.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	webhook.DefaultUpdatedAt = webhookDescUpdatedAt.Default.(func() time.Time)
	// webhook.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	webhook.UpdateDefaultUpdatedAt = webhookDescUpdatedAt.UpdateDefault.(func() time.Time)
}
