// Code generated by ent, DO NOT EDIT.

package emailsequencestep

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the emailsequencestep type in the database.
	Label = "email_sequence_step"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSequenceID holds the string denoting the sequence_id field in the database.
	FieldSequenceID = "sequence_id"
	// FieldStepOrder holds the string denoting the step_order field in the database.
	FieldStepOrder = "step_order"
	// FieldDelayDays holds the string denoting the delay_days field in the database.
	FieldDelayDays = "delay_days"
	// FieldSubject holds the string denoting the subject field in the database.
	FieldSubject = "subject"
	// FieldBody holds the string denoting the body field in the database.
	FieldBody = "body"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeSequence holds the string denoting the sequence edge name in mutations.
	EdgeSequence = "sequence"
	// EdgeSends holds the string denoting the sends edge name in mutations.
	EdgeSends = "sends"
	// Table holds the table name of the emailsequencestep in the database.
	Table = "email_sequence_steps"
	// SequenceTable is the table that holds the sequence relation/edge.
	SequenceTable = "email_sequence_steps"
	// SequenceInverseTable is the table name for the EmailSequence entity.
	// It exists in this package in order to avoid circular dependency with the "emailsequence" package.
	SequenceInverseTable = "email_sequences"
	// SequenceColumn is the table column denoting the sequence relation/edge.
	SequenceColumn = "sequence_id"
	// SendsTable is the table that holds the sends relation/edge.
	SendsTable = "email_sequence_sends"
	// SendsInverseTable is the table name for the EmailSequenceSend entity.
	// It exists in this package in order to avoid circular dependency with the "emailsequencesend" package.
	SendsInverseTable = "email_sequence_sends"
	// SendsColumn is the table column denoting the sends relation/edge.
	SendsColumn = "step_id"
)

// Columns holds all SQL columns for emailsequencestep fields.
var Columns = []string{
	FieldID,
	FieldSequenceID,
	FieldStepOrder,
	FieldDelayDays,
	FieldSubject,
	FieldBody,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// SequenceIDValidator is a validator for the "sequence_id" field. It is called by the builders before save.
	SequenceIDValidator func(int) error
	// StepOrderValidator is a validator for the "step_order" field. It is called by the builders before save.
	StepOrderValidator func(int) error
	// DefaultDelayDays holds the default value on creation for the "delay_days" field.
	DefaultDelayDays int
	// DelayDaysValidator is a validator for the "delay_days" field. It is called by the builders before save.
	DelayDaysValidator func(int) error
	// SubjectValidator is a validator for the "subject" field. It is called by the builders before save.
	SubjectValidator func(string) error
	// BodyValidator is a validator for the "body" field. It is called by the builders before save.
	BodyValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the EmailSequenceStep queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySequenceID orders the results by the sequence_id field.
func BySequenceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSequenceID, opts...).ToFunc()
}

// ByStepOrder orders the results by the step_order field.
func ByStepOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStepOrder, opts...).ToFunc()
}

// ByDelayDays orders the results by the delay_days field.
func ByDelayDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDelayDays, opts...).ToFunc()
}

// BySubject orders the results by the subject field.
func BySubject(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubject, opts...).ToFunc()
}

// ByBody orders the results by the body field.
func ByBody(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBody, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// BySequenceField orders the results by sequence field.
func BySequenceField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSequenceStep(), sql.OrderByField(field, opts...))
	}
}

// BySendsCount orders the results by sends count.
func BySendsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSendsStep(), opts...)
	}
}

// BySends orders the results by sends terms.
func BySends(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSendsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newSequenceStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SequenceInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SequenceTable, SequenceColumn),
	)
}
func newSendsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SendsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SendsTable, SendsColumn),
	)
}
