package industries

// BeautySubNiches returns all beauty salon sub-niches
func BeautySubNiches() []SubNicheConfig {
	return []SubNicheConfig{
		{
			ID:          "hair",
			Name:        "Hair Salon",
			Icon:        "💇",
			OSMTag:      "beauty",
			OSMValues:   []string{"hair", "hair_salon"},
			Description: "Hair salons and stylists",
			SortOrder:   1,
			Popular:     true,
		},
		{
			ID:          "nails",
			Name:        "Nail Salon",
			Icon:        "💅",
			OSMTag:      "beauty",
			OSMValues:   []string{"nails", "nail_salon"},
			Description: "Nail salons, manicures, and pedicures",
			SortOrder:   2,
			Popular:     true,
		},
		{
			ID:          "skin_care",
			Name:        "Skin Care/Facial",
			Icon:        "🧖",
			OSMTag:      "beauty",
			OSMValues:   []string{"skin_care", "facial", "esthetician"},
			Description: "Facials, skin treatments, and estheticians",
			SortOrder:   3,
			Popular:     false,
		},
		{
			ID:          "waxing",
			Name:        "Waxing/Hair Removal",
			Icon:        "✨",
			OSMTag:      "beauty",
			OSMValues:   []string{"waxing", "hair_removal"},
			Description: "Waxing and hair removal services",
			SortOrder:   4,
			Popular:     false,
		},
		{
			ID:          "makeup",
			Name:        "Makeup Artist",
			Icon:        "💄",
			OSMTag:      "beauty",
			OSMValues:   []string{"makeup", "cosmetics"},
			Description: "Makeup artists and cosmetic services",
			SortOrder:   5,
			Popular:     false,
		},
		{
			ID:          "lashes",
			Name:        "Lash Extensions",
			Icon:        "👁️",
			OSMTag:      "beauty",
			OSMValues:   []string{"lashes", "eyelash", "brows"},
			Description: "Lash extensions, brows, and eye services",
			SortOrder:   6,
			Popular:     false,
		},
		{
			ID:          "tanning",
			Name:        "Tanning Salon",
			Icon:        "☀️",
			OSMTag:      "beauty",
			OSMValues:   []string{"tanning", "solarium"},
			Description: "Tanning salons and spray tans",
			SortOrder:   7,
			Popular:     false,
		},
		{
			ID:          "other",
			Name:        "Other Beauty Services",
			Icon:        "💆",
			OSMTag:      "beauty",
			OSMValues:   []string{},
			Description: "Other beauty and cosmetic services",
			SortOrder:   8,
			Popular:     false,
		},
	}
}
