package industries

// RestaurantSubNiches returns all restaurant cuisine sub-niches
func RestaurantSubNiches() []SubNicheConfig {
	return []SubNicheConfig{
		// Popular cuisines (sorted by popularity)
		{
			ID:          "italian",
			Name:        "Italian",
			Icon:        "🇮🇹",
			OSMTag:      "cuisine",
			OSMValues:   []string{"italian", "pizza", "pasta"},
			Description: "Italian restaurants, pizzerias, and trattorias",
			SortOrder:   1,
			Popular:     true,
		},
		{
			ID:          "mexican",
			Name:        "Mexican",
			Icon:        "🇲🇽",
			OSMTag:      "cuisine",
			OSMValues:   []string{"mexican", "tex-mex", "tacos"},
			Description: "Mexican restaurants and taquerias",
			SortOrder:   2,
			Popular:     true,
		},
		{
			ID:          "japanese",
			Name:        "Japanese",
			Icon:        "🇯🇵",
			OSMTag:      "cuisine",
			OSMValues:   []string{"japanese", "sushi", "ramen"},
			Description: "Japanese restaurants, sushi bars, and ramen shops",
			SortOrder:   3,
			Popular:     true,
		},
		{
			ID:          "chinese",
			Name:        "Chinese",
			Icon:        "🇨🇳",
			OSMTag:      "cuisine",
			OSMValues:   []string{"chinese", "cantonese", "szechuan", "dim_sum"},
			Description: "Chinese restaurants and dim sum",
			SortOrder:   4,
			Popular:     true,
		},
		{
			ID:          "thai",
			Name:        "Thai",
			Icon:        "🇹🇭",
			OSMTag:      "cuisine",
			OSMValues:   []string{"thai"},
			Description: "Thai restaurants and street food",
			SortOrder:   5,
			Popular:     true,
		},
		{
			ID:          "indian",
			Name:        "Indian",
			Icon:        "🇮🇳",
			OSMTag:      "cuisine",
			OSMValues:   []string{"indian", "curry"},
			Description: "Indian restaurants and curry houses",
			SortOrder:   6,
			Popular:     true,
		},
		{
			ID:          "french",
			Name:        "French",
			Icon:        "🇫🇷",
			OSMTag:      "cuisine",
			OSMValues:   []string{"french", "bistro"},
			Description: "French restaurants and bistros",
			SortOrder:   7,
			Popular:     true,
		},
		{
			ID:          "american",
			Name:        "American",
			Icon:        "🇺🇸",
			OSMTag:      "cuisine",
			OSMValues:   []string{"american", "burger", "steak"},
			Description: "American restaurants, diners, and steakhouses",
			SortOrder:   8,
			Popular:     true,
		},
		{
			ID:          "greek",
			Name:        "Greek",
			Icon:        "🇬🇷",
			OSMTag:      "cuisine",
			OSMValues:   []string{"greek", "mediterranean"},
			Description: "Greek tavernas and Mediterranean cuisine",
			SortOrder:   9,
			Popular:     false,
		},
		{
			ID:          "vietnamese",
			Name:        "Vietnamese",
			Icon:        "🇻🇳",
			OSMTag:      "cuisine",
			OSMValues:   []string{"vietnamese", "pho"},
			Description: "Vietnamese restaurants and pho shops",
			SortOrder:   10,
			Popular:     false,
		},
		{
			ID:          "korean",
			Name:        "Korean",
			Icon:        "🇰🇷",
			OSMTag:      "cuisine",
			OSMValues:   []string{"korean", "bbq"},
			Description: "Korean restaurants and BBQ",
			SortOrder:   11,
			Popular:     false,
		},
		{
			ID:          "spanish",
			Name:        "Spanish",
			Icon:        "🇪🇸",
			OSMTag:      "cuisine",
			OSMValues:   []string{"spanish", "tapas"},
			Description: "Spanish restaurants and tapas bars",
			SortOrder:   12,
			Popular:     false,
		},
		{
			ID:          "turkish",
			Name:        "Turkish",
			Icon:        "🇹🇷",
			OSMTag:      "cuisine",
			OSMValues:   []string{"turkish", "kebab"},
			Description: "Turkish restaurants and kebab shops",
			SortOrder:   13,
			Popular:     false,
		},
		{
			ID:          "lebanese",
			Name:        "Lebanese",
			Icon:        "🇱🇧",
			OSMTag:      "cuisine",
			OSMValues:   []string{"lebanese", "middle_eastern"},
			Description: "Lebanese and Middle Eastern cuisine",
			SortOrder:   14,
			Popular:     false,
		},
		{
			ID:          "brazilian",
			Name:        "Brazilian",
			Icon:        "🇧🇷",
			OSMTag:      "cuisine",
			OSMValues:   []string{"brazilian", "churrasco"},
			Description: "Brazilian steakhouses and restaurants",
			SortOrder:   15,
			Popular:     false,
		},
		{
			ID:          "caribbean",
			Name:        "Caribbean",
			Icon:        "🏝️",
			OSMTag:      "cuisine",
			OSMValues:   []string{"caribbean", "jamaican", "cuban"},
			Description: "Caribbean cuisine and island food",
			SortOrder:   16,
			Popular:     false,
		},
		{
			ID:          "ethiopian",
			Name:        "Ethiopian",
			Icon:        "🇪🇹",
			OSMTag:      "cuisine",
			OSMValues:   []string{"ethiopian", "african"},
			Description: "Ethiopian and African cuisine",
			SortOrder:   17,
			Popular:     false,
		},
		{
			ID:          "moroccan",
			Name:        "Moroccan",
			Icon:        "🇲🇦",
			OSMTag:      "cuisine",
			OSMValues:   []string{"moroccan"},
			Description: "Moroccan restaurants and tagines",
			SortOrder:   18,
			Popular:     false,
		},
		{
			ID:          "peruvian",
			Name:        "Peruvian",
			Icon:        "🇵🇪",
			OSMTag:      "cuisine",
			OSMValues:   []string{"peruvian"},
			Description: "Peruvian cuisine and ceviche",
			SortOrder:   19,
			Popular:     false,
		},
		{
			ID:          "argentinian",
			Name:        "Argentinian",
			Icon:        "🇦🇷",
			OSMTag:      "cuisine",
			OSMValues:   []string{"argentinian", "steak"},
			Description: "Argentinian steakhouses and parrillas",
			SortOrder:   20,
			Popular:     false,
		},
		{
			ID:          "filipino",
			Name:        "Filipino",
			Icon:        "🇵🇭",
			OSMTag:      "cuisine",
			OSMValues:   []string{"filipino"},
			Description: "Filipino restaurants and eateries",
			SortOrder:   21,
			Popular:     false,
		},
		{
			ID:          "indonesian",
			Name:        "Indonesian",
			Icon:        "🇮🇩",
			OSMTag:      "cuisine",
			OSMValues:   []string{"indonesian"},
			Description: "Indonesian cuisine and satay",
			SortOrder:   22,
			Popular:     false,
		},
		{
			ID:          "malaysian",
			Name:        "Malaysian",
			Icon:        "🇲🇾",
			OSMTag:      "cuisine",
			OSMValues:   []string{"malaysian"},
			Description: "Malaysian restaurants and hawker food",
			SortOrder:   23,
			Popular:     false,
		},
		{
			ID:          "polish",
			Name:        "Polish",
			Icon:        "🇵🇱",
			OSMTag:      "cuisine",
			OSMValues:   []string{"polish"},
			Description: "Polish restaurants and pierogi",
			SortOrder:   24,
			Popular:     false,
		},
		{
			ID:          "german",
			Name:        "German",
			Icon:        "🇩🇪",
			OSMTag:      "cuisine",
			OSMValues:   []string{"german", "bavarian"},
			Description: "German restaurants and beer halls",
			SortOrder:   25,
			Popular:     false,
		},
		{
			ID:          "irish",
			Name:        "Irish",
			Icon:        "🇮🇪",
			OSMTag:      "cuisine",
			OSMValues:   []string{"irish"},
			Description: "Irish pubs and restaurants",
			SortOrder:   26,
			Popular:     false,
		},
		{
			ID:          "british",
			Name:        "British",
			Icon:        "🇬🇧",
			OSMTag:      "cuisine",
			OSMValues:   []string{"british", "english", "fish_and_chips"},
			Description: "British pubs and fish & chips",
			SortOrder:   27,
			Popular:     false,
		},
		{
			ID:          "portuguese",
			Name:        "Portuguese",
			Icon:        "🇵🇹",
			OSMTag:      "cuisine",
			OSMValues:   []string{"portuguese"},
			Description: "Portuguese restaurants and seafood",
			SortOrder:   28,
			Popular:     false,
		},
		{
			ID:          "russian",
			Name:        "Russian",
			Icon:        "🇷🇺",
			OSMTag:      "cuisine",
			OSMValues:   []string{"russian"},
			Description: "Russian restaurants and borscht",
			SortOrder:   29,
			Popular:     false,
		},
		{
			ID:          "seafood",
			Name:        "Seafood",
			Icon:        "🦞",
			OSMTag:      "cuisine",
			OSMValues:   []string{"seafood", "fish"},
			Description: "Seafood restaurants and oyster bars",
			SortOrder:   30,
			Popular:     false,
		},
		{
			ID:          "steakhouse",
			Name:        "Steakhouse",
			Icon:        "🥩",
			OSMTag:      "cuisine",
			OSMValues:   []string{"steak", "steakhouse"},
			Description: "Steakhouses and grill houses",
			SortOrder:   31,
			Popular:     false,
		},
		{
			ID:          "vegetarian",
			Name:        "Vegetarian",
			Icon:        "🥗",
			OSMTag:      "cuisine",
			OSMValues:   []string{"vegetarian", "vegan"},
			Description: "Vegetarian and vegan restaurants",
			SortOrder:   32,
			Popular:     false,
		},
		{
			ID:          "bbq",
			Name:        "BBQ & Smokehouse",
			Icon:        "🍖",
			OSMTag:      "cuisine",
			OSMValues:   []string{"bbq", "barbecue", "smoked"},
			Description: "BBQ restaurants and smokehouses",
			SortOrder:   33,
			Popular:     false,
		},
		{
			ID:          "fusion",
			Name:        "Fusion",
			Icon:        "🌐",
			OSMTag:      "cuisine",
			OSMValues:   []string{"fusion", "international"},
			Description: "Fusion and international cuisine",
			SortOrder:   34,
			Popular:     false,
		},
		{
			ID:          "fine_dining",
			Name:        "Fine Dining",
			Icon:        "⭐",
			OSMTag:      "cuisine",
			OSMValues:   []string{"fine_dining", "gourmet"},
			Description: "Fine dining and Michelin-starred restaurants",
			SortOrder:   35,
			Popular:     false,
		},
		{
			ID:          "buffet",
			Name:        "Buffet",
			Icon:        "🍱",
			OSMTag:      "cuisine",
			OSMValues:   []string{"buffet"},
			Description: "All-you-can-eat buffets",
			SortOrder:   36,
			Popular:     false,
		},
		{
			ID:          "fast_food",
			Name:        "Fast Food",
			Icon:        "🍔",
			OSMTag:      "cuisine",
			OSMValues:   []string{"fast_food", "burger", "fried_chicken"},
			Description: "Fast food chains and quick service",
			SortOrder:   37,
			Popular:     false,
		},
		{
			ID:          "diner",
			Name:        "Diner",
			Icon:        "🥞",
			OSMTag:      "cuisine",
			OSMValues:   []string{"diner", "breakfast"},
			Description: "Diners and breakfast spots",
			SortOrder:   38,
			Popular:     false,
		},
		{
			ID:          "food_truck",
			Name:        "Food Truck",
			Icon:        "🚚",
			OSMTag:      "cuisine",
			OSMValues:   []string{"food_truck", "street_food"},
			Description: "Food trucks and mobile eateries",
			SortOrder:   39,
			Popular:     false,
		},
		{
			ID:          "other",
			Name:        "Other Cuisine",
			Icon:        "🍽️",
			OSMTag:      "cuisine",
			OSMValues:   []string{},
			Description: "Other restaurant types",
			SortOrder:   40,
			Popular:     false,
		},
	}
}
