// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jordanlanch/industrydb/ent/emailsequence"
	"github.com/jordanlanch/industrydb/ent/emailsequenceenrollment"
	"github.com/jordanlanch/industrydb/ent/emailsequencesend"
	"github.com/jordanlanch/industrydb/ent/lead"
	"github.com/jordanlanch/industrydb/ent/predicate"
	"github.com/jordanlanch/industrydb/ent/user"
)

// EmailSequenceEnrollmentUpdate is the builder for updating EmailSequenceEnrollment entities.
type EmailSequenceEnrollmentUpdate struct {
	config
	hooks    []Hook
	mutation *EmailSequenceEnrollmentMutation
}

// Where appends a list predicates to the EmailSequenceEnrollmentUpdate builder.
func (_u *EmailSequenceEnrollmentUpdate) Where(ps ...predicate.EmailSequenceEnrollment) *EmailSequenceEnrollmentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSequenceID sets the "sequence_id" field.
func (_u *EmailSequenceEnrollmentUpdate) SetSequenceID(v int) *EmailSequenceEnrollmentUpdate {
	_u.mutation.SetSequenceID(v)
	return _u
}

// SetNillableSequenceID sets the "sequence_id" field if the given value is not nil.
func (_u *EmailSequenceEnrollmentUpdate) SetNillableSequenceID(v *int) *EmailSequenceEnrollmentUpdate {
	if v != nil {
		_u.SetSequenceID(*v)
	}
	return _u
}

// SetLeadID sets the "lead_id" field.
func (_u *EmailSequenceEnrollmentUpdate) SetLeadID(v int) *EmailSequenceEnrollmentUpdate {
	_u.mutation.SetLeadID(v)
	return _u
}

// SetNillableLeadID sets the "lead_id" field if the given value is not nil.
func (_u *EmailSequenceEnrollmentUpdate) SetNillableLeadID(v *int) *EmailSequenceEnrollmentUpdate {
	if v != nil {
		_u.SetLeadID(*v)
	}
	return _u
}

// SetEnrolledByUserID sets the "enrolled_by_user_id" field.
func (_u *EmailSequenceEnrollmentUpdate) SetEnrolledByUserID(v int) *EmailSequenceEnrollmentUpdate {
	_u.mutation.SetEnrolledByUserID(v)
	return _u
}

// SetNillableEnrolledByUserID sets the "enrolled_by_user_id" field if the given value is not nil.
func (_u *EmailSequenceEnrollmentUpdate) SetNillableEnrolledByUserID(v *int) *EmailSequenceEnrollmentUpdate {
	if v != nil {
		_u.SetEnrolledByUserID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *EmailSequenceEnrollmentUpdate) SetStatus(v emailsequenceenrollment.Status) *EmailSequenceEnrollmentUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EmailSequenceEnrollmentUpdate) SetNillableStatus(v *emailsequenceenrollment.Status) *EmailSequenceEnrollmentUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCurrentStep sets the "current_step" field.
func (_u *EmailSequenceEnrollmentUpdate) SetCurrentStep(v int) *EmailSequenceEnrollmentUpdate {
	_u.mutation.ResetCurrentStep()
	_u.mutation.SetCurrentStep(v)
	return _u
}

// SetNillableCurrentStep sets the "current_step" field if the given value is not nil.
func (_u *EmailSequenceEnrollmentUpdate) SetNillableCurrentStep(v *int) *EmailSequenceEnrollmentUpdate {
	if v != nil {
		_u.SetCurrentStep(*v)
	}
	return _u
}

// AddCurrentStep adds value to the "current_step" field.
func (_u *EmailSequenceEnrollmentUpdate) AddCurrentStep(v int) *EmailSequenceEnrollmentUpdate {
	_u.mutation.AddCurrentStep(v)
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *EmailSequenceEnrollmentUpdate) SetCompletedAt(v time.Time) *EmailSequenceEnrollmentUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *EmailSequenceEnrollmentUpdate) SetNillableCompletedAt(v *time.Time) *EmailSequenceEnrollmentUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *EmailSequenceEnrollmentUpdate) ClearCompletedAt() *EmailSequenceEnrollmentUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EmailSequenceEnrollmentUpdate) SetUpdatedAt(v time.Time) *EmailSequenceEnrollmentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSequence sets the "sequence" edge to the EmailSequence entity.
func (_u *EmailSequenceEnrollmentUpdate) SetSequence(v *EmailSequence) *EmailSequenceEnrollmentUpdate {
	return _u.SetSequenceID(v.ID)
}

// SetLead sets the "lead" edge to the Lead entity.
func (_u *EmailSequenceEnrollmentUpdate) SetLead(v *Lead) *EmailSequenceEnrollmentUpdate {
	return _u.SetLeadID(v.ID)
}

// SetEnrolledByID sets the "enrolled_by" edge to the User entity by ID.
func (_u *EmailSequenceEnrollmentUpdate) SetEnrolledByID(id int) *EmailSequenceEnrollmentUpdate {
	_u.mutation.SetEnrolledByID(id)
	return _u
}

// SetEnrolledBy sets the "enrolled_by" edge to the User entity.
func (_u *EmailSequenceEnrollmentUpdate) SetEnrolledBy(v *User) *EmailSequenceEnrollmentUpdate {
	return _u.SetEnrolledByID(v.ID)
}

// AddSendIDs adds the "sends" edge to the EmailSequenceSend entity by IDs.
func (_u *EmailSequenceEnrollmentUpdate) AddSendIDs(ids ...int) *EmailSequenceEnrollmentUpdate {
	_u.mutation.AddSendIDs(ids...)
	return _u
}

// AddSends adds the "sends" edges to the EmailSequenceSend entity.
func (_u *EmailSequenceEnrollmentUpdate) AddSends(v ...*EmailSequenceSend) *EmailSequenceEnrollmentUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSendIDs(ids...)
}

// Mutation returns the EmailSequenceEnrollmentMutation object of the builder.
func (_u *EmailSequenceEnrollmentUpdate) Mutation() *EmailSequenceEnrollmentMutation {
	return _u.mutation
}

// ClearSequence clears the "sequence" edge to the EmailSequence entity.
func (_u *EmailSequenceEnrollmentUpdate) ClearSequence() *EmailSequenceEnrollmentUpdate {
	_u.mutation.ClearSequence()
	return _u
}

// ClearLead clears the "lead" edge to the Lead entity.
func (_u *EmailSequenceEnrollmentUpdate) ClearLead() *EmailSequenceEnrollmentUpdate {
	_u.mutation.ClearLead()
	return _u
}

// ClearEnrolledBy clears the "enrolled_by" edge to the User entity.
func (_u *EmailSequenceEnrollmentUpdate) ClearEnrolledBy() *EmailSequenceEnrollmentUpdate {
	_u.mutation.ClearEnrolledBy()
	return _u
}

// ClearSends clears all "sends" edges to the EmailSequenceSend entity.
func (_u *EmailSequenceEnrollmentUpdate) ClearSends() *EmailSequenceEnrollmentUpdate {
	_u.mutation.ClearSends()
	return _u
}

// RemoveSendIDs removes the "sends" edge to EmailSequenceSend entities by IDs.
func (_u *EmailSequenceEnrollmentUpdate) RemoveSendIDs(ids ...int) *EmailSequenceEnrollmentUpdate {
	_u.mutation.RemoveSendIDs(ids...)
	return _u
}

// RemoveSends removes "sends" edges to EmailSequenceSend entities.
func (_u *EmailSequenceEnrollmentUpdate) RemoveSends(v ...*EmailSequenceSend) *EmailSequenceEnrollmentUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSendIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EmailSequenceEnrollmentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EmailSequenceEnrollmentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EmailSequenceEnrollmentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EmailSequenceEnrollmentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EmailSequenceEnrollmentUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := emailsequenceenrollment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EmailSequenceEnrollmentUpdate) check() error {
	if v, ok := _u.mutation.SequenceID(); ok {
		if err := emailsequenceenrollment.SequenceIDValidator(v); err != nil {
			return &ValidationError{Name: "sequence_id", err: fmt.Errorf(`ent: validator failed for field "EmailSequenceEnrollment.sequence_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LeadID(); ok {
		if err := emailsequenceenrollment.LeadIDValidator(v); err != nil {
			return &ValidationError{Name: "lead_id", err: fmt.Errorf(`ent: validator failed for field "EmailSequenceEnrollment.lead_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EnrolledByUserID(); ok {
		if err := emailsequenceenrollment.EnrolledByUserIDValidator(v); err != nil {
			return &ValidationError{Name: "enrolled_by_user_id", err: fmt.Errorf(`ent: validator failed for field "EmailSequenceEnrollment.enrolled_by_user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := emailsequenceenrollment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "EmailSequenceEnrollment.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CurrentStep(); ok {
		if err := emailsequenceenrollment.CurrentStepValidator(v); err != nil {
			return &ValidationError{Name: "current_step", err: fmt.Errorf(`ent: validator failed for field "EmailSequenceEnrollment.current_step": %w`, err)}
		}
	}
	if _u.mutation.SequenceCleared() && len(_u.mutation.SequenceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EmailSequenceEnrollment.sequence"`)
	}
	if _u.mutation.LeadCleared() && len(_u.mutation.LeadIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EmailSequenceEnrollment.lead"`)
	}
	if _u.mutation.EnrolledByCleared() && len(_u.mutation.EnrolledByIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EmailSequenceEnrollment.enrolled_by"`)
	}
	return nil
}

func (_u *EmailSequenceEnrollmentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(emailsequenceenrollment.Table, emailsequenceenrollment.Columns, sqlgraph.NewFieldSpec(emailsequenceenrollment.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(emailsequenceenrollment.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CurrentStep(); ok {
		_spec.SetField(emailsequenceenrollment.FieldCurrentStep, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCurrentStep(); ok {
		_spec.AddField(emailsequenceenrollment.FieldCurrentStep, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(emailsequenceenrollment.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(emailsequenceenrollment.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(emailsequenceenrollment.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.SequenceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   emailsequenceenrollment.SequenceTable,
			Columns: []string{emailsequenceenrollment.SequenceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(emailsequence.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SequenceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   emailsequenceenrollment.SequenceTable,
			Columns: []string{emailsequenceenrollment.SequenceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(emailsequence.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LeadCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   emailsequenceenrollment.LeadTable,
			Columns: []string{emailsequenceenrollment.LeadColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lead.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LeadIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   emailsequenceenrollment.LeadTable,
			Columns: []string{emailsequenceenrollment.LeadColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lead.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EnrolledByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   emailsequenceenrollment.EnrolledByTable,
			Columns: []string{emailsequenceenrollment.EnrolledByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EnrolledByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   emailsequenceenrollment.EnrolledByTable,
			Columns: []string{emailsequenceenrollment.EnrolledByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SendsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   emailsequenceenrollment.SendsTable,
			Columns: []string{emailsequenceenrollment.SendsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(emailsequencesend.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSendsIDs(); len(nodes) > 0 && !_u.mutation.SendsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   emailsequenceenrollment.SendsTable,
			Columns: []string{emailsequenceenrollment.SendsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(emailsequencesend.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SendsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   emailsequenceenrollment.SendsTable,
			Columns: []string{emailsequenceenrollment.SendsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(emailsequencesend.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{emailsequenceenrollment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EmailSequenceEnrollmentUpdateOne is the builder for updating a single EmailSequenceEnrollment entity.
type EmailSequenceEnrollmentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EmailSequenceEnrollmentMutation
}

// SetSequenceID sets the "sequence_id" field.
func (_u *EmailSequenceEnrollmentUpdateOne) SetSequenceID(v int) *EmailSequenceEnrollmentUpdateOne {
	_u.mutation.SetSequenceID(v)
	return _u
}

// SetNillableSequenceID sets the "sequence_id" field if the given value is not nil.
func (_u *EmailSequenceEnrollmentUpdateOne) SetNillableSequenceID(v *int) *EmailSequenceEnrollmentUpdateOne {
	if v != nil {
		_u.SetSequenceID(*v)
	}
	return _u
}

// SetLeadID sets the "lead_id" field.
func (_u *EmailSequenceEnrollmentUpdateOne) SetLeadID(v int) *EmailSequenceEnrollmentUpdateOne {
	_u.mutation.SetLeadID(v)
	return _u
}

// SetNillableLeadID sets the "lead_id" field if the given value is not nil.
func (_u *EmailSequenceEnrollmentUpdateOne) SetNillableLeadID(v *int) *EmailSequenceEnrollmentUpdateOne {
	if v != nil {
		_u.SetLeadID(*v)
	}
	return _u
}

// SetEnrolledByUserID sets the "enrolled_by_user_id" field.
func (_u *EmailSequenceEnrollmentUpdateOne) SetEnrolledByUserID(v int) *EmailSequenceEnrollmentUpdateOne {
	_u.mutation.SetEnrolledByUserID(v)
	return _u
}

// SetNillableEnrolledByUserID sets the "enrolled_by_user_id" field if the given value is not nil.
func (_u *EmailSequenceEnrollmentUpdateOne) SetNillableEnrolledByUserID(v *int) *EmailSequenceEnrollmentUpdateOne {
	if v != nil {
		_u.SetEnrolledByUserID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *EmailSequenceEnrollmentUpdateOne) SetStatus(v emailsequenceenrollment.Status) *EmailSequenceEnrollmentUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EmailSequenceEnrollmentUpdateOne) SetNillableStatus(v *emailsequenceenrollment.Status) *EmailSequenceEnrollmentUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCurrentStep sets the "current_step" field.
func (_u *EmailSequenceEnrollmentUpdateOne) SetCurrentStep(v int) *EmailSequenceEnrollmentUpdateOne {
	_u.mutation.ResetCurrentStep()
	_u.mutation.SetCurrentStep(v)
	return _u
}

// SetNillableCurrentStep sets the "current_step" field if the given value is not nil.
func (_u *EmailSequenceEnrollmentUpdateOne) SetNillableCurrentStep(v *int) *EmailSequenceEnrollmentUpdateOne {
	if v != nil {
		_u.SetCurrentStep(*v)
	}
	return _u
}

// AddCurrentStep adds value to the "current_step" field.
func (_u *EmailSequenceEnrollmentUpdateOne) AddCurrentStep(v int) *EmailSequenceEnrollmentUpdateOne {
	_u.mutation.AddCurrentStep(v)
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *EmailSequenceEnrollmentUpdateOne) SetCompletedAt(v time.Time) *EmailSequenceEnrollmentUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *EmailSequenceEnrollmentUpdateOne) SetNillableCompletedAt(v *time.Time) *EmailSequenceEnrollmentUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *EmailSequenceEnrollmentUpdateOne) ClearCompletedAt() *EmailSequenceEnrollmentUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EmailSequenceEnrollmentUpdateOne) SetUpdatedAt(v time.Time) *EmailSequenceEnrollmentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSequence sets the "sequence" edge to the EmailSequence entity.
func (_u *EmailSequenceEnrollmentUpdateOne) SetSequence(v *EmailSequence) *EmailSequenceEnrollmentUpdateOne {
	return _u.SetSequenceID(v.ID)
}

// SetLead sets the "lead" edge to the Lead entity.
func (_u *EmailSequenceEnrollmentUpdateOne) SetLead(v *Lead) *EmailSequenceEnrollmentUpdateOne {
	return _u.SetLeadID(v.ID)
}

// SetEnrolledByID sets the "enrolled_by" edge to the User entity by ID.
func (_u *EmailSequenceEnrollmentUpdateOne) SetEnrolledByID(id int) *EmailSequenceEnrollmentUpdateOne {
	_u.mutation.SetEnrolledByID(id)
	return _u
}

// SetEnrolledBy sets the "enrolled_by" edge to the User entity.
func (_u *EmailSequenceEnrollmentUpdateOne) SetEnrolledBy(v *User) *EmailSequenceEnrollmentUpdateOne {
	return _u.SetEnrolledByID(v.ID)
}

// AddSendIDs adds the "sends" edge to the EmailSequenceSend entity by IDs.
func (_u *EmailSequenceEnrollmentUpdateOne) AddSendIDs(ids ...int) *EmailSequenceEnrollmentUpdateOne {
	_u.mutation.AddSendIDs(ids...)
	return _u
}

// AddSends adds the "sends" edges to the EmailSequenceSend entity.
func (_u *EmailSequenceEnrollmentUpdateOne) AddSends(v ...*EmailSequenceSend) *EmailSequenceEnrollmentUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSendIDs(ids...)
}

// Mutation returns the EmailSequenceEnrollmentMutation object of the builder.
func (_u *EmailSequenceEnrollmentUpdateOne) Mutation() *EmailSequenceEnrollmentMutation {
	return _u.mutation
}

// ClearSequence clears the "sequence" edge to the EmailSequence entity.
func (_u *EmailSequenceEnrollmentUpdateOne) ClearSequence() *EmailSequenceEnrollmentUpdateOne {
	_u.mutation.ClearSequence()
	return _u
}

// ClearLead clears the "lead" edge to the Lead entity.
func (_u *EmailSequenceEnrollmentUpdateOne) ClearLead() *EmailSequenceEnrollmentUpdateOne {
	_u.mutation.ClearLead()
	return _u
}

// ClearEnrolledBy clears the "enrolled_by" edge to the User entity.
func (_u *EmailSequenceEnrollmentUpdateOne) ClearEnrolledBy() *EmailSequenceEnrollmentUpdateOne {
	_u.mutation.ClearEnrolledBy()
	return _u
}

// ClearSends clears all "sends" edges to the EmailSequenceSend entity.
func (_u *EmailSequenceEnrollmentUpdateOne) ClearSends() *EmailSequenceEnrollmentUpdateOne {
	_u.mutation.ClearSends()
	return _u
}

// RemoveSendIDs removes the "sends" edge to EmailSequenceSend entities by IDs.
func (_u *EmailSequenceEnrollmentUpdateOne) RemoveSendIDs(ids ...int) *EmailSequenceEnrollmentUpdateOne {
	_u.mutation.RemoveSendIDs(ids...)
	return _u
}

// RemoveSends removes "sends" edges to EmailSequenceSend entities.
func (_u *EmailSequenceEnrollmentUpdateOne) RemoveSends(v ...*EmailSequenceSend) *EmailSequenceEnrollmentUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSendIDs(ids...)
}

// Where appends a list predicates to the EmailSequenceEnrollmentUpdate builder.
func (_u *EmailSequenceEnrollmentUpdateOne) Where(ps ...predicate.EmailSequenceEnrollment) *EmailSequenceEnrollmentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EmailSequenceEnrollmentUpdateOne) Select(field string, fields ...string) *EmailSequenceEnrollmentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EmailSequenceEnrollment entity.
func (_u *EmailSequenceEnrollmentUpdateOne) Save(ctx context.Context) (*EmailSequenceEnrollment, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EmailSequenceEnrollmentUpdateOne) SaveX(ctx context.Context) *EmailSequenceEnrollment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EmailSequenceEnrollmentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EmailSequenceEnrollmentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EmailSequenceEnrollmentUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := emailsequenceenrollment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EmailSequenceEnrollmentUpdateOne) check() error {
	if v, ok := _u.mutation.SequenceID(); ok {
		if err := emailsequenceenrollment.SequenceIDValidator(v); err != nil {
			return &ValidationError{Name: "sequence_id", err: fmt.Errorf(`ent: validator failed for field "EmailSequenceEnrollment.sequence_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LeadID(); ok {
		if err := emailsequenceenrollment.LeadIDValidator(v); err != nil {
			return &ValidationError{Name: "lead_id", err: fmt.Errorf(`ent: validator failed for field "EmailSequenceEnrollment.lead_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EnrolledByUserID(); ok {
		if err := emailsequenceenrollment.EnrolledByUserIDValidator(v); err != nil {
			return &ValidationError{Name: "enrolled_by_user_id", err: fmt.Errorf(`ent: validator failed for field "EmailSequenceEnrollment.enrolled_by_user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := emailsequenceenrollment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "EmailSequenceEnrollment.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CurrentStep(); ok {
		if err := emailsequenceenrollment.CurrentStepValidator(v); err != nil {
			return &ValidationError{Name: "current_step", err: fmt.Errorf(`ent: validator failed for field "EmailSequenceEnrollment.current_step": %w`, err)}
		}
	}
	if _u.mutation.SequenceCleared() && len(_u.mutation.SequenceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EmailSequenceEnrollment.sequence"`)
	}
	if _u.mutation.LeadCleared() && len(_u.mutation.LeadIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EmailSequenceEnrollment.lead"`)
	}
	if _u.mutation.EnrolledByCleared() && len(_u.mutation.EnrolledByIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EmailSequenceEnrollment.enrolled_by"`)
	}
	return nil
}

func (_u *EmailSequenceEnrollmentUpdateOne) sqlSave(ctx context.Context) (_node *EmailSequenceEnrollment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(emailsequenceenrollment.Table, emailsequenceenrollment.Columns, sqlgraph.NewFieldSpec(emailsequenceenrollment.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EmailSequenceEnrollment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, emailsequenceenrollment.FieldID)
		for _, f := range fields {
			if !emailsequenceenrollment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != emailsequenceenrollment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(emailsequenceenrollment.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CurrentStep(); ok {
		_spec.SetField(emailsequenceenrollment.FieldCurrentStep, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCurrentStep(); ok {
		_spec.AddField(emailsequenceenrollment.FieldCurrentStep, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(emailsequenceenrollment.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(emailsequenceenrollment.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(emailsequenceenrollment.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.SequenceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   emailsequenceenrollment.SequenceTable,
			Columns: []string{emailsequenceenrollment.SequenceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(emailsequence.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SequenceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   emailsequenceenrollment.SequenceTable,
			Columns: []string{emailsequenceenrollment.SequenceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(emailsequence.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LeadCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   emailsequenceenrollment.LeadTable,
			Columns: []string{emailsequenceenrollment.LeadColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lead.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LeadIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   emailsequenceenrollment.LeadTable,
			Columns: []string{emailsequenceenrollment.LeadColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lead.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EnrolledByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   emailsequenceenrollment.EnrolledByTable,
			Columns: []string{emailsequenceenrollment.EnrolledByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EnrolledByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   emailsequenceenrollment.EnrolledByTable,
			Columns: []string{emailsequenceenrollment.EnrolledByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SendsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   emailsequenceenrollment.SendsTable,
			Columns: []string{emailsequenceenrollment.SendsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(emailsequencesend.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSendsIDs(); len(nodes) > 0 && !_u.mutation.SendsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   emailsequenceenrollment.SendsTable,
			Columns: []string{emailsequenceenrollment.SendsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(emailsequencesend.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SendsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   emailsequenceenrollment.SendsTable,
			Columns: []string{emailsequenceenrollment.SendsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(emailsequencesend.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &EmailSequenceEnrollment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{emailsequenceenrollment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
