// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jordanlanch/industrydb/ent/emailcampaign"
	"github.com/jordanlanch/industrydb/ent/emailcampaignrecipient"
	"github.com/jordanlanch/industrydb/ent/predicate"
)

// EmailCampaignRecipientUpdate is the builder for updating EmailCampaignRecipient entities.
type EmailCampaignRecipientUpdate struct {
	config
	hooks    []Hook
	mutation *EmailCampaignRecipientMutation
}

// Where appends a list predicates to the EmailCampaignRecipientUpdate builder.
func (_u *EmailCampaignRecipientUpdate) Where(ps ...predicate.EmailCampaignRecipient) *EmailCampaignRecipientUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCampaignID sets the "campaign_id" field.
func (_u *EmailCampaignRecipientUpdate) SetCampaignID(v int) *EmailCampaignRecipientUpdate {
	_u.mutation.SetCampaignID(v)
	return _u
}

// SetNillableCampaignID sets the "campaign_id" field if the given value is not nil.
func (_u *EmailCampaignRecipientUpdate) SetNillableCampaignID(v *int) *EmailCampaignRecipientUpdate {
	if v != nil {
		_u.SetCampaignID(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *EmailCampaignRecipientUpdate) SetEmail(v string) *EmailCampaignRecipientUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *EmailCampaignRecipientUpdate) SetNillableEmail(v *string) *EmailCampaignRecipientUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *EmailCampaignRecipientUpdate) SetName(v string) *EmailCampaignRecipientUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *EmailCampaignRecipientUpdate) SetNillableName(v *string) *EmailCampaignRecipientUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *EmailCampaignRecipientUpdate) ClearName() *EmailCampaignRecipientUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetStatus sets the "status" field.
func (_u *EmailCampaignRecipientUpdate) SetStatus(v emailcampaignrecipient.Status) *EmailCampaignRecipientUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EmailCampaignRecipientUpdate) SetNillableStatus(v *emailcampaignrecipient.Status) *EmailCampaignRecipientUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSentAt sets the "sent_at" field.
func (_u *EmailCampaignRecipientUpdate) SetSentAt(v time.Time) *EmailCampaignRecipientUpdate {
	_u.mutation.SetSentAt(v)
	return _u
}

// SetNillableSentAt sets the "sent_at" field if the given value is not nil.
func (_u *EmailCampaignRecipientUpdate) SetNillableSentAt(v *time.Time) *EmailCampaignRecipientUpdate {
	if v != nil {
		_u.SetSentAt(*v)
	}
	return _u
}

// ClearSentAt clears the value of the "sent_at" field.
func (_u *EmailCampaignRecipientUpdate) ClearSentAt() *EmailCampaignRecipientUpdate {
	_u.mutation.ClearSentAt()
	return _u
}

// SetOpenedAt sets the "opened_at" field.
func (_u *EmailCampaignRecipientUpdate) SetOpenedAt(v time.Time) *EmailCampaignRecipientUpdate {
	_u.mutation.SetOpenedAt(v)
	return _u
}

// SetNillableOpenedAt sets the "opened_at" field if the given value is not nil.
func (_u *EmailCampaignRecipientUpdate) SetNillableOpenedAt(v *time.Time) *EmailCampaignRecipientUpdate {
	if v != nil {
		_u.SetOpenedAt(*v)
	}
	return _u
}

// ClearOpenedAt clears the value of the "opened_at" field.
func (_u *EmailCampaignRecipientUpdate) ClearOpenedAt() *EmailCampaignRecipientUpdate {
	_u.mutation.ClearOpenedAt()
	return _u
}

// SetClickedAt sets the "clicked_at" field.
func (_u *EmailCampaignRecipientUpdate) SetClickedAt(v time.Time) *EmailCampaignRecipientUpdate {
	_u.mutation.SetClickedAt(v)
	return _u
}

// SetNillableClickedAt sets the "clicked_at" field if the given value is not nil.
func (_u *EmailCampaignRecipientUpdate) SetNillableClickedAt(v *time.Time) *EmailCampaignRecipientUpdate {
	if v != nil {
		_u.SetClickedAt(*v)
	}
	return _u
}

// ClearClickedAt clears the value of the "clicked_at" field.
func (_u *EmailCampaignRecipientUpdate) ClearClickedAt() *EmailCampaignRecipientUpdate {
	_u.mutation.ClearClickedAt()
	return _u
}

// SetUnsubscribedAt sets the "unsubscribed_at" field.
func (_u *EmailCampaignRecipientUpdate) SetUnsubscribedAt(v time.Time) *EmailCampaignRecipientUpdate {
	_u.mutation.SetUnsubscribedAt(v)
	return _u
}

// SetNillableUnsubscribedAt sets the "unsubscribed_at" field if the given value is not nil.
func (_u *EmailCampaignRecipientUpdate) SetNillableUnsubscribedAt(v *time.Time) *EmailCampaignRecipientUpdate {
	if v != nil {
		_u.SetUnsubscribedAt(*v)
	}
	return _u
}

// ClearUnsubscribedAt clears the value of the "unsubscribed_at" field.
func (_u *EmailCampaignRecipientUpdate) ClearUnsubscribedAt() *EmailCampaignRecipientUpdate {
	_u.mutation.ClearUnsubscribedAt()
	return _u
}

// SetFailureReason sets the "failure_reason" field.
func (_u *EmailCampaignRecipientUpdate) SetFailureReason(v string) *EmailCampaignRecipientUpdate {
	_u.mutation.SetFailureReason(v)
	return _u
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (_u *EmailCampaignRecipientUpdate) SetNillableFailureReason(v *string) *EmailCampaignRecipientUpdate {
	if v != nil {
		_u.SetFailureReason(*v)
	}
	return _u
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (_u *EmailCampaignRecipientUpdate) ClearFailureReason() *EmailCampaignRecipientUpdate {
	_u.mutation.ClearFailureReason()
	return _u
}

// SetSendgridMessageID sets the "sendgrid_message_id" field.
func (_u *EmailCampaignRecipientUpdate) SetSendgridMessageID(v string) *EmailCampaignRecipientUpdate {
	_u.mutation.SetSendgridMessageID(v)
	return _u
}

// SetNillableSendgridMessageID sets the "sendgrid_message_id" field if the given value is not nil.
func (_u *EmailCampaignRecipientUpdate) SetNillableSendgridMessageID(v *string) *EmailCampaignRecipientUpdate {
	if v != nil {
		_u.SetSendgridMessageID(*v)
	}
	return _u
}

// ClearSendgridMessageID clears the value of the "sendgrid_message_id" field.
func (_u *EmailCampaignRecipientUpdate) ClearSendgridMessageID() *EmailCampaignRecipientUpdate {
	_u.mutation.ClearSendgridMessageID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EmailCampaignRecipientUpdate) SetUpdatedAt(v time.Time) *EmailCampaignRecipientUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCampaign sets the "campaign" edge to the EmailCampaign entity.
func (_u *EmailCampaignRecipientUpdate) SetCampaign(v *EmailCampaign) *EmailCampaignRecipientUpdate {
	return _u.SetCampaignID(v.ID)
}

// Mutation returns the EmailCampaignRecipientMutation object of the builder.
func (_u *EmailCampaignRecipientUpdate) Mutation() *EmailCampaignRecipientMutation {
	return _u.mutation
}

// ClearCampaign clears the "campaign" edge to the EmailCampaign entity.
func (_u *EmailCampaignRecipientUpdate) ClearCampaign() *EmailCampaignRecipientUpdate {
	_u.mutation.ClearCampaign()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EmailCampaignRecipientUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EmailCampaignRecipientUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EmailCampaignRecipientUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EmailCampaignRecipientUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EmailCampaignRecipientUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := emailcampaignrecipient.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EmailCampaignRecipientUpdate) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := emailcampaignrecipient.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "EmailCampaignRecipient.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := emailcampaignrecipient.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "EmailCampaignRecipient.status": %w`, err)}
		}
	}
	if _u.mutation.CampaignCleared() && len(_u.mutation.CampaignIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EmailCampaignRecipient.campaign"`)
	}
	return nil
}

func (_u *EmailCampaignRecipientUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(emailcampaignrecipient.Table, emailcampaignrecipient.Columns, sqlgraph.NewFieldSpec(emailcampaignrecipient.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(emailcampaignrecipient.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(emailcampaignrecipient.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(emailcampaignrecipient.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(emailcampaignrecipient.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SentAt(); ok {
		_spec.SetField(emailcampaignrecipient.FieldSentAt, field.TypeTime, value)
	}
	if _u.mutation.SentAtCleared() {
		_spec.ClearField(emailcampaignrecipient.FieldSentAt, field.TypeTime)
	}
	if value, ok := _u.mutation.OpenedAt(); ok {
		_spec.SetField(emailcampaignrecipient.FieldOpenedAt, field.TypeTime, value)
	}
	if _u.mutation.OpenedAtCleared() {
		_spec.ClearField(emailcampaignrecipient.FieldOpenedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ClickedAt(); ok {
		_spec.SetField(emailcampaignrecipient.FieldClickedAt, field.TypeTime, value)
	}
	if _u.mutation.ClickedAtCleared() {
		_spec.ClearField(emailcampaignrecipient.FieldClickedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UnsubscribedAt(); ok {
		_spec.SetField(emailcampaignrecipient.FieldUnsubscribedAt, field.TypeTime, value)
	}
	if _u.mutation.UnsubscribedAtCleared() {
		_spec.ClearField(emailcampaignrecipient.FieldUnsubscribedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FailureReason(); ok {
		_spec.SetField(emailcampaignrecipient.FieldFailureReason, field.TypeString, value)
	}
	if _u.mutation.FailureReasonCleared() {
		_spec.ClearField(emailcampaignrecipient.FieldFailureReason, field.TypeString)
	}
	if value, ok := _u.mutation.SendgridMessageID(); ok {
		_spec.SetField(emailcampaignrecipient.FieldSendgridMessageID, field.TypeString, value)
	}
	if _u.mutation.SendgridMessageIDCleared() {
		_spec.ClearField(emailcampaignrecipient.FieldSendgridMessageID, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(emailcampaignrecipient.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CampaignCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   emailcampaignrecipient.CampaignTable,
			Columns: []string{emailcampaignrecipient.CampaignColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(emailcampaign.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CampaignIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   emailcampaignrecipient.CampaignTable,
			Columns: []string{emailcampaignrecipient.CampaignColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(emailcampaign.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{emailcampaignrecipient.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EmailCampaignRecipientUpdateOne is the builder for updating a single EmailCampaignRecipient entity.
type EmailCampaignRecipientUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EmailCampaignRecipientMutation
}

// SetCampaignID sets the "campaign_id" field.
func (_u *EmailCampaignRecipientUpdateOne) SetCampaignID(v int) *EmailCampaignRecipientUpdateOne {
	_u.mutation.SetCampaignID(v)
	return _u
}

// SetNillableCampaignID sets the "campaign_id" field if the given value is not nil.
func (_u *EmailCampaignRecipientUpdateOne) SetNillableCampaignID(v *int) *EmailCampaignRecipientUpdateOne {
	if v != nil {
		_u.SetCampaignID(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *EmailCampaignRecipientUpdateOne) SetEmail(v string) *EmailCampaignRecipientUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *EmailCampaignRecipientUpdateOne) SetNillableEmail(v *string) *EmailCampaignRecipientUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *EmailCampaignRecipientUpdateOne) SetName(v string) *EmailCampaignRecipientUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *EmailCampaignRecipientUpdateOne) SetNillableName(v *string) *EmailCampaignRecipientUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *EmailCampaignRecipientUpdateOne) ClearName() *EmailCampaignRecipientUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetStatus sets the "status" field.
func (_u *EmailCampaignRecipientUpdateOne) SetStatus(v emailcampaignrecipient.Status) *EmailCampaignRecipientUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EmailCampaignRecipientUpdateOne) SetNillableStatus(v *emailcampaignrecipient.Status) *EmailCampaignRecipientUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSentAt sets the "sent_at" field.
func (_u *EmailCampaignRecipientUpdateOne) SetSentAt(v time.Time) *EmailCampaignRecipientUpdateOne {
	_u.mutation.SetSentAt(v)
	return _u
}

// SetNillableSentAt sets the "sent_at" field if the given value is not nil.
func (_u *EmailCampaignRecipientUpdateOne) SetNillableSentAt(v *time.Time) *EmailCampaignRecipientUpdateOne {
	if v != nil {
		_u.SetSentAt(*v)
	}
	return _u
}

// ClearSentAt clears the value of the "sent_at" field.
func (_u *EmailCampaignRecipientUpdateOne) ClearSentAt() *EmailCampaignRecipientUpdateOne {
	_u.mutation.ClearSentAt()
	return _u
}

// SetOpenedAt sets the "opened_at" field.
func (_u *EmailCampaignRecipientUpdateOne) SetOpenedAt(v time.Time) *EmailCampaignRecipientUpdateOne {
	_u.mutation.SetOpenedAt(v)
	return _u
}

// SetNillableOpenedAt sets the "opened_at" field if the given value is not nil.
func (_u *EmailCampaignRecipientUpdateOne) SetNillableOpenedAt(v *time.Time) *EmailCampaignRecipientUpdateOne {
	if v != nil {
		_u.SetOpenedAt(*v)
	}
	return _u
}

// ClearOpenedAt clears the value of the "opened_at" field.
func (_u *EmailCampaignRecipientUpdateOne) ClearOpenedAt() *EmailCampaignRecipientUpdateOne {
	_u.mutation.ClearOpenedAt()
	return _u
}

// SetClickedAt sets the "clicked_at" field.
func (_u *EmailCampaignRecipientUpdateOne) SetClickedAt(v time.Time) *EmailCampaignRecipientUpdateOne {
	_u.mutation.SetClickedAt(v)
	return _u
}

// SetNillableClickedAt sets the "clicked_at" field if the given value is not nil.
func (_u *EmailCampaignRecipientUpdateOne) SetNillableClickedAt(v *time.Time) *EmailCampaignRecipientUpdateOne {
	if v != nil {
		_u.SetClickedAt(*v)
	}
	return _u
}

// ClearClickedAt clears the value of the "clicked_at" field.
func (_u *EmailCampaignRecipientUpdateOne) ClearClickedAt() *EmailCampaignRecipientUpdateOne {
	_u.mutation.ClearClickedAt()
	return _u
}

// SetUnsubscribedAt sets the "unsubscribed_at" field.
func (_u *EmailCampaignRecipientUpdateOne) SetUnsubscribedAt(v time.Time) *EmailCampaignRecipientUpdateOne {
	_u.mutation.SetUnsubscribedAt(v)
	return _u
}

// SetNillableUnsubscribedAt sets the "unsubscribed_at" field if the given value is not nil.
func (_u *EmailCampaignRecipientUpdateOne) SetNillableUnsubscribedAt(v *time.Time) *EmailCampaignRecipientUpdateOne {
	if v != nil {
		_u.SetUnsubscribedAt(*v)
	}
	return _u
}

// ClearUnsubscribedAt clears the value of the "unsubscribed_at" field.
func (_u *EmailCampaignRecipientUpdateOne) ClearUnsubscribedAt() *EmailCampaignRecipientUpdateOne {
	_u.mutation.ClearUnsubscribedAt()
	return _u
}

// SetFailureReason sets the "failure_reason" field.
func (_u *EmailCampaignRecipientUpdateOne) SetFailureReason(v string) *EmailCampaignRecipientUpdateOne {
	_u.mutation.SetFailureReason(v)
	return _u
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (_u *EmailCampaignRecipientUpdateOne) SetNillableFailureReason(v *string) *EmailCampaignRecipientUpdateOne {
	if v != nil {
		_u.SetFailureReason(*v)
	}
	return _u
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (_u *EmailCampaignRecipientUpdateOne) ClearFailureReason() *EmailCampaignRecipientUpdateOne {
	_u.mutation.ClearFailureReason()
	return _u
}

// SetSendgridMessageID sets the "sendgrid_message_id" field.
func (_u *EmailCampaignRecipientUpdateOne) SetSendgridMessageID(v string) *EmailCampaignRecipientUpdateOne {
	_u.mutation.SetSendgridMessageID(v)
	return _u
}

// SetNillableSendgridMessageID sets the "sendgrid_message_id" field if the given value is not nil.
func (_u *EmailCampaignRecipientUpdateOne) SetNillableSendgridMessageID(v *string) *EmailCampaignRecipientUpdateOne {
	if v != nil {
		_u.SetSendgridMessageID(*v)
	}
	return _u
}

// ClearSendgridMessageID clears the value of the "sendgrid_message_id" field.
func (_u *EmailCampaignRecipientUpdateOne) ClearSendgridMessageID() *EmailCampaignRecipientUpdateOne {
	_u.mutation.ClearSendgridMessageID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EmailCampaignRecipientUpdateOne) SetUpdatedAt(v time.Time) *EmailCampaignRecipientUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCampaign sets the "campaign" edge to the EmailCampaign entity.
func (_u *EmailCampaignRecipientUpdateOne) SetCampaign(v *EmailCampaign) *EmailCampaignRecipientUpdateOne {
	return _u.SetCampaignID(v.ID)
}

// Mutation returns the EmailCampaignRecipientMutation object of the builder.
func (_u *EmailCampaignRecipientUpdateOne) Mutation() *EmailCampaignRecipientMutation {
	return _u.mutation
}

// ClearCampaign clears the "campaign" edge to the EmailCampaign entity.
func (_u *EmailCampaignRecipientUpdateOne) ClearCampaign() *EmailCampaignRecipientUpdateOne {
	_u.mutation.ClearCampaign()
	return _u
}

// Where appends a list predicates to the EmailCampaignRecipientUpdate builder.
func (_u *EmailCampaignRecipientUpdateOne) Where(ps ...predicate.EmailCampaignRecipient) *EmailCampaignRecipientUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EmailCampaignRecipientUpdateOne) Select(field string, fields ...string) *EmailCampaignRecipientUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EmailCampaignRecipient entity.
func (_u *EmailCampaignRecipientUpdateOne) Save(ctx context.Context) (*EmailCampaignRecipient, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EmailCampaignRecipientUpdateOne) SaveX(ctx context.Context) *EmailCampaignRecipient {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EmailCampaignRecipientUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EmailCampaignRecipientUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EmailCampaignRecipientUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := emailcampaignrecipient.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EmailCampaignRecipientUpdateOne) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := emailcampaignrecipient.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "EmailCampaignRecipient.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := emailcampaignrecipient.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "EmailCampaignRecipient.status": %w`, err)}
		}
	}
	if _u.mutation.CampaignCleared() && len(_u.mutation.CampaignIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EmailCampaignRecipient.campaign"`)
	}
	return nil
}

func (_u *EmailCampaignRecipientUpdateOne) sqlSave(ctx context.Context) (_node *EmailCampaignRecipient, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(emailcampaignrecipient.Table, emailcampaignrecipient.Columns, sqlgraph.NewFieldSpec(emailcampaignrecipient.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EmailCampaignRecipient.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, emailcampaignrecipient.FieldID)
		for _, f := range fields {
			if !emailcampaignrecipient.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != emailcampaignrecipient.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(emailcampaignrecipient.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(emailcampaignrecipient.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(emailcampaignrecipient.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(emailcampaignrecipient.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SentAt(); ok {
		_spec.SetField(emailcampaignrecipient.FieldSentAt, field.TypeTime, value)
	}
	if _u.mutation.SentAtCleared() {
		_spec.ClearField(emailcampaignrecipient.FieldSentAt, field.TypeTime)
	}
	if value, ok := _u.mutation.OpenedAt(); ok {
		_spec.SetField(emailcampaignrecipient.FieldOpenedAt, field.TypeTime, value)
	}
	if _u.mutation.OpenedAtCleared() {
		_spec.ClearField(emailcampaignrecipient.FieldOpenedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ClickedAt(); ok {
		_spec.SetField(emailcampaignrecipient.FieldClickedAt, field.TypeTime, value)
	}
	if _u.mutation.ClickedAtCleared() {
		_spec.ClearField(emailcampaignrecipient.FieldClickedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UnsubscribedAt(); ok {
		_spec.SetField(emailcampaignrecipient.FieldUnsubscribedAt, field.TypeTime, value)
	}
	if _u.mutation.UnsubscribedAtCleared() {
		_spec.ClearField(emailcampaignrecipient.FieldUnsubscribedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FailureReason(); ok {
		_spec.SetField(emailcampaignrecipient.FieldFailureReason, field.TypeString, value)
	}
	if _u.mutation.FailureReasonCleared() {
		_spec.ClearField(emailcampaignrecipient.FieldFailureReason, field.TypeString)
	}
	if value, ok := _u.mutation.SendgridMessageID(); ok {
		_spec.SetField(emailcampaignrecipient.FieldSendgridMessageID, field.TypeString, value)
	}
	if _u.mutation.SendgridMessageIDCleared() {
		_spec.ClearField(emailcampaignrecipient.FieldSendgridMessageID, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(emailcampaignrecipient.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CampaignCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   emailcampaignrecipient.CampaignTable,
			Columns: []string{emailcampaignrecipient.CampaignColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(emailcampaign.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CampaignIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   emailcampaignrecipient.CampaignTable,
			Columns: []string{emailcampaignrecipient.CampaignColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(emailcampaign.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &EmailCampaignRecipient{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{emailcampaignrecipient.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
