// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jordanlanch/industrydb/ent/organization"
	"github.com/jordanlanch/industrydb/ent/organizationmember"
	"github.com/jordanlanch/industrydb/ent/user"
)

// OrganizationMemberCreate is the builder for creating a OrganizationMember entity.
type OrganizationMemberCreate struct {
	config
	mutation *OrganizationMemberMutation
	hooks    []Hook
}

// SetOrganizationID sets the "organization_id" field.
func (_c *OrganizationMemberCreate) SetOrganizationID(v int) *OrganizationMemberCreate {
	_c.mutation.SetOrganizationID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *OrganizationMemberCreate) SetUserID(v int) *OrganizationMemberCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetRole sets the "role" field.
func (_c *OrganizationMemberCreate) SetRole(v organizationmember.Role) *OrganizationMemberCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_c *OrganizationMemberCreate) SetNillableRole(v *organizationmember.Role) *OrganizationMemberCreate {
	if v != nil {
		_c.SetRole(*v)
	}
	return _c
}

// SetInvitedByEmail sets the "invited_by_email" field.
func (_c *OrganizationMemberCreate) SetInvitedByEmail(v string) *OrganizationMemberCreate {
	_c.mutation.SetInvitedByEmail(v)
	return _c
}

// SetNillableInvitedByEmail sets the "invited_by_email" field if the given value is not nil.
func (_c *OrganizationMemberCreate) SetNillableInvitedByEmail(v *string) *OrganizationMemberCreate {
	if v != nil {
		_c.SetInvitedByEmail(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *OrganizationMemberCreate) SetStatus(v organizationmember.Status) *OrganizationMemberCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *OrganizationMemberCreate) SetNillableStatus(v *organizationmember.Status) *OrganizationMemberCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetInvitedAt sets the "invited_at" field.
func (_c *OrganizationMemberCreate) SetInvitedAt(v time.Time) *OrganizationMemberCreate {
	_c.mutation.SetInvitedAt(v)
	return _c
}

// SetNillableInvitedAt sets the "invited_at" field if the given value is not nil.
func (_c *OrganizationMemberCreate) SetNillableInvitedAt(v *time.Time) *OrganizationMemberCreate {
	if v != nil {
		_c.SetInvitedAt(*v)
	}
	return _c
}

// SetJoinedAt sets the "joined_at" field.
func (_c *OrganizationMemberCreate) SetJoinedAt(v time.Time) *OrganizationMemberCreate {
	_c.mutation.SetJoinedAt(v)
	return _c
}

// SetNillableJoinedAt sets the "joined_at" field if the given value is not nil.
func (_c *OrganizationMemberCreate) SetNillableJoinedAt(v *time.Time) *OrganizationMemberCreate {
	if v != nil {
		_c.SetJoinedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OrganizationMemberCreate) SetCreatedAt(v time.Time) *OrganizationMemberCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OrganizationMemberCreate) SetNillableCreatedAt(v *time.Time) *OrganizationMemberCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OrganizationMemberCreate) SetUpdatedAt(v time.Time) *OrganizationMemberCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OrganizationMemberCreate) SetNillableUpdatedAt(v *time.Time) *OrganizationMemberCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_c *OrganizationMemberCreate) SetOrganization(v *Organization) *OrganizationMemberCreate {
	return _c.SetOrganizationID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *OrganizationMemberCreate) SetUser(v *User) *OrganizationMemberCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the OrganizationMemberMutation object of the builder.
func (_c *OrganizationMemberCreate) Mutation() *OrganizationMemberMutation {
	return _c.mutation
}

// Save creates the OrganizationMember in the database.
func (_c *OrganizationMemberCreate) Save(ctx context.Context) (*OrganizationMember, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OrganizationMemberCreate) SaveX(ctx context.Context) *OrganizationMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrganizationMemberCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrganizationMemberCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OrganizationMemberCreate) defaults() {
	if _, ok := _c.mutation.Role(); !ok {
		v := organizationmember.DefaultRole
		_c.mutation.SetRole(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := organizationmember.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.JoinedAt(); !ok {
		v := organizationmember.DefaultJoinedAt()
		_c.mutation.SetJoinedAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := organizationmember.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := organizationmember.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OrganizationMemberCreate) check() error {
	if _, ok := _c.mutation.OrganizationID(); !ok {
		return &ValidationError{Name: "organization_id", err: errors.New(`ent: missing required field "OrganizationMember.organization_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "OrganizationMember.user_id"`)}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "OrganizationMember.role"`)}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := organizationmember.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "OrganizationMember.role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "OrganizationMember.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := organizationmember.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OrganizationMember.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.JoinedAt(); !ok {
		return &ValidationError{Name: "joined_at", err: errors.New(`ent: missing required field "OrganizationMember.joined_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OrganizationMember.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OrganizationMember.updated_at"`)}
	}
	if len(_c.mutation.OrganizationIDs()) == 0 {
		return &ValidationError{Name: "organization", err: errors.New(`ent: missing required edge "OrganizationMember.organization"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "OrganizationMember.user"`)}
	}
	return nil
}

func (_c *OrganizationMemberCreate) sqlSave(ctx context.Context) (*OrganizationMember, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OrganizationMemberCreate) createSpec() (*OrganizationMember, *sqlgraph.CreateSpec) {
	var (
		_node = &OrganizationMember{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(organizationmember.Table, sqlgraph.NewFieldSpec(organizationmember.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(organizationmember.FieldRole, field.TypeEnum, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.InvitedByEmail(); ok {
		_spec.SetField(organizationmember.FieldInvitedByEmail, field.TypeString, value)
		_node.InvitedByEmail = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(organizationmember.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.InvitedAt(); ok {
		_spec.SetField(organizationmember.FieldInvitedAt, field.TypeTime, value)
		_node.InvitedAt = &value
	}
	if value, ok := _c.mutation.JoinedAt(); ok {
		_spec.SetField(organizationmember.FieldJoinedAt, field.TypeTime, value)
		_node.JoinedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(organizationmember.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(organizationmember.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   organizationmember.OrganizationTable,
			Columns: []string{organizationmember.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OrganizationID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   organizationmember.UserTable,
			Columns: []string{organizationmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OrganizationMemberCreateBulk is the builder for creating many OrganizationMember entities in bulk.
type OrganizationMemberCreateBulk struct {
	config
	err      error
	builders []*OrganizationMemberCreate
}

// Save creates the OrganizationMember entities in the database.
func (_c *OrganizationMemberCreateBulk) Save(ctx context.Context) ([]*OrganizationMember, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OrganizationMember, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrganizationMemberMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OrganizationMemberCreateBulk) SaveX(ctx context.Context) []*OrganizationMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrganizationMemberCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrganizationMemberCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
