// Code generated by ent, DO NOT EDIT.

package competitormetric

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the competitormetric type in the database.
	Label = "competitor_metric"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCompetitorID holds the string denoting the competitor_id field in the database.
	FieldCompetitorID = "competitor_id"
	// FieldMetricType holds the string denoting the metric_type field in the database.
	FieldMetricType = "metric_type"
	// FieldMetricName holds the string denoting the metric_name field in the database.
	FieldMetricName = "metric_name"
	// FieldMetricValue holds the string denoting the metric_value field in the database.
	FieldMetricValue = "metric_value"
	// FieldNumericValue holds the string denoting the numeric_value field in the database.
	FieldNumericValue = "numeric_value"
	// FieldUnit holds the string denoting the unit field in the database.
	FieldUnit = "unit"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldRecordedAt holds the string denoting the recorded_at field in the database.
	FieldRecordedAt = "recorded_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeCompetitor holds the string denoting the competitor edge name in mutations.
	EdgeCompetitor = "competitor"
	// Table holds the table name of the competitormetric in the database.
	Table = "competitor_metrics"
	// CompetitorTable is the table that holds the competitor relation/edge.
	CompetitorTable = "competitor_metrics"
	// CompetitorInverseTable is the table name for the CompetitorProfile entity.
	// It exists in this package in order to avoid circular dependency with the "competitorprofile" package.
	CompetitorInverseTable = "competitor_profiles"
	// CompetitorColumn is the table column denoting the competitor relation/edge.
	CompetitorColumn = "competitor_id"
)

// Columns holds all SQL columns for competitormetric fields.
var Columns = []string{
	FieldID,
	FieldCompetitorID,
	FieldMetricType,
	FieldMetricName,
	FieldMetricValue,
	FieldNumericValue,
	FieldUnit,
	FieldNotes,
	FieldSource,
	FieldRecordedAt,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// MetricNameValidator is a validator for the "metric_name" field. It is called by the builders before save.
	MetricNameValidator func(string) error
	// MetricValueValidator is a validator for the "metric_value" field. It is called by the builders before save.
	MetricValueValidator func(string) error
	// UnitValidator is a validator for the "unit" field. It is called by the builders before save.
	UnitValidator func(string) error
	// DefaultRecordedAt holds the default value on creation for the "recorded_at" field.
	DefaultRecordedAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// MetricType defines the type for the "metric_type" enum field.
type MetricType string

// MetricType values.
const (
	MetricTypePricing     MetricType = "pricing"
	MetricTypeFeatures    MetricType = "features"
	MetricTypeMarketShare MetricType = "market_share"
	MetricTypeTraffic     MetricType = "traffic"
	MetricTypeEmployees   MetricType = "employees"
	MetricTypeFunding     MetricType = "funding"
	MetricTypeReviews     MetricType = "reviews"
	MetricTypeSocialMedia MetricType = "social_media"
	MetricTypeCustom      MetricType = "custom"
)

func (mt MetricType) String() string {
	return string(mt)
}

// MetricTypeValidator is a validator for the "metric_type" field enum values. It is called by the builders before save.
func MetricTypeValidator(mt MetricType) error {
	switch mt {
	case MetricTypePricing, MetricTypeFeatures, MetricTypeMarketShare, MetricTypeTraffic, MetricTypeEmployees, MetricTypeFunding, MetricTypeReviews, MetricTypeSocialMedia, MetricTypeCustom:
		return nil
	default:
		return fmt.Errorf("competitormetric: invalid enum value for metric_type field: %q", mt)
	}
}

// OrderOption defines the ordering options for the CompetitorMetric queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCompetitorID orders the results by the competitor_id field.
func ByCompetitorID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompetitorID, opts...).ToFunc()
}

// ByMetricType orders the results by the metric_type field.
func ByMetricType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetricType, opts...).ToFunc()
}

// ByMetricName orders the results by the metric_name field.
func ByMetricName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetricName, opts...).ToFunc()
}

// ByMetricValue orders the results by the metric_value field.
func ByMetricValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetricValue, opts...).ToFunc()
}

// ByNumericValue orders the results by the numeric_value field.
func ByNumericValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNumericValue, opts...).ToFunc()
}

// ByUnit orders the results by the unit field.
func ByUnit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnit, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByRecordedAt orders the results by the recorded_at field.
func ByRecordedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecordedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByCompetitorField orders the results by competitor field.
func ByCompetitorField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCompetitorStep(), sql.OrderByField(field, opts...))
	}
}
func newCompetitorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CompetitorInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CompetitorTable, CompetitorColumn),
	)
}
