// Code generated by ent, DO NOT EDIT.

package lead

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the lead type in the database.
	Label = "lead"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldIndustry holds the string denoting the industry field in the database.
	FieldIndustry = "industry"
	// FieldCountry holds the string denoting the country field in the database.
	FieldCountry = "country"
	// FieldCity holds the string denoting the city field in the database.
	FieldCity = "city"
	// FieldAddress holds the string denoting the address field in the database.
	FieldAddress = "address"
	// FieldPostalCode holds the string denoting the postal_code field in the database.
	FieldPostalCode = "postal_code"
	// FieldPhone holds the string denoting the phone field in the database.
	FieldPhone = "phone"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldWebsite holds the string denoting the website field in the database.
	FieldWebsite = "website"
	// FieldSocialMedia holds the string denoting the social_media field in the database.
	FieldSocialMedia = "social_media"
	// FieldLatitude holds the string denoting the latitude field in the database.
	FieldLatitude = "latitude"
	// FieldLongitude holds the string denoting the longitude field in the database.
	FieldLongitude = "longitude"
	// FieldVerified holds the string denoting the verified field in the database.
	FieldVerified = "verified"
	// FieldQualityScore holds the string denoting the quality_score field in the database.
	FieldQualityScore = "quality_score"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldStatusChangedAt holds the string denoting the status_changed_at field in the database.
	FieldStatusChangedAt = "status_changed_at"
	// FieldCustomFields holds the string denoting the custom_fields field in the database.
	FieldCustomFields = "custom_fields"
	// FieldOsmID holds the string denoting the osm_id field in the database.
	FieldOsmID = "osm_id"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldSubNiche holds the string denoting the sub_niche field in the database.
	FieldSubNiche = "sub_niche"
	// FieldSpecialties holds the string denoting the specialties field in the database.
	FieldSpecialties = "specialties"
	// FieldCuisineType holds the string denoting the cuisine_type field in the database.
	FieldCuisineType = "cuisine_type"
	// FieldSportType holds the string denoting the sport_type field in the database.
	FieldSportType = "sport_type"
	// FieldTattooStyle holds the string denoting the tattoo_style field in the database.
	FieldTattooStyle = "tattoo_style"
	// FieldCompanyDescription holds the string denoting the company_description field in the database.
	FieldCompanyDescription = "company_description"
	// FieldEmployeeCount holds the string denoting the employee_count field in the database.
	FieldEmployeeCount = "employee_count"
	// FieldCompanyRevenue holds the string denoting the company_revenue field in the database.
	FieldCompanyRevenue = "company_revenue"
	// FieldLinkedinURL holds the string denoting the linkedin_url field in the database.
	FieldLinkedinURL = "linkedin_url"
	// FieldTwitterURL holds the string denoting the twitter_url field in the database.
	FieldTwitterURL = "twitter_url"
	// FieldFacebookURL holds the string denoting the facebook_url field in the database.
	FieldFacebookURL = "facebook_url"
	// FieldIsEnriched holds the string denoting the is_enriched field in the database.
	FieldIsEnriched = "is_enriched"
	// FieldEnrichedAt holds the string denoting the enriched_at field in the database.
	FieldEnrichedAt = "enriched_at"
	// FieldEmailValidated holds the string denoting the email_validated field in the database.
	FieldEmailValidated = "email_validated"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeNotes holds the string denoting the notes edge name in mutations.
	EdgeNotes = "notes"
	// EdgeStatusHistory holds the string denoting the status_history edge name in mutations.
	EdgeStatusHistory = "status_history"
	// EdgeAssignments holds the string denoting the assignments edge name in mutations.
	EdgeAssignments = "assignments"
	// EdgeEmailSequenceEnrollments holds the string denoting the email_sequence_enrollments edge name in mutations.
	EdgeEmailSequenceEnrollments = "email_sequence_enrollments"
	// EdgeEmailSequenceSends holds the string denoting the email_sequence_sends edge name in mutations.
	EdgeEmailSequenceSends = "email_sequence_sends"
	// EdgeTerritory holds the string denoting the territory edge name in mutations.
	EdgeTerritory = "territory"
	// EdgeSmsMessages holds the string denoting the sms_messages edge name in mutations.
	EdgeSmsMessages = "sms_messages"
	// EdgeCallLogs holds the string denoting the call_logs edge name in mutations.
	EdgeCallLogs = "call_logs"
	// EdgeRecommendations holds the string denoting the recommendations edge name in mutations.
	EdgeRecommendations = "recommendations"
	// Table holds the table name of the lead in the database.
	Table = "leads"
	// NotesTable is the table that holds the notes relation/edge.
	NotesTable = "lead_notes"
	// NotesInverseTable is the table name for the LeadNote entity.
	// It exists in this package in order to avoid circular dependency with the "leadnote" package.
	NotesInverseTable = "lead_notes"
	// NotesColumn is the table column denoting the notes relation/edge.
	NotesColumn = "lead_id"
	// StatusHistoryTable is the table that holds the status_history relation/edge.
	StatusHistoryTable = "lead_status_histories"
	// StatusHistoryInverseTable is the table name for the LeadStatusHistory entity.
	// It exists in this package in order to avoid circular dependency with the "leadstatushistory" package.
	StatusHistoryInverseTable = "lead_status_histories"
	// StatusHistoryColumn is the table column denoting the status_history relation/edge.
	StatusHistoryColumn = "lead_id"
	// AssignmentsTable is the table that holds the assignments relation/edge.
	AssignmentsTable = "lead_assignments"
	// AssignmentsInverseTable is the table name for the LeadAssignment entity.
	// It exists in this package in order to avoid circular dependency with the "leadassignment" package.
	AssignmentsInverseTable = "lead_assignments"
	// AssignmentsColumn is the table column denoting the assignments relation/edge.
	AssignmentsColumn = "lead_id"
	// EmailSequenceEnrollmentsTable is the table that holds the email_sequence_enrollments relation/edge.
	EmailSequenceEnrollmentsTable = "email_sequence_enrollments"
	// EmailSequenceEnrollmentsInverseTable is the table name for the EmailSequenceEnrollment entity.
	// It exists in this package in order to avoid circular dependency with the "emailsequenceenrollment" package.
	EmailSequenceEnrollmentsInverseTable = "email_sequence_enrollments"
	// EmailSequenceEnrollmentsColumn is the table column denoting the email_sequence_enrollments relation/edge.
	EmailSequenceEnrollmentsColumn = "lead_id"
	// EmailSequenceSendsTable is the table that holds the email_sequence_sends relation/edge.
	EmailSequenceSendsTable = "email_sequence_sends"
	// EmailSequenceSendsInverseTable is the table name for the EmailSequenceSend entity.
	// It exists in this package in order to avoid circular dependency with the "emailsequencesend" package.
	EmailSequenceSendsInverseTable = "email_sequence_sends"
	// EmailSequenceSendsColumn is the table column denoting the email_sequence_sends relation/edge.
	EmailSequenceSendsColumn = "lead_id"
	// TerritoryTable is the table that holds the territory relation/edge.
	TerritoryTable = "leads"
	// TerritoryInverseTable is the table name for the Territory entity.
	// It exists in this package in order to avoid circular dependency with the "territory" package.
	TerritoryInverseTable = "territories"
	// TerritoryColumn is the table column denoting the territory relation/edge.
	TerritoryColumn = "territory_leads"
	// SmsMessagesTable is the table that holds the sms_messages relation/edge.
	SmsMessagesTable = "sms_messages"
	// SmsMessagesInverseTable is the table name for the SMSMessage entity.
	// It exists in this package in order to avoid circular dependency with the "smsmessage" package.
	SmsMessagesInverseTable = "sms_messages"
	// SmsMessagesColumn is the table column denoting the sms_messages relation/edge.
	SmsMessagesColumn = "lead_id"
	// CallLogsTable is the table that holds the call_logs relation/edge.
	CallLogsTable = "call_logs"
	// CallLogsInverseTable is the table name for the CallLog entity.
	// It exists in this package in order to avoid circular dependency with the "calllog" package.
	CallLogsInverseTable = "call_logs"
	// CallLogsColumn is the table column denoting the call_logs relation/edge.
	CallLogsColumn = "lead_id"
	// RecommendationsTable is the table that holds the recommendations relation/edge.
	RecommendationsTable = "lead_recommendations"
	// RecommendationsInverseTable is the table name for the LeadRecommendation entity.
	// It exists in this package in order to avoid circular dependency with the "leadrecommendation" package.
	RecommendationsInverseTable = "lead_recommendations"
	// RecommendationsColumn is the table column denoting the recommendations relation/edge.
	RecommendationsColumn = "lead_id"
)

// Columns holds all SQL columns for lead fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldIndustry,
	FieldCountry,
	FieldCity,
	FieldAddress,
	FieldPostalCode,
	FieldPhone,
	FieldEmail,
	FieldWebsite,
	FieldSocialMedia,
	FieldLatitude,
	FieldLongitude,
	FieldVerified,
	FieldQualityScore,
	FieldStatus,
	FieldStatusChangedAt,
	FieldCustomFields,
	FieldOsmID,
	FieldMetadata,
	FieldSubNiche,
	FieldSpecialties,
	FieldCuisineType,
	FieldSportType,
	FieldTattooStyle,
	FieldCompanyDescription,
	FieldEmployeeCount,
	FieldCompanyRevenue,
	FieldLinkedinURL,
	FieldTwitterURL,
	FieldFacebookURL,
	FieldIsEnriched,
	FieldEnrichedAt,
	FieldEmailValidated,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "leads"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"territory_leads",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// CountryValidator is a validator for the "country" field. It is called by the builders before save.
	CountryValidator func(string) error
	// CityValidator is a validator for the "city" field. It is called by the builders before save.
	CityValidator func(string) error
	// DefaultVerified holds the default value on creation for the "verified" field.
	DefaultVerified bool
	// DefaultQualityScore holds the default value on creation for the "quality_score" field.
	DefaultQualityScore int
	// QualityScoreValidator is a validator for the "quality_score" field. It is called by the builders before save.
	QualityScoreValidator func(int) error
	// DefaultStatusChangedAt holds the default value on creation for the "status_changed_at" field.
	DefaultStatusChangedAt func() time.Time
	// DefaultIsEnriched holds the default value on creation for the "is_enriched" field.
	DefaultIsEnriched bool
	// DefaultEmailValidated holds the default value on creation for the "email_validated" field.
	DefaultEmailValidated bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Industry defines the type for the "industry" enum field.
type Industry string

// Industry values.
const (
	IndustryTattoo           Industry = "tattoo"
	IndustryBeauty           Industry = "beauty"
	IndustryBarber           Industry = "barber"
	IndustrySpa              Industry = "spa"
	IndustryNailSalon        Industry = "nail_salon"
	IndustryHairSalon        Industry = "hair_salon"
	IndustryTanningSalon     Industry = "tanning_salon"
	IndustryCosmetics        Industry = "cosmetics"
	IndustryPerfumery        Industry = "perfumery"
	IndustryWaxingSalon      Industry = "waxing_salon"
	IndustryGym              Industry = "gym"
	IndustryDentist          Industry = "dentist"
	IndustryPharmacy         Industry = "pharmacy"
	IndustryMassage          Industry = "massage"
	IndustryChiropractor     Industry = "chiropractor"
	IndustryOptician         Industry = "optician"
	IndustryClinic           Industry = "clinic"
	IndustryHospital         Industry = "hospital"
	IndustryVeterinary       Industry = "veterinary"
	IndustryYogaStudio       Industry = "yoga_studio"
	IndustryPilatesStudio    Industry = "pilates_studio"
	IndustryPhysicalTherapy  Industry = "physical_therapy"
	IndustryRestaurant       Industry = "restaurant"
	IndustryCafe             Industry = "cafe"
	IndustryBar              Industry = "bar"
	IndustryBakery           Industry = "bakery"
	IndustryFastFood         Industry = "fast_food"
	IndustryIceCream         Industry = "ice_cream"
	IndustryJuiceBar         Industry = "juice_bar"
	IndustryPizza            Industry = "pizza"
	IndustrySushi            Industry = "sushi"
	IndustryBrewery          Industry = "brewery"
	IndustryWinery           Industry = "winery"
	IndustryFoodTruck        Industry = "food_truck"
	IndustryCatering         Industry = "catering"
	IndustryDeli             Industry = "deli"
	IndustryCarRepair        Industry = "car_repair"
	IndustryCarWash          Industry = "car_wash"
	IndustryCarDealer        Industry = "car_dealer"
	IndustryTireShop         Industry = "tire_shop"
	IndustryAutoParts        Industry = "auto_parts"
	IndustryGasStation       Industry = "gas_station"
	IndustryMotorcycleDealer Industry = "motorcycle_dealer"
	IndustryRvDealer         Industry = "rv_dealer"
	IndustryClothing         Industry = "clothing"
	IndustryConvenience      Industry = "convenience"
	IndustryFlorist          Industry = "florist"
	IndustryBookstore        Industry = "bookstore"
	IndustryElectronics      Industry = "electronics"
	IndustryFurniture        Industry = "furniture"
	IndustryHardware         Industry = "hardware"
	IndustryJewelry          Industry = "jewelry"
	IndustryGiftShop         Industry = "gift_shop"
	IndustryToyStore         Industry = "toy_store"
	IndustryPetStore         Industry = "pet_store"
	IndustryBicycleShop      Industry = "bicycle_shop"
	IndustrySportingGoods    Industry = "sporting_goods"
	IndustryMusicStore       Industry = "music_store"
	IndustryArtSupply        Industry = "art_supply"
	IndustryStationery       Industry = "stationery"
	IndustryGardenCenter     Industry = "garden_center"
	IndustryLawyer           Industry = "lawyer"
	IndustryAccountant       Industry = "accountant"
	IndustryRealEstate       Industry = "real_estate"
	IndustryInsurance        Industry = "insurance"
	IndustryFinancialAdvisor Industry = "financial_advisor"
	IndustryNotary           Industry = "notary"
	IndustryTaxService       Industry = "tax_service"
	IndustryMarketingAgency  Industry = "marketing_agency"
	IndustryPhotography      Industry = "photography"
	IndustryPrinting         Industry = "printing"
	IndustryEventPlanning    Industry = "event_planning"
	IndustryTravelAgency     Industry = "travel_agency"
	IndustryHotel            Industry = "hotel"
	IndustryMotel            Industry = "motel"
	IndustryHostel           Industry = "hostel"
	IndustryBedBreakfast     Industry = "bed_breakfast"
	IndustryVacationRental   Industry = "vacation_rental"
	IndustryCampground       Industry = "campground"
	IndustryRvPark           Industry = "rv_park"
	IndustryResort           Industry = "resort"
	IndustryPlumber          Industry = "plumber"
	IndustryElectrician      Industry = "electrician"
	IndustryHvac             Industry = "hvac"
	IndustryLocksmith        Industry = "locksmith"
	IndustryRoofing          Industry = "roofing"
	IndustryPainting         Industry = "painting"
	IndustryCleaning         Industry = "cleaning"
	IndustryLandscaping      Industry = "landscaping"
	IndustryPestControl      Industry = "pest_control"
)

func (i Industry) String() string {
	return string(i)
}

// IndustryValidator is a validator for the "industry" field enum values. It is called by the builders before save.
func IndustryValidator(i Industry) error {
	switch i {
	case IndustryTattoo, IndustryBeauty, IndustryBarber, IndustrySpa, IndustryNailSalon, IndustryHairSalon, IndustryTanningSalon, IndustryCosmetics, IndustryPerfumery, IndustryWaxingSalon, IndustryGym, IndustryDentist, IndustryPharmacy, IndustryMassage, IndustryChiropractor, IndustryOptician, IndustryClinic, IndustryHospital, IndustryVeterinary, IndustryYogaStudio, IndustryPilatesStudio, IndustryPhysicalTherapy, IndustryRestaurant, IndustryCafe, IndustryBar, IndustryBakery, IndustryFastFood, IndustryIceCream, IndustryJuiceBar, IndustryPizza, IndustrySushi, IndustryBrewery, IndustryWinery, IndustryFoodTruck, IndustryCatering, IndustryDeli, IndustryCarRepair, IndustryCarWash, IndustryCarDealer, IndustryTireShop, IndustryAutoParts, IndustryGasStation, IndustryMotorcycleDealer, IndustryRvDealer, IndustryClothing, IndustryConvenience, IndustryFlorist, IndustryBookstore, IndustryElectronics, IndustryFurniture, IndustryHardware, IndustryJewelry, IndustryGiftShop, IndustryToyStore, IndustryPetStore, IndustryBicycleShop, IndustrySportingGoods, IndustryMusicStore, IndustryArtSupply, IndustryStationery, IndustryGardenCenter, IndustryLawyer, IndustryAccountant, IndustryRealEstate, IndustryInsurance, IndustryFinancialAdvisor, IndustryNotary, IndustryTaxService, IndustryMarketingAgency, IndustryPhotography, IndustryPrinting, IndustryEventPlanning, IndustryTravelAgency, IndustryHotel, IndustryMotel, IndustryHostel, IndustryBedBreakfast, IndustryVacationRental, IndustryCampground, IndustryRvPark, IndustryResort, IndustryPlumber, IndustryElectrician, IndustryHvac, IndustryLocksmith, IndustryRoofing, IndustryPainting, IndustryCleaning, IndustryLandscaping, IndustryPestControl:
		return nil
	default:
		return fmt.Errorf("lead: invalid enum value for industry field: %q", i)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusNew is the default value of the Status enum.
const DefaultStatus = StatusNew

// Status values.
const (
	StatusNew         Status = "new"
	StatusContacted   Status = "contacted"
	StatusQualified   Status = "qualified"
	StatusNegotiating Status = "negotiating"
	StatusWon         Status = "won"
	StatusLost        Status = "lost"
	StatusArchived    Status = "archived"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusNew, StatusContacted, StatusQualified, StatusNegotiating, StatusWon, StatusLost, StatusArchived:
		return nil
	default:
		return fmt.Errorf("lead: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Lead queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByIndustry orders the results by the industry field.
func ByIndustry(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIndustry, opts...).ToFunc()
}

// ByCountry orders the results by the country field.
func ByCountry(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCountry, opts...).ToFunc()
}

// ByCity orders the results by the city field.
func ByCity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCity, opts...).ToFunc()
}

// ByAddress orders the results by the address field.
func ByAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAddress, opts...).ToFunc()
}

// ByPostalCode orders the results by the postal_code field.
func ByPostalCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPostalCode, opts...).ToFunc()
}

// ByPhone orders the results by the phone field.
func ByPhone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhone, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByWebsite orders the results by the website field.
func ByWebsite(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWebsite, opts...).ToFunc()
}

// ByLatitude orders the results by the latitude field.
func ByLatitude(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLatitude, opts...).ToFunc()
}

// ByLongitude orders the results by the longitude field.
func ByLongitude(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLongitude, opts...).ToFunc()
}

// ByVerified orders the results by the verified field.
func ByVerified(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVerified, opts...).ToFunc()
}

// ByQualityScore orders the results by the quality_score field.
func ByQualityScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQualityScore, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByStatusChangedAt orders the results by the status_changed_at field.
func ByStatusChangedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatusChangedAt, opts...).ToFunc()
}

// ByOsmID orders the results by the osm_id field.
func ByOsmID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOsmID, opts...).ToFunc()
}

// BySubNiche orders the results by the sub_niche field.
func BySubNiche(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubNiche, opts...).ToFunc()
}

// ByCuisineType orders the results by the cuisine_type field.
func ByCuisineType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCuisineType, opts...).ToFunc()
}

// BySportType orders the results by the sport_type field.
func BySportType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSportType, opts...).ToFunc()
}

// ByTattooStyle orders the results by the tattoo_style field.
func ByTattooStyle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTattooStyle, opts...).ToFunc()
}

// ByCompanyDescription orders the results by the company_description field.
func ByCompanyDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompanyDescription, opts...).ToFunc()
}

// ByEmployeeCount orders the results by the employee_count field.
func ByEmployeeCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmployeeCount, opts...).ToFunc()
}

// ByCompanyRevenue orders the results by the company_revenue field.
func ByCompanyRevenue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompanyRevenue, opts...).ToFunc()
}

// ByLinkedinURL orders the results by the linkedin_url field.
func ByLinkedinURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLinkedinURL, opts...).ToFunc()
}

// ByTwitterURL orders the results by the twitter_url field.
func ByTwitterURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTwitterURL, opts...).ToFunc()
}

// ByFacebookURL orders the results by the facebook_url field.
func ByFacebookURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFacebookURL, opts...).ToFunc()
}

// ByIsEnriched orders the results by the is_enriched field.
func ByIsEnriched(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsEnriched, opts...).ToFunc()
}

// ByEnrichedAt orders the results by the enriched_at field.
func ByEnrichedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnrichedAt, opts...).ToFunc()
}

// ByEmailValidated orders the results by the email_validated field.
func ByEmailValidated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmailValidated, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByNotesCount orders the results by notes count.
func ByNotesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newNotesStep(), opts...)
	}
}

// ByNotes orders the results by notes terms.
func ByNotes(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNotesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByStatusHistoryCount orders the results by status_history count.
func ByStatusHistoryCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newStatusHistoryStep(), opts...)
	}
}

// ByStatusHistory orders the results by status_history terms.
func ByStatusHistory(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStatusHistoryStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAssignmentsCount orders the results by assignments count.
func ByAssignmentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAssignmentsStep(), opts...)
	}
}

// ByAssignments orders the results by assignments terms.
func ByAssignments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAssignmentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByEmailSequenceEnrollmentsCount orders the results by email_sequence_enrollments count.
func ByEmailSequenceEnrollmentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEmailSequenceEnrollmentsStep(), opts...)
	}
}

// ByEmailSequenceEnrollments orders the results by email_sequence_enrollments terms.
func ByEmailSequenceEnrollments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEmailSequenceEnrollmentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByEmailSequenceSendsCount orders the results by email_sequence_sends count.
func ByEmailSequenceSendsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEmailSequenceSendsStep(), opts...)
	}
}

// ByEmailSequenceSends orders the results by email_sequence_sends terms.
func ByEmailSequenceSends(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEmailSequenceSendsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTerritoryField orders the results by territory field.
func ByTerritoryField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTerritoryStep(), sql.OrderByField(field, opts...))
	}
}

// BySmsMessagesCount orders the results by sms_messages count.
func BySmsMessagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSmsMessagesStep(), opts...)
	}
}

// BySmsMessages orders the results by sms_messages terms.
func BySmsMessages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSmsMessagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCallLogsCount orders the results by call_logs count.
func ByCallLogsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCallLogsStep(), opts...)
	}
}

// ByCallLogs orders the results by call_logs terms.
func ByCallLogs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCallLogsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByRecommendationsCount orders the results by recommendations count.
func ByRecommendationsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRecommendationsStep(), opts...)
	}
}

// ByRecommendations orders the results by recommendations terms.
func ByRecommendations(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRecommendationsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newNotesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(NotesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, NotesTable, NotesColumn),
	)
}
func newStatusHistoryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StatusHistoryInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, StatusHistoryTable, StatusHistoryColumn),
	)
}
func newAssignmentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AssignmentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AssignmentsTable, AssignmentsColumn),
	)
}
func newEmailSequenceEnrollmentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EmailSequenceEnrollmentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, EmailSequenceEnrollmentsTable, EmailSequenceEnrollmentsColumn),
	)
}
func newEmailSequenceSendsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EmailSequenceSendsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, EmailSequenceSendsTable, EmailSequenceSendsColumn),
	)
}
func newTerritoryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TerritoryInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TerritoryTable, TerritoryColumn),
	)
}
func newSmsMessagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SmsMessagesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SmsMessagesTable, SmsMessagesColumn),
	)
}
func newCallLogsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CallLogsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CallLogsTable, CallLogsColumn),
	)
}
func newRecommendationsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RecommendationsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RecommendationsTable, RecommendationsColumn),
	)
}
