-- Create "industries" table
CREATE TABLE "industries" (
  "id" character varying NOT NULL,
  "name" character varying NOT NULL,
  "category" character varying NOT NULL,
  "icon" character varying NULL,
  "osm_primary_tag" character varying NOT NULL,
  "osm_additional_tags" jsonb NULL,
  "description" character varying NULL,
  "active" boolean NOT NULL DEFAULT true,
  "sort_order" bigint NOT NULL DEFAULT 0,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "industry_active" to table: "industries"
CREATE INDEX "industry_active" ON "industries" ("active");
-- Create index "industry_category" to table: "industries"
CREATE INDEX "industry_category" ON "industries" ("category");
-- Create index "industry_sort_order" to table: "industries"
CREATE INDEX "industry_sort_order" ON "industries" ("sort_order");
-- Create "users" table
CREATE TABLE "users" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "email" character varying NOT NULL,
  "password_hash" character varying NOT NULL,
  "name" character varying NOT NULL,
  "subscription_tier" character varying NOT NULL DEFAULT 'free',
  "role" character varying NOT NULL DEFAULT 'user',
  "usage_count" bigint NOT NULL DEFAULT 0,
  "usage_limit" bigint NOT NULL DEFAULT 50,
  "last_reset_at" timestamptz NOT NULL,
  "last_login_at" timestamptz NULL,
  "email_verified" boolean NOT NULL DEFAULT false,
  "email_verification_token" character varying NULL,
  "email_verification_token_expires_at" timestamptz NULL,
  "email_verified_at" timestamptz NULL,
  "accepted_terms_at" timestamptz NULL,
  "onboarding_completed" boolean NOT NULL DEFAULT false,
  "totp_enabled" boolean NOT NULL DEFAULT false,
  "totp_secret" character varying NULL,
  "oauth_provider" character varying NULL,
  "oauth_id" character varying NULL,
  "stripe_customer_id" character varying NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "deleted_at" timestamptz NULL,
  "onboarding_step" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id")
);
-- Create index "user_created_at" to table: "users"
CREATE INDEX "user_created_at" ON "users" ("created_at");
-- Create index "user_email" to table: "users"
CREATE UNIQUE INDEX "user_email" ON "users" ("email");
-- Create index "user_stripe_customer_id" to table: "users"
CREATE INDEX "user_stripe_customer_id" ON "users" ("stripe_customer_id");
-- Create index "user_subscription_tier" to table: "users"
CREATE INDEX "user_subscription_tier" ON "users" ("subscription_tier");
-- Create index "users_email_key" to table: "users"
CREATE UNIQUE INDEX "users_email_key" ON "users" ("email");
-- Create "affiliates" table
CREATE TABLE "affiliates" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "affiliate_code" character varying NOT NULL,
  "status" character varying NOT NULL DEFAULT 'pending',
  "commission_rate" double precision NOT NULL DEFAULT 0.1,
  "total_earnings" double precision NOT NULL DEFAULT 0,
  "pending_earnings" double precision NOT NULL DEFAULT 0,
  "paid_earnings" double precision NOT NULL DEFAULT 0,
  "total_clicks" bigint NOT NULL DEFAULT 0,
  "total_conversions" bigint NOT NULL DEFAULT 0,
  "payment_method" character varying NULL,
  "payment_details" character varying NULL,
  "approved_at" timestamptz NULL,
  "last_payout_at" timestamptz NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "affiliates_users_affiliate" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "affiliate_affiliate_code" to table: "affiliates"
CREATE UNIQUE INDEX "affiliate_affiliate_code" ON "affiliates" ("affiliate_code");
-- Create index "affiliate_status" to table: "affiliates"
CREATE INDEX "affiliate_status" ON "affiliates" ("status");
-- Create index "affiliate_total_earnings" to table: "affiliates"
CREATE INDEX "affiliate_total_earnings" ON "affiliates" ("total_earnings");
-- Create index "affiliate_user_id" to table: "affiliates"
CREATE UNIQUE INDEX "affiliate_user_id" ON "affiliates" ("user_id");
-- Create index "affiliates_affiliate_code_key" to table: "affiliates"
CREATE UNIQUE INDEX "affiliates_affiliate_code_key" ON "affiliates" ("affiliate_code");
-- Create index "affiliates_user_id_key" to table: "affiliates"
CREATE UNIQUE INDEX "affiliates_user_id_key" ON "affiliates" ("user_id");
-- Create "affiliate_clicks" table
CREATE TABLE "affiliate_clicks" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "ip_address" character varying NULL,
  "user_agent" character varying NULL,
  "referrer" character varying NULL,
  "landing_page" character varying NULL,
  "utm_source" character varying NULL,
  "utm_medium" character varying NULL,
  "utm_campaign" character varying NULL,
  "converted" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL,
  "affiliate_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "affiliate_clicks_affiliates_clicks" FOREIGN KEY ("affiliate_id") REFERENCES "affiliates" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "affiliateclick_affiliate_id" to table: "affiliate_clicks"
CREATE INDEX "affiliateclick_affiliate_id" ON "affiliate_clicks" ("affiliate_id");
-- Create index "affiliateclick_converted" to table: "affiliate_clicks"
CREATE INDEX "affiliateclick_converted" ON "affiliate_clicks" ("converted");
-- Create index "affiliateclick_created_at" to table: "affiliate_clicks"
CREATE INDEX "affiliateclick_created_at" ON "affiliate_clicks" ("created_at");
-- Create index "affiliateclick_ip_address" to table: "affiliate_clicks"
CREATE INDEX "affiliateclick_ip_address" ON "affiliate_clicks" ("ip_address");
-- Create "affiliate_conversions" table
CREATE TABLE "affiliate_conversions" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "conversion_type" character varying NOT NULL,
  "order_value" double precision NOT NULL DEFAULT 0,
  "commission_amount" double precision NOT NULL,
  "commission_rate" double precision NOT NULL,
  "status" character varying NOT NULL DEFAULT 'pending',
  "rejection_reason" character varying NULL,
  "approved_at" timestamptz NULL,
  "paid_at" timestamptz NULL,
  "created_at" timestamptz NOT NULL,
  "affiliate_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "affiliate_conversions_affiliates_conversions" FOREIGN KEY ("affiliate_id") REFERENCES "affiliates" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "affiliate_conversions_users_affiliate_conversions" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "affiliateconversion_affiliate_id" to table: "affiliate_conversions"
CREATE INDEX "affiliateconversion_affiliate_id" ON "affiliate_conversions" ("affiliate_id");
-- Create index "affiliateconversion_conversion_type" to table: "affiliate_conversions"
CREATE INDEX "affiliateconversion_conversion_type" ON "affiliate_conversions" ("conversion_type");
-- Create index "affiliateconversion_created_at" to table: "affiliate_conversions"
CREATE INDEX "affiliateconversion_created_at" ON "affiliate_conversions" ("created_at");
-- Create index "affiliateconversion_status" to table: "affiliate_conversions"
CREATE INDEX "affiliateconversion_status" ON "affiliate_conversions" ("status");
-- Create index "affiliateconversion_user_id" to table: "affiliate_conversions"
CREATE INDEX "affiliateconversion_user_id" ON "affiliate_conversions" ("user_id");
-- Create "api_keys" table
CREATE TABLE "api_keys" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "key_hash" character varying NOT NULL,
  "name" character varying NOT NULL,
  "prefix" character varying NOT NULL,
  "last_used_at" timestamptz NULL,
  "usage_count" bigint NOT NULL DEFAULT 0,
  "revoked" boolean NOT NULL DEFAULT false,
  "revoked_at" timestamptz NULL,
  "expires_at" timestamptz NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "api_keys_users_api_keys" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "api_keys_key_hash_key" to table: "api_keys"
CREATE UNIQUE INDEX "api_keys_key_hash_key" ON "api_keys" ("key_hash");
-- Create index "apikey_created_at" to table: "api_keys"
CREATE INDEX "apikey_created_at" ON "api_keys" ("created_at");
-- Create index "apikey_key_hash" to table: "api_keys"
CREATE UNIQUE INDEX "apikey_key_hash" ON "api_keys" ("key_hash");
-- Create index "apikey_revoked" to table: "api_keys"
CREATE INDEX "apikey_revoked" ON "api_keys" ("revoked");
-- Create index "apikey_user_id" to table: "api_keys"
CREATE INDEX "apikey_user_id" ON "api_keys" ("user_id");
-- Create "audit_logs" table
CREATE TABLE "audit_logs" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "action" character varying NOT NULL,
  "resource_type" character varying NULL,
  "resource_id" character varying NULL,
  "ip_address" character varying NULL,
  "user_agent" character varying NULL,
  "metadata" jsonb NULL,
  "severity" character varying NOT NULL DEFAULT 'info',
  "description" character varying NULL,
  "created_at" timestamptz NOT NULL,
  "user_id" bigint NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "audit_logs_users_audit_logs" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create index "auditlog_action" to table: "audit_logs"
CREATE INDEX "auditlog_action" ON "audit_logs" ("action");
-- Create index "auditlog_created_at" to table: "audit_logs"
CREATE INDEX "auditlog_created_at" ON "audit_logs" ("created_at");
-- Create index "auditlog_resource_type_resource_id" to table: "audit_logs"
CREATE INDEX "auditlog_resource_type_resource_id" ON "audit_logs" ("resource_type", "resource_id");
-- Create index "auditlog_severity" to table: "audit_logs"
CREATE INDEX "auditlog_severity" ON "audit_logs" ("severity");
-- Create index "auditlog_user_id" to table: "audit_logs"
CREATE INDEX "auditlog_user_id" ON "audit_logs" ("user_id");
-- Create "territories" table
CREATE TABLE "territories" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "description" text NULL,
  "countries" jsonb NULL,
  "regions" jsonb NULL,
  "cities" jsonb NULL,
  "industries" jsonb NULL,
  "active" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by_user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "territories_users_territories_created" FOREIGN KEY ("created_by_user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "territory_active" to table: "territories"
CREATE INDEX "territory_active" ON "territories" ("active");
-- Create index "territory_created_at" to table: "territories"
CREATE INDEX "territory_created_at" ON "territories" ("created_at");
-- Create index "territory_created_by_user_id" to table: "territories"
CREATE INDEX "territory_created_by_user_id" ON "territories" ("created_by_user_id");
-- Create "leads" table
CREATE TABLE "leads" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "industry" character varying NOT NULL,
  "country" character varying NOT NULL,
  "city" character varying NOT NULL,
  "address" character varying NULL,
  "postal_code" character varying NULL,
  "phone" character varying NULL,
  "email" character varying NULL,
  "website" character varying NULL,
  "social_media" jsonb NULL,
  "latitude" double precision NULL,
  "longitude" double precision NULL,
  "verified" boolean NOT NULL DEFAULT false,
  "quality_score" bigint NOT NULL DEFAULT 50,
  "status" character varying NOT NULL DEFAULT 'new',
  "status_changed_at" timestamptz NOT NULL,
  "custom_fields" jsonb NULL,
  "osm_id" character varying NULL,
  "metadata" jsonb NULL,
  "sub_niche" character varying NULL,
  "specialties" jsonb NULL,
  "cuisine_type" character varying NULL,
  "sport_type" character varying NULL,
  "tattoo_style" character varying NULL,
  "company_description" character varying NULL,
  "employee_count" bigint NULL,
  "company_revenue" character varying NULL,
  "linkedin_url" character varying NULL,
  "twitter_url" character varying NULL,
  "facebook_url" character varying NULL,
  "is_enriched" boolean NOT NULL DEFAULT false,
  "enriched_at" timestamptz NULL,
  "email_validated" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "territory_leads" bigint NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "leads_territories_leads" FOREIGN KEY ("territory_leads") REFERENCES "territories" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create index "lead_country_city" to table: "leads"
CREATE INDEX "lead_country_city" ON "leads" ("country", "city");
-- Create index "lead_created_at" to table: "leads"
CREATE INDEX "lead_created_at" ON "leads" ("created_at");
-- Create index "lead_cuisine_type" to table: "leads"
CREATE INDEX "lead_cuisine_type" ON "leads" ("cuisine_type");
-- Create index "lead_email" to table: "leads"
CREATE INDEX "lead_email" ON "leads" ("email");
-- Create index "lead_industry_country" to table: "leads"
CREATE INDEX "lead_industry_country" ON "leads" ("industry", "country");
-- Create index "lead_industry_country_city" to table: "leads"
CREATE INDEX "lead_industry_country_city" ON "leads" ("industry", "country", "city");
-- Create index "lead_industry_country_sub_niche" to table: "leads"
CREATE INDEX "lead_industry_country_sub_niche" ON "leads" ("industry", "country", "sub_niche");
-- Create index "lead_industry_sub_niche" to table: "leads"
CREATE INDEX "lead_industry_sub_niche" ON "leads" ("industry", "sub_niche");
-- Create index "lead_latitude_longitude" to table: "leads"
CREATE INDEX "lead_latitude_longitude" ON "leads" ("latitude", "longitude");
-- Create index "lead_osm_id" to table: "leads"
CREATE UNIQUE INDEX "lead_osm_id" ON "leads" ("osm_id");
-- Create index "lead_phone" to table: "leads"
CREATE INDEX "lead_phone" ON "leads" ("phone");
-- Create index "lead_quality_score" to table: "leads"
CREATE INDEX "lead_quality_score" ON "leads" ("quality_score");
-- Create index "lead_sport_type" to table: "leads"
CREATE INDEX "lead_sport_type" ON "leads" ("sport_type");
-- Create index "lead_sub_niche" to table: "leads"
CREATE INDEX "lead_sub_niche" ON "leads" ("sub_niche");
-- Create index "lead_tattoo_style" to table: "leads"
CREATE INDEX "lead_tattoo_style" ON "leads" ("tattoo_style");
-- Create index "lead_verified" to table: "leads"
CREATE INDEX "lead_verified" ON "leads" ("verified");
-- Create "call_logs" table
CREATE TABLE "call_logs" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "phone_number" character varying NOT NULL,
  "direction" character varying NOT NULL,
  "status" character varying NOT NULL DEFAULT 'initiated',
  "duration" bigint NOT NULL DEFAULT 0,
  "provider_call_id" character varying NULL,
  "from_number" character varying NULL,
  "to_number" character varying NULL,
  "cost" double precision NOT NULL DEFAULT 0,
  "recording_url" character varying NULL,
  "recording_duration" bigint NULL,
  "notes" text NULL,
  "disposition" character varying NULL,
  "is_recorded" boolean NOT NULL DEFAULT false,
  "started_at" timestamptz NULL,
  "ended_at" timestamptz NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "lead_id" bigint NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "call_logs_leads_call_logs" FOREIGN KEY ("lead_id") REFERENCES "leads" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "call_logs_users_call_logs" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "calllog_created_at" to table: "call_logs"
CREATE INDEX "calllog_created_at" ON "call_logs" ("created_at");
-- Create index "calllog_direction" to table: "call_logs"
CREATE INDEX "calllog_direction" ON "call_logs" ("direction");
-- Create index "calllog_lead_id" to table: "call_logs"
CREATE INDEX "calllog_lead_id" ON "call_logs" ("lead_id");
-- Create index "calllog_provider_call_id" to table: "call_logs"
CREATE INDEX "calllog_provider_call_id" ON "call_logs" ("provider_call_id");
-- Create index "calllog_started_at" to table: "call_logs"
CREATE INDEX "calllog_started_at" ON "call_logs" ("started_at");
-- Create index "calllog_status" to table: "call_logs"
CREATE INDEX "calllog_status" ON "call_logs" ("status");
-- Create index "calllog_user_id" to table: "call_logs"
CREATE INDEX "calllog_user_id" ON "call_logs" ("user_id");
-- Create "competitor_profiles" table
CREATE TABLE "competitor_profiles" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "website" character varying NULL,
  "industry" character varying NOT NULL,
  "country" character varying NULL,
  "description" text NULL,
  "market_position" character varying NULL,
  "estimated_employees" bigint NULL,
  "estimated_revenue" character varying NULL,
  "strengths" jsonb NULL,
  "weaknesses" jsonb NULL,
  "products" jsonb NULL,
  "pricing_tiers" jsonb NULL,
  "target_markets" jsonb NULL,
  "linkedin_url" character varying NULL,
  "twitter_handle" character varying NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  "last_analyzed_at" timestamptz NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "competitor_profiles_users_competitor_profiles" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "competitorprofile_country" to table: "competitor_profiles"
CREATE INDEX "competitorprofile_country" ON "competitor_profiles" ("country");
-- Create index "competitorprofile_created_at" to table: "competitor_profiles"
CREATE INDEX "competitorprofile_created_at" ON "competitor_profiles" ("created_at");
-- Create index "competitorprofile_industry" to table: "competitor_profiles"
CREATE INDEX "competitorprofile_industry" ON "competitor_profiles" ("industry");
-- Create index "competitorprofile_is_active" to table: "competitor_profiles"
CREATE INDEX "competitorprofile_is_active" ON "competitor_profiles" ("is_active");
-- Create index "competitorprofile_user_id" to table: "competitor_profiles"
CREATE INDEX "competitorprofile_user_id" ON "competitor_profiles" ("user_id");
-- Create "competitor_metrics" table
CREATE TABLE "competitor_metrics" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "metric_type" character varying NOT NULL,
  "metric_name" character varying NOT NULL,
  "metric_value" text NOT NULL,
  "numeric_value" double precision NULL,
  "unit" character varying NULL,
  "notes" text NULL,
  "source" character varying NULL,
  "recorded_at" timestamptz NOT NULL,
  "created_at" timestamptz NOT NULL,
  "competitor_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "competitor_metrics_competitor_profiles_metrics" FOREIGN KEY ("competitor_id") REFERENCES "competitor_profiles" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "competitormetric_competitor_id" to table: "competitor_metrics"
CREATE INDEX "competitormetric_competitor_id" ON "competitor_metrics" ("competitor_id");
-- Create index "competitormetric_created_at" to table: "competitor_metrics"
CREATE INDEX "competitormetric_created_at" ON "competitor_metrics" ("created_at");
-- Create index "competitormetric_metric_name" to table: "competitor_metrics"
CREATE INDEX "competitormetric_metric_name" ON "competitor_metrics" ("metric_name");
-- Create index "competitormetric_metric_type" to table: "competitor_metrics"
CREATE INDEX "competitormetric_metric_type" ON "competitor_metrics" ("metric_type");
-- Create index "competitormetric_recorded_at" to table: "competitor_metrics"
CREATE INDEX "competitormetric_recorded_at" ON "competitor_metrics" ("recorded_at");
-- Create "email_sequences" table
CREATE TABLE "email_sequences" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "description" text NULL,
  "status" character varying NOT NULL DEFAULT 'draft',
  "trigger" character varying NOT NULL DEFAULT 'manual',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by_user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "email_sequences_users_email_sequences_created" FOREIGN KEY ("created_by_user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "emailsequence_created_at" to table: "email_sequences"
CREATE INDEX "emailsequence_created_at" ON "email_sequences" ("created_at");
-- Create index "emailsequence_created_by_user_id" to table: "email_sequences"
CREATE INDEX "emailsequence_created_by_user_id" ON "email_sequences" ("created_by_user_id");
-- Create index "emailsequence_status" to table: "email_sequences"
CREATE INDEX "emailsequence_status" ON "email_sequences" ("status");
-- Create index "emailsequence_trigger" to table: "email_sequences"
CREATE INDEX "emailsequence_trigger" ON "email_sequences" ("trigger");
-- Create "email_sequence_enrollments" table
CREATE TABLE "email_sequence_enrollments" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "status" character varying NOT NULL DEFAULT 'active',
  "current_step" bigint NOT NULL DEFAULT 0,
  "enrolled_at" timestamptz NOT NULL,
  "completed_at" timestamptz NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "sequence_id" bigint NOT NULL,
  "lead_id" bigint NOT NULL,
  "enrolled_by_user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "email_sequence_enrollments_email_sequences_enrollments" FOREIGN KEY ("sequence_id") REFERENCES "email_sequences" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "email_sequence_enrollments_leads_email_sequence_enrollments" FOREIGN KEY ("lead_id") REFERENCES "leads" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "email_sequence_enrollments_users_email_sequence_enrollments_mad" FOREIGN KEY ("enrolled_by_user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "idx_enrollment_lead_status" to table: "email_sequence_enrollments"
CREATE INDEX "idx_enrollment_lead_status" ON "email_sequence_enrollments" ("lead_id", "status");
-- Create index "idx_enrollment_sequence_status" to table: "email_sequence_enrollments"
CREATE INDEX "idx_enrollment_sequence_status" ON "email_sequence_enrollments" ("sequence_id", "status");
-- Create index "idx_enrollment_time" to table: "email_sequence_enrollments"
CREATE INDEX "idx_enrollment_time" ON "email_sequence_enrollments" ("enrolled_at");
-- Create index "idx_enrollment_unique" to table: "email_sequence_enrollments"
CREATE UNIQUE INDEX "idx_enrollment_unique" ON "email_sequence_enrollments" ("sequence_id", "lead_id");
-- Create "email_sequence_steps" table
CREATE TABLE "email_sequence_steps" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "step_order" bigint NOT NULL,
  "delay_days" bigint NOT NULL DEFAULT 0,
  "subject" character varying NOT NULL,
  "body" text NOT NULL,
  "created_at" timestamptz NOT NULL,
  "sequence_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "email_sequence_steps_email_sequences_steps" FOREIGN KEY ("sequence_id") REFERENCES "email_sequences" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "idx_email_sequence_step_order" to table: "email_sequence_steps"
CREATE UNIQUE INDEX "idx_email_sequence_step_order" ON "email_sequence_steps" ("sequence_id", "step_order");
-- Create "email_sequence_sends" table
CREATE TABLE "email_sequence_sends" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "status" character varying NOT NULL DEFAULT 'scheduled',
  "scheduled_for" timestamptz NOT NULL,
  "sent_at" timestamptz NULL,
  "opened_at" timestamptz NULL,
  "clicked_at" timestamptz NULL,
  "bounced" boolean NOT NULL DEFAULT false,
  "error_message" text NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "enrollment_id" bigint NOT NULL,
  "step_id" bigint NOT NULL,
  "lead_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "email_sequence_sends_email_sequence_enrollments_sends" FOREIGN KEY ("enrollment_id") REFERENCES "email_sequence_enrollments" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "email_sequence_sends_email_sequence_steps_sends" FOREIGN KEY ("step_id") REFERENCES "email_sequence_steps" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "email_sequence_sends_leads_email_sequence_sends" FOREIGN KEY ("lead_id") REFERENCES "leads" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "idx_send_enrollment_status" to table: "email_sequence_sends"
CREATE INDEX "idx_send_enrollment_status" ON "email_sequence_sends" ("enrollment_id", "status");
-- Create index "idx_send_lead_status" to table: "email_sequence_sends"
CREATE INDEX "idx_send_lead_status" ON "email_sequence_sends" ("lead_id", "status");
-- Create index "idx_send_opened" to table: "email_sequence_sends"
CREATE INDEX "idx_send_opened" ON "email_sequence_sends" ("opened_at");
-- Create index "idx_send_scheduled" to table: "email_sequence_sends"
CREATE INDEX "idx_send_scheduled" ON "email_sequence_sends" ("status", "scheduled_for");
-- Create index "idx_send_time" to table: "email_sequence_sends"
CREATE INDEX "idx_send_time" ON "email_sequence_sends" ("sent_at");
-- Create "experiments" table
CREATE TABLE "experiments" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "key" character varying NOT NULL,
  "description" text NULL,
  "status" character varying NOT NULL DEFAULT 'draft',
  "variants" jsonb NOT NULL,
  "traffic_split" jsonb NOT NULL,
  "start_date" timestamptz NULL,
  "end_date" timestamptz NULL,
  "target_metric" character varying NULL,
  "confidence_level" double precision NOT NULL DEFAULT 0.95,
  "min_sample_size" bigint NOT NULL DEFAULT 100,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "experiment_end_date" to table: "experiments"
CREATE INDEX "experiment_end_date" ON "experiments" ("end_date");
-- Create index "experiment_key" to table: "experiments"
CREATE UNIQUE INDEX "experiment_key" ON "experiments" ("key");
-- Create index "experiment_start_date" to table: "experiments"
CREATE INDEX "experiment_start_date" ON "experiments" ("start_date");
-- Create index "experiment_status" to table: "experiments"
CREATE INDEX "experiment_status" ON "experiments" ("status");
-- Create index "experiments_key_key" to table: "experiments"
CREATE UNIQUE INDEX "experiments_key_key" ON "experiments" ("key");
-- Create "experiment_assignments" table
CREATE TABLE "experiment_assignments" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "variant" character varying NOT NULL,
  "exposed" boolean NOT NULL DEFAULT false,
  "exposed_at" timestamptz NULL,
  "converted" boolean NOT NULL DEFAULT false,
  "converted_at" timestamptz NULL,
  "metric_value" double precision NULL,
  "created_at" timestamptz NOT NULL,
  "experiment_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "experiment_assignments_experiments_assignments" FOREIGN KEY ("experiment_id") REFERENCES "experiments" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "experiment_assignments_users_experiment_assignments" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "experimentassignment_converted" to table: "experiment_assignments"
CREATE INDEX "experimentassignment_converted" ON "experiment_assignments" ("converted");
-- Create index "experimentassignment_experiment_id_variant" to table: "experiment_assignments"
CREATE INDEX "experimentassignment_experiment_id_variant" ON "experiment_assignments" ("experiment_id", "variant");
-- Create index "experimentassignment_exposed" to table: "experiment_assignments"
CREATE INDEX "experimentassignment_exposed" ON "experiment_assignments" ("exposed");
-- Create index "experimentassignment_user_id_experiment_id" to table: "experiment_assignments"
CREATE UNIQUE INDEX "experimentassignment_user_id_experiment_id" ON "experiment_assignments" ("user_id", "experiment_id");
-- Create "organizations" table
CREATE TABLE "organizations" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "slug" character varying NOT NULL,
  "subscription_tier" character varying NOT NULL DEFAULT 'free',
  "usage_limit" bigint NOT NULL DEFAULT 50,
  "usage_count" bigint NOT NULL DEFAULT 0,
  "last_reset_at" timestamptz NOT NULL,
  "stripe_customer_id" character varying NULL,
  "billing_email" character varying NULL,
  "active" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "saml_enabled" boolean NOT NULL DEFAULT false,
  "saml_idp_metadata_url" text NULL,
  "saml_idp_entity_id" text NULL,
  "saml_certificate" text NULL,
  "saml_private_key" text NULL,
  "owner_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "organizations_users_owned_organizations" FOREIGN KEY ("owner_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "organization_active" to table: "organizations"
CREATE INDEX "organization_active" ON "organizations" ("active");
-- Create index "organization_created_at" to table: "organizations"
CREATE INDEX "organization_created_at" ON "organizations" ("created_at");
-- Create index "organization_owner_id" to table: "organizations"
CREATE INDEX "organization_owner_id" ON "organizations" ("owner_id");
-- Create index "organization_slug" to table: "organizations"
CREATE UNIQUE INDEX "organization_slug" ON "organizations" ("slug");
-- Create index "organization_subscription_tier" to table: "organizations"
CREATE INDEX "organization_subscription_tier" ON "organizations" ("subscription_tier");
-- Create index "organizations_slug_key" to table: "organizations"
CREATE UNIQUE INDEX "organizations_slug_key" ON "organizations" ("slug");
-- Create "exports" table
CREATE TABLE "exports" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "format" character varying NOT NULL,
  "filters_applied" jsonb NULL,
  "lead_count" bigint NOT NULL,
  "file_url" character varying NULL,
  "file_path" character varying NULL,
  "status" character varying NOT NULL DEFAULT 'pending',
  "error_message" character varying NULL,
  "expires_at" timestamptz NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "organization_id" bigint NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "exports_organizations_exports" FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "exports_users_exports" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "export_created_at" to table: "exports"
CREATE INDEX "export_created_at" ON "exports" ("created_at");
-- Create index "export_expires_at" to table: "exports"
CREATE INDEX "export_expires_at" ON "exports" ("expires_at");
-- Create index "export_organization_id" to table: "exports"
CREATE INDEX "export_organization_id" ON "exports" ("organization_id");
-- Create index "export_status" to table: "exports"
CREATE INDEX "export_status" ON "exports" ("status");
-- Create index "export_user_id" to table: "exports"
CREATE INDEX "export_user_id" ON "exports" ("user_id");
-- Create "lead_assignments" table
CREATE TABLE "lead_assignments" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "assignment_type" character varying NOT NULL DEFAULT 'manual',
  "assignment_reason" character varying NULL,
  "assigned_at" timestamptz NOT NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz NOT NULL,
  "lead_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "assigned_by_user_id" bigint NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "lead_assignments_leads_assignments" FOREIGN KEY ("lead_id") REFERENCES "leads" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "lead_assignments_users_assigned_leads" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "lead_assignments_users_lead_assignments_made" FOREIGN KEY ("assigned_by_user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create index "idx_lead_assignment_lead_active" to table: "lead_assignments"
CREATE INDEX "idx_lead_assignment_lead_active" ON "lead_assignments" ("lead_id", "is_active");
-- Create index "idx_lead_assignment_time" to table: "lead_assignments"
CREATE INDEX "idx_lead_assignment_time" ON "lead_assignments" ("assigned_at");
-- Create index "idx_lead_assignment_type_time" to table: "lead_assignments"
CREATE INDEX "idx_lead_assignment_type_time" ON "lead_assignments" ("assignment_type", "assigned_at");
-- Create index "idx_lead_assignment_user_active" to table: "lead_assignments"
CREATE INDEX "idx_lead_assignment_user_active" ON "lead_assignments" ("user_id", "is_active");
-- Create "lead_notes" table
CREATE TABLE "lead_notes" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "content" character varying NOT NULL,
  "is_pinned" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "lead_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "lead_notes_leads_notes" FOREIGN KEY ("lead_id") REFERENCES "leads" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "lead_notes_users_lead_notes" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "leadnote_lead_id_created_at" to table: "lead_notes"
CREATE INDEX "leadnote_lead_id_created_at" ON "lead_notes" ("lead_id", "created_at");
-- Create index "leadnote_lead_id_is_pinned_created_at" to table: "lead_notes"
CREATE INDEX "leadnote_lead_id_is_pinned_created_at" ON "lead_notes" ("lead_id", "is_pinned", "created_at");
-- Create index "leadnote_user_id_created_at" to table: "lead_notes"
CREATE INDEX "leadnote_user_id_created_at" ON "lead_notes" ("user_id", "created_at");
-- Create "lead_recommendations" table
CREATE TABLE "lead_recommendations" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "score" double precision NOT NULL,
  "reason" character varying NOT NULL,
  "status" character varying NOT NULL DEFAULT 'pending',
  "metadata" jsonb NULL,
  "expires_at" timestamptz NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "lead_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "lead_recommendations_leads_recommendations" FOREIGN KEY ("lead_id") REFERENCES "leads" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "lead_recommendations_users_lead_recommendations" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "leadrecommendation_created_at" to table: "lead_recommendations"
CREATE INDEX "leadrecommendation_created_at" ON "lead_recommendations" ("created_at");
-- Create index "leadrecommendation_expires_at" to table: "lead_recommendations"
CREATE INDEX "leadrecommendation_expires_at" ON "lead_recommendations" ("expires_at");
-- Create index "leadrecommendation_lead_id" to table: "lead_recommendations"
CREATE INDEX "leadrecommendation_lead_id" ON "lead_recommendations" ("lead_id");
-- Create index "leadrecommendation_score" to table: "lead_recommendations"
CREATE INDEX "leadrecommendation_score" ON "lead_recommendations" ("score");
-- Create index "leadrecommendation_status" to table: "lead_recommendations"
CREATE INDEX "leadrecommendation_status" ON "lead_recommendations" ("status");
-- Create index "leadrecommendation_user_id" to table: "lead_recommendations"
CREATE INDEX "leadrecommendation_user_id" ON "lead_recommendations" ("user_id");
-- Create "lead_status_histories" table
CREATE TABLE "lead_status_histories" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "old_status" character varying NULL,
  "new_status" character varying NOT NULL,
  "reason" character varying NULL,
  "created_at" timestamptz NOT NULL,
  "lead_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "lead_status_histories_leads_status_history" FOREIGN KEY ("lead_id") REFERENCES "leads" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "lead_status_histories_users_lead_status_changes" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "idx_lead_status_history_lead_time" to table: "lead_status_histories"
CREATE INDEX "idx_lead_status_history_lead_time" ON "lead_status_histories" ("lead_id", "created_at");
-- Create index "idx_lead_status_history_status_time" to table: "lead_status_histories"
CREATE INDEX "idx_lead_status_history_status_time" ON "lead_status_histories" ("new_status", "created_at");
-- Create index "idx_lead_status_history_user" to table: "lead_status_histories"
CREATE INDEX "idx_lead_status_history_user" ON "lead_status_histories" ("user_id");
-- Create "market_reports" table
CREATE TABLE "market_reports" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "title" character varying NOT NULL,
  "industry" character varying NOT NULL,
  "country" character varying NULL,
  "report_type" character varying NOT NULL,
  "data" jsonb NOT NULL,
  "metadata" jsonb NULL,
  "period_start" timestamptz NOT NULL,
  "period_end" timestamptz NOT NULL,
  "generated_at" timestamptz NOT NULL,
  "expires_at" timestamptz NULL,
  "created_at" timestamptz NOT NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "market_reports_users_market_reports" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "marketreport_country" to table: "market_reports"
CREATE INDEX "marketreport_country" ON "market_reports" ("country");
-- Create index "marketreport_created_at" to table: "market_reports"
CREATE INDEX "marketreport_created_at" ON "market_reports" ("created_at");
-- Create index "marketreport_generated_at" to table: "market_reports"
CREATE INDEX "marketreport_generated_at" ON "market_reports" ("generated_at");
-- Create index "marketreport_industry" to table: "market_reports"
CREATE INDEX "marketreport_industry" ON "market_reports" ("industry");
-- Create index "marketreport_report_type" to table: "market_reports"
CREATE INDEX "marketreport_report_type" ON "market_reports" ("report_type");
-- Create index "marketreport_user_id" to table: "market_reports"
CREATE INDEX "marketreport_user_id" ON "market_reports" ("user_id");
-- Create "organization_members" table
CREATE TABLE "organization_members" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "role" character varying NOT NULL DEFAULT 'member',
  "invited_by_email" character varying NULL,
  "status" character varying NOT NULL DEFAULT 'active',
  "invited_at" timestamptz NULL,
  "joined_at" timestamptz NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "organization_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "organization_members_organizations_members" FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "organization_members_users_organization_memberships" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "organizationmember_created_at" to table: "organization_members"
CREATE INDEX "organizationmember_created_at" ON "organization_members" ("created_at");
-- Create index "organizationmember_organization_id" to table: "organization_members"
CREATE INDEX "organizationmember_organization_id" ON "organization_members" ("organization_id");
-- Create index "organizationmember_organization_id_user_id" to table: "organization_members"
CREATE UNIQUE INDEX "organizationmember_organization_id_user_id" ON "organization_members" ("organization_id", "user_id");
-- Create index "organizationmember_role" to table: "organization_members"
CREATE INDEX "organizationmember_role" ON "organization_members" ("role");
-- Create index "organizationmember_status" to table: "organization_members"
CREATE INDEX "organizationmember_status" ON "organization_members" ("status");
-- Create index "organizationmember_user_id" to table: "organization_members"
CREATE INDEX "organizationmember_user_id" ON "organization_members" ("user_id");
-- Create "referrals" table
CREATE TABLE "referrals" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "referral_code" character varying NOT NULL,
  "status" character varying NOT NULL DEFAULT 'pending',
  "reward_type" character varying NOT NULL DEFAULT 'credit',
  "reward_amount" double precision NOT NULL DEFAULT 0,
  "created_at" timestamptz NOT NULL,
  "completed_at" timestamptz NULL,
  "rewarded_at" timestamptz NULL,
  "expires_at" timestamptz NULL,
  "referrer_user_id" bigint NOT NULL,
  "referred_user_id" bigint NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "referrals_users_received_referrals" FOREIGN KEY ("referred_user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "referrals_users_sent_referrals" FOREIGN KEY ("referrer_user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "referral_referral_code" to table: "referrals"
CREATE UNIQUE INDEX "referral_referral_code" ON "referrals" ("referral_code");
-- Create index "referral_referrer_user_id" to table: "referrals"
CREATE INDEX "referral_referrer_user_id" ON "referrals" ("referrer_user_id");
-- Create index "referral_referrer_user_id_status" to table: "referrals"
CREATE INDEX "referral_referrer_user_id_status" ON "referrals" ("referrer_user_id", "status");
-- Create index "referral_status" to table: "referrals"
CREATE INDEX "referral_status" ON "referrals" ("status");
-- Create index "referrals_referral_code_key" to table: "referrals"
CREATE UNIQUE INDEX "referrals_referral_code_key" ON "referrals" ("referral_code");
-- Create "saved_searches" table
CREATE TABLE "saved_searches" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "filters" jsonb NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "saved_searches_users_saved_searches" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "savedsearch_created_at" to table: "saved_searches"
CREATE INDEX "savedsearch_created_at" ON "saved_searches" ("created_at");
-- Create index "savedsearch_user_id" to table: "saved_searches"
CREATE INDEX "savedsearch_user_id" ON "saved_searches" ("user_id");
-- Create "sms_campaigns" table
CREATE TABLE "sms_campaigns" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "message_template" text NOT NULL,
  "target_filters" jsonb NULL,
  "status" character varying NOT NULL DEFAULT 'draft',
  "scheduled_at" timestamptz NULL,
  "sent_at" timestamptz NULL,
  "total_recipients" bigint NOT NULL DEFAULT 0,
  "sent_count" bigint NOT NULL DEFAULT 0,
  "delivered_count" bigint NOT NULL DEFAULT 0,
  "failed_count" bigint NOT NULL DEFAULT 0,
  "estimated_cost" double precision NOT NULL DEFAULT 0,
  "actual_cost" double precision NOT NULL DEFAULT 0,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "sms_campaigns_users_sms_campaigns" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "smscampaign_created_at" to table: "sms_campaigns"
CREATE INDEX "smscampaign_created_at" ON "sms_campaigns" ("created_at");
-- Create index "smscampaign_scheduled_at" to table: "sms_campaigns"
CREATE INDEX "smscampaign_scheduled_at" ON "sms_campaigns" ("scheduled_at");
-- Create index "smscampaign_status" to table: "sms_campaigns"
CREATE INDEX "smscampaign_status" ON "sms_campaigns" ("status");
-- Create index "smscampaign_user_id" to table: "sms_campaigns"
CREATE INDEX "smscampaign_user_id" ON "sms_campaigns" ("user_id");
-- Create "sms_messages" table
CREATE TABLE "sms_messages" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "phone_number" character varying NOT NULL,
  "message_body" text NOT NULL,
  "twilio_sid" character varying NULL,
  "status" character varying NOT NULL DEFAULT 'queued',
  "error_message" character varying NULL,
  "error_code" bigint NULL,
  "cost" double precision NOT NULL DEFAULT 0,
  "sent_at" timestamptz NULL,
  "delivered_at" timestamptz NULL,
  "failed_at" timestamptz NULL,
  "created_at" timestamptz NOT NULL,
  "lead_id" bigint NULL,
  "campaign_id" bigint NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "sms_messages_leads_sms_messages" FOREIGN KEY ("lead_id") REFERENCES "leads" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "sms_messages_sms_campaigns_messages" FOREIGN KEY ("campaign_id") REFERENCES "sms_campaigns" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create index "smsmessage_campaign_id" to table: "sms_messages"
CREATE INDEX "smsmessage_campaign_id" ON "sms_messages" ("campaign_id");
-- Create index "smsmessage_created_at" to table: "sms_messages"
CREATE INDEX "smsmessage_created_at" ON "sms_messages" ("created_at");
-- Create index "smsmessage_lead_id" to table: "sms_messages"
CREATE INDEX "smsmessage_lead_id" ON "sms_messages" ("lead_id");
-- Create index "smsmessage_status" to table: "sms_messages"
CREATE INDEX "smsmessage_status" ON "sms_messages" ("status");
-- Create index "smsmessage_twilio_sid" to table: "sms_messages"
CREATE INDEX "smsmessage_twilio_sid" ON "sms_messages" ("twilio_sid");
-- Create "subscriptions" table
CREATE TABLE "subscriptions" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "tier" character varying NOT NULL,
  "status" character varying NOT NULL DEFAULT 'active',
  "stripe_subscription_id" character varying NULL,
  "stripe_price_id" character varying NULL,
  "current_period_start" timestamptz NULL,
  "current_period_end" timestamptz NULL,
  "cancel_at_period_end" boolean NOT NULL DEFAULT false,
  "canceled_at" timestamptz NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "subscriptions_users_subscriptions" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "subscription_created_at" to table: "subscriptions"
CREATE INDEX "subscription_created_at" ON "subscriptions" ("created_at");
-- Create index "subscription_status" to table: "subscriptions"
CREATE INDEX "subscription_status" ON "subscriptions" ("status");
-- Create index "subscription_stripe_subscription_id" to table: "subscriptions"
CREATE UNIQUE INDEX "subscription_stripe_subscription_id" ON "subscriptions" ("stripe_subscription_id");
-- Create index "subscription_user_id" to table: "subscriptions"
CREATE INDEX "subscription_user_id" ON "subscriptions" ("user_id");
-- Create "territory_members" table
CREATE TABLE "territory_members" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "role" character varying NOT NULL DEFAULT 'member',
  "joined_at" timestamptz NOT NULL,
  "territory_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "added_by_user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "territory_members_territories_members" FOREIGN KEY ("territory_id") REFERENCES "territories" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "territory_members_users_territory_members_added" FOREIGN KEY ("added_by_user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "territory_members_users_territory_memberships" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "territorymember_role" to table: "territory_members"
CREATE INDEX "territorymember_role" ON "territory_members" ("role");
-- Create index "territorymember_territory_id_user_id" to table: "territory_members"
CREATE UNIQUE INDEX "territorymember_territory_id_user_id" ON "territory_members" ("territory_id", "user_id");
-- Create index "territorymember_user_id" to table: "territory_members"
CREATE INDEX "territorymember_user_id" ON "territory_members" ("user_id");
-- Create "usage_logs" table
CREATE TABLE "usage_logs" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "action" character varying NOT NULL,
  "count" bigint NOT NULL DEFAULT 1,
  "metadata" jsonb NULL,
  "created_at" timestamptz NOT NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "usage_logs_users_usage_logs" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "usagelog_action" to table: "usage_logs"
CREATE INDEX "usagelog_action" ON "usage_logs" ("action");
-- Create index "usagelog_created_at" to table: "usage_logs"
CREATE INDEX "usagelog_created_at" ON "usage_logs" ("created_at");
-- Create index "usagelog_user_id_created_at" to table: "usage_logs"
CREATE INDEX "usagelog_user_id_created_at" ON "usage_logs" ("user_id", "created_at");
-- Create "user_behaviors" table
CREATE TABLE "user_behaviors" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "action_type" character varying NOT NULL,
  "lead_id" bigint NULL,
  "industry" character varying NULL,
  "country" character varying NULL,
  "city" character varying NULL,
  "metadata" jsonb NULL,
  "created_at" timestamptz NOT NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "user_behaviors_users_behaviors" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "userbehavior_action_type" to table: "user_behaviors"
CREATE INDEX "userbehavior_action_type" ON "user_behaviors" ("action_type");
-- Create index "userbehavior_country" to table: "user_behaviors"
CREATE INDEX "userbehavior_country" ON "user_behaviors" ("country");
-- Create index "userbehavior_created_at" to table: "user_behaviors"
CREATE INDEX "userbehavior_created_at" ON "user_behaviors" ("created_at");
-- Create index "userbehavior_industry" to table: "user_behaviors"
CREATE INDEX "userbehavior_industry" ON "user_behaviors" ("industry");
-- Create index "userbehavior_lead_id" to table: "user_behaviors"
CREATE INDEX "userbehavior_lead_id" ON "user_behaviors" ("lead_id");
-- Create index "userbehavior_user_id" to table: "user_behaviors"
CREATE INDEX "userbehavior_user_id" ON "user_behaviors" ("user_id");
-- Create "webhooks" table
CREATE TABLE "webhooks" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "url" character varying NOT NULL,
  "events" jsonb NOT NULL,
  "secret" character varying NOT NULL,
  "active" boolean NOT NULL DEFAULT true,
  "description" character varying NULL,
  "retry_count" bigint NOT NULL DEFAULT 3,
  "last_triggered_at" timestamptz NULL,
  "success_count" bigint NOT NULL DEFAULT 0,
  "failure_count" bigint NOT NULL DEFAULT 0,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "user_webhooks" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "webhooks_users_webhooks" FOREIGN KEY ("user_webhooks") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "webhook_active" to table: "webhooks"
CREATE INDEX "webhook_active" ON "webhooks" ("active");
-- Create index "webhook_created_at" to table: "webhooks"
CREATE INDEX "webhook_created_at" ON "webhooks" ("created_at");
